<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Remarks_beneRow1</name>
   <tag></tag>
   <elementGuidId>afeb8107-47e8-4c34-9850-2761e2f3e163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#beneRow1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='beneRow1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7d2618b0-2286-42ec-b812-812991fbe7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beneRow1</value>
      <webElementGuid>391ade3d-492b-46d4-818b-3cdf4f3a40b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-add-circle-fill</value>
      <webElementGuid>3c78aa83-8871-495e-be6a-dcb6dad1cd70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beneRow1&quot;)</value>
      <webElementGuid>1ed980cf-a9be-4e10-b5d7-afd02168d28c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='beneRow1']</value>
      <webElementGuid>3cdd09b8-b8bd-436c-89e6-717449e1773f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='add-benerow-button']/i</value>
      <webElementGuid>2338ae9f-a65b-4385-81a3-4c2a78db0ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/button/i</value>
      <webElementGuid>b885f216-bef1-4d43-8a99-9b5c55ecca5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'beneRow1']</value>
      <webElementGuid>b65eaaaf-eb83-4b19-8611-974c24aa475b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
