<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MiddleName_txtSpousemname</name>
   <tag></tag>
   <elementGuidId>e73a8713-ba34-4b7c-ab4c-5dfb919dfdcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSpousemname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSpousemname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c0ea5b6-5ac7-4548-ba95-5acd6e3ace6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>91a4865a-8333-4c30-84d6-9ab15050ae02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a14b16c3-a7d1-4870-bd7e-b29bd8860302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checkSpouseCharacter();</value>
      <webElementGuid>9e329cc7-25de-4219-9335-412b058cda22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs text-capitalize font-11</value>
      <webElementGuid>a1cabbfd-b8a0-4a85-b9b2-ae773754854a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>91a0cc20-ac8f-4dad-9f25-a9c8dfdc8637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSpousemname</value>
      <webElementGuid>bc3dc2e9-34ee-4528-b14c-dd4b46d8d7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSpousemname&quot;)</value>
      <webElementGuid>f995028d-62f4-425a-854e-b7fd3ecc3b7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSpousemname']</value>
      <webElementGuid>b8acd947-6018-485d-b4f3-c41ef4d78479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5']/div/div/div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>43d51361-f8a6-4495-a321-359c8b63aded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>43596c34-a2cb-467a-b993-f71b017c4d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtSpousemname']</value>
      <webElementGuid>e682f140-df02-4809-8c0a-ae78c4490493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
