<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_txtDisability2</name>
   <tag></tag>
   <elementGuidId>c27a5d0f-5617-450d-8ffb-867fd07380f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDisability2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtDisability2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a68667a5-3b30-4998-83bd-e65199d8a56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0e8ad8b7-f794-474c-83f8-ff551c24c070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDisability2</value>
      <webElementGuid>70f488b8-e3ec-40d0-83d7-d354b20d0c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>339fcfd4-25c5-4fb0-8e27-e84b212d9651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-9 text-capitalize required</value>
      <webElementGuid>3e4ff65c-9541-4641-b7b2-ca8436369ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDisability2&quot;)</value>
      <webElementGuid>54fbaa49-b257-46e5-b78b-4980e13f6ad0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtDisability2']</value>
      <webElementGuid>f61a7bc7-b47c-4e64-b244-abecf10b16bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div[8]/div/div/input</value>
      <webElementGuid>045ec8b0-bad6-4852-a961-d882b32beeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[8]/div/div/input</value>
      <webElementGuid>755d2938-e0d9-450d-b81b-f9a0b1932243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtDisability2']</value>
      <webElementGuid>4ab3fd8e-99c5-4769-bacb-9cb20a757ff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
