<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_txtBeneficiaryName3</name>
   <tag></tag>
   <elementGuidId>952b9428-4ec2-468e-83d1-a3cb2cccb059</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtBeneficiaryName3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtBeneficiaryName3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f749e162-21a8-4743-b8f7-8d7be1ac4d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2f8fe19c-4f2d-4d20-8382-00142d7ecf51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7579aa1-86ac-47c6-b2df-fa0131edb073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs text-capitalize font-9</value>
      <webElementGuid>7abea638-d83c-4e13-a81f-0de2dc62c5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7b1cc953-2bda-4ed1-bf9b-9af2069d07f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtBeneficiaryName3</value>
      <webElementGuid>d9a54e33-84e8-4855-bf0d-644b1719ee8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtBeneficiaryName3&quot;)</value>
      <webElementGuid>ab773ac8-b4b3-4a91-b37c-e1e1e5e0cdf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtBeneficiaryName3']</value>
      <webElementGuid>f0bfc132-3f9f-4962-8981-e47f57422584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row3']/div/div/div/div/input</value>
      <webElementGuid>7f08853f-a99f-4521-98d9-861834bdbe85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/div/input</value>
      <webElementGuid>35df8d78-d4e9-4b07-be45-0500b42b00a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtBeneficiaryName3']</value>
      <webElementGuid>2e714214-756f-4d31-9974-cbb2eb16aad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
