<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CID_txtSpouseCID</name>
   <tag></tag>
   <elementGuidId>4c0852e2-9465-4956-8887-adba93ad4807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSpouseCID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSpouseCID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d64b3d48-52c5-437f-abb6-76558b3213b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>03b63399-7b6d-4695-ba80-1acb1912b01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15e91deb-2d0d-4347-a71c-40b2551b5f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e091cee6-d87c-4e89-a8f9-91957a4f92ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>af7d20d9-a79d-4d29-95d9-c15455ecfa86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return onlyNumberKey(event)</value>
      <webElementGuid>d48330e7-ab3e-4aa4-8ff9-0f3e3a084a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSpouseCID</value>
      <webElementGuid>9a03e0d3-9bb0-468d-b9b0-9886b814ac9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSpouseCID&quot;)</value>
      <webElementGuid>69ad4457-1218-4fbc-abc4-1d9d34e5b237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSpouseCID']</value>
      <webElementGuid>78df7117-9509-4c06-a243-554f06fc1022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5']/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>a356b295-5844-4376-b744-0ae9a15163cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>95759e1f-26b2-433a-bbb4-6c1bfd038545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtSpouseCID']</value>
      <webElementGuid>e07d34e0-8ae2-4b34-b2b8-875c9c532ca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
