<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BusinessGovernment Employe_69ab64</name>
   <tag></tag>
   <elementGuidId>4be6c39e-2f50-40db-ab2f-f10f63136447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboSpouseOccupation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSpouseOccupation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d377c471-babf-4193-b4ec-804ba1282a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSpouseOccupation</value>
      <webElementGuid>80c265d2-7770-4bbd-9bd3-a4359ab5807d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>68eef539-159e-422d-8f78-bd4006f94ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>a5265bf2-d801-430f-9823-ec94d90205e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BusinessGovernment EmployeeOthersPrivate Emplovee</value>
      <webElementGuid>44c58268-b4ac-4243-bda0-08cd6c601629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSpouseOccupation&quot;)</value>
      <webElementGuid>88d6c0fd-f800-40ab-bffe-4c9b95ee31ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSpouseOccupation']</value>
      <webElementGuid>1ae5f481-6110-4010-a134-d0d71a69bfb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5']/div/div/div[2]/div[2]/div/div[3]/div/div/select</value>
      <webElementGuid>565c6757-b7f3-435d-9e3f-76052ce1c7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/div/div/select</value>
      <webElementGuid>e01460ae-5c19-4b59-97d9-6672ca979a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSpouseOccupation' and (text() = '--Select--BusinessGovernment EmployeeOthersPrivate Emplovee' or . = '--Select--BusinessGovernment EmployeeOthersPrivate Emplovee')]</value>
      <webElementGuid>8ab36ad8-6df5-433b-bce6-6848f38bfdd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
