<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BeneficiaryLegal Dependent_a71cea_1</name>
   <tag></tag>
   <elementGuidId>acd8e97f-7413-4f8a-bb72-b206f490b067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboRemarks2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboRemarks2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a4e528cf-3fc6-4be5-abe6-3c996392f4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboRemarks2</value>
      <webElementGuid>43fbef29-b2f0-4916-8aff-f8a06b24a270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>306c9135-210c-4692-8adf-2578f63ae7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>beneficiaryRemarks($('#txtBeneficiaryBday2').val(), $('#cboWithDisability2').val(),$('#cboRemarks2').val(),'#cboRemarks2');</value>
      <webElementGuid>29da673a-32b5-4588-8ee9-167b0dddc12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>3591ec50-80e5-4d19-b387-fe9ee517db2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary</value>
      <webElementGuid>7d19ced7-b778-454d-9606-65e2b7a1e7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboRemarks2&quot;)</value>
      <webElementGuid>e67756e0-f9a3-4d0d-8e9a-8496c78e73f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboRemarks2']</value>
      <webElementGuid>fce6dbaa-e9bd-4b38-b935-bc8f3c31bc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div[10]/div/div/select</value>
      <webElementGuid>c11e482b-f9a6-4ec5-82ce-0c830cc4508b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[14]</value>
      <webElementGuid>a37240b3-9ede-4cd2-b888-545a2dc3c090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[1]</value>
      <webElementGuid>09d34605-b39a-464f-aebb-91a0c6b145dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[1]</value>
      <webElementGuid>6c454f4b-a090-4bd4-9aa6-147ef5ed0918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[10]/div/div/select</value>
      <webElementGuid>6208788f-55a7-4c42-9595-8f85b633e715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboRemarks2' and (text() = '--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary' or . = '--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary')]</value>
      <webElementGuid>6a2c7737-d41c-413a-b800-39a5b0fa1d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
