<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--AnnulledLive-inMarriedSepa_54a068</name>
   <tag></tag>
   <elementGuidId>924a927f-cd3e-43b2-8a75-9a150245bf3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCivilStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCivilStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eddb1f6a-f998-4588-ad21-c7adf1de8483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCivilStatus</value>
      <webElementGuid>4806b99b-e1ed-406d-8073-130519d866d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CivilStatusType();</value>
      <webElementGuid>be2a3f81-2d1c-4c52-b608-543d063fa212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>00ee8f0d-4706-4a32-8242-f14d2864a254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>35fce90c-b753-4203-a75a-eed728c9c683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AnnulledLive-inMarriedSeparatedSingleWidowed</value>
      <webElementGuid>bc5625c4-3b96-4f3d-bb49-5ee279830c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCivilStatus&quot;)</value>
      <webElementGuid>4b4c3c56-1576-4de9-bedf-6513f4c08963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCivilStatus']</value>
      <webElementGuid>9ae57953-e199-4b92-b97b-d9369455d1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[12]/div/div/select</value>
      <webElementGuid>90b2e4b1-5b31-4a7b-9318-91e53abbc48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/select</value>
      <webElementGuid>f0b67894-a0c8-4a1f-a464-30e6be45d950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCivilStatus' and (text() = '--Select--AnnulledLive-inMarriedSeparatedSingleWidowed' or . = '--Select--AnnulledLive-inMarriedSeparatedSingleWidowed')]</value>
      <webElementGuid>d3a0a28e-c1c1-48fe-9340-e70397fa387c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
