<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BisexualGayLesbianQueerTra_c208c0</name>
   <tag></tag>
   <elementGuidId>7ddd52ba-71ae-41fd-a24c-341e9ca35e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSexualOrientation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboSexualOrientation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>22974c12-7b8e-4809-a1cb-ed6a8e4e0ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSexualOrientation</value>
      <webElementGuid>d0e93903-1cab-4338-8686-96ce5557dbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateTitle();</value>
      <webElementGuid>6f500c06-3262-4c36-bb8c-10a08d3213bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>0777a243-7a52-4f7e-a97a-7921ddcda07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>ac83c578-1160-4eba-9596-e4279588b7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BisexualGayLesbianQueerTransgender+AgenderAsexual+Bigender+Gender Queer+Gender VirantIntersex+Pangender+PansexualQuestioning</value>
      <webElementGuid>bb1d7051-385f-4d2e-b729-664990dff5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSexualOrientation&quot;)</value>
      <webElementGuid>61d3e56f-3616-4656-bec2-9f3c80ead1da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSexualOrientation']</value>
      <webElementGuid>85f0dfa9-8b01-4861-bcf8-4fef173afa15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[11]/div/div/select</value>
      <webElementGuid>98b1e1dc-7db6-43af-a35c-a69cdc8ce3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/select</value>
      <webElementGuid>94d25571-9ee1-41a4-8eb6-260f3d8cfb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSexualOrientation' and (text() = '--Select--BisexualGayLesbianQueerTransgender+AgenderAsexual+Bigender+Gender Queer+Gender VirantIntersex+Pangender+PansexualQuestioning' or . = '--Select--BisexualGayLesbianQueerTransgender+AgenderAsexual+Bigender+Gender Queer+Gender VirantIntersex+Pangender+PansexualQuestioning')]</value>
      <webElementGuid>6982a28a-38a2-4dca-aa72-13bed7777854</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
