<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Adasen InlaudAetaAetaAlang_82eebf</name>
   <tag></tag>
   <elementGuidId>9cb222c0-1ace-4730-bc90-bb30bd40df06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboTribetype</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboTribetype']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>54e0566b-bdba-46e3-87a3-1264fbb01a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboTribetype</value>
      <webElementGuid>c02ae33d-0585-4f2c-875a-23e51922d175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>8ac47ba3-aeb7-48d6-a136-88104fe53ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>8cecf097-23ab-47b7-8d6d-bf4925c08f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Adasen InlaudAetaAetaAlanganAlangan Mangyan TribeApplaiATA manoboATA tribeAtiAyanganBadjaoBadjaoBagoboBago- KankanaeyBanwaonbasaoBilaan, manobo kauloBilaan ,Manobo KauloBlaanBontok TribeBugkalot/Ilongot/Kankana-EyBuhid Mangyan TribeBukkalotDibabawonHanunuo Mangyan TribeHiagaononHigaononHigaonon/ ManoboIbaloiIbaloi/ Kankanaey/ IgorotIbaloy/ Kankamaey/IgorotIlocano-KankanaeyIlongot/BugkalotInlaodiraya, alanganIraya Mangyan TribeIsnagIsnag ( Imalawa)ItnegKalangoya/Bugkalot/IlongotKalangoya/Kankana-EKalanguya(Kalanguya,Ifugao)Kalibugan,TausugKali-ekankanaeyKankana-EyKankanaey/IbaloiKankanaey/Ibaloi/ KalanguyaKankana-Ey/KalangoyaKannanaey/ IgorotLumadMaengMa-gantiMaguindanaoManaboMandayaMangyan BukidManoboManobo/ MatigsalogMansakaManuboMaranaoMasadiitMatigsalogMolbogMuslimMuslim MaguindanaoMuslim MaguindanawanMuslim PalauanMuyadanName Of MamanwaName Of Tribe Or Ethnic Group: AgtaName Of Tribe Or Ethnic Group: Agta And IlongotPalauanPalawanoSamalSubanenSubanen TribeSubaninSubanin, MuslimSubanonSumadelTadyawan Mangyan TribeTagabawaTalaandigTalaandig/ManaboTalaandig/ ManoboTausogTausugTboliTboli/ MuslimTboli/MuslimTidurayTiguianTigwanahonTuwaliTuwali &amp; AyanganUmayamnon- BulonayYatuka</value>
      <webElementGuid>fc7ae923-9748-4ab4-91dc-9ac55f7bbc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboTribetype&quot;)</value>
      <webElementGuid>e410d327-54f3-4dae-aa53-94090c33527c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboTribetype']</value>
      <webElementGuid>920008d4-2a3d-40da-aeb6-794f8dea0468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8']/div/div/div/div[4]/div[2]/div/select</value>
      <webElementGuid>d67de3f7-d5ae-4832-84c5-d788f711bc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Score:'])[1]/following::select[2]</value>
      <webElementGuid>ebf5020b-50c2-4c08-9b0c-63255f92a4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health Declaration'])[1]/preceding::select[1]</value>
      <webElementGuid>be579534-7c2e-433b-b1ae-a35eb62a98e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YES'])[11]/preceding::select[1]</value>
      <webElementGuid>70b4e05f-dce0-4d12-9e58-ba51c7b01d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>6bd1180e-a046-4f29-818a-46dbf6d778e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboTribetype' and (text() = '--Select--Adasen InlaudAetaAetaAlanganAlangan Mangyan TribeApplaiATA manoboATA tribeAtiAyanganBadjaoBadjaoBagoboBago- KankanaeyBanwaonbasaoBilaan, manobo kauloBilaan ,Manobo KauloBlaanBontok TribeBugkalot/Ilongot/Kankana-EyBuhid Mangyan TribeBukkalotDibabawonHanunuo Mangyan TribeHiagaononHigaononHigaonon/ ManoboIbaloiIbaloi/ Kankanaey/ IgorotIbaloy/ Kankamaey/IgorotIlocano-KankanaeyIlongot/BugkalotInlaodiraya, alanganIraya Mangyan TribeIsnagIsnag ( Imalawa)ItnegKalangoya/Bugkalot/IlongotKalangoya/Kankana-EKalanguya(Kalanguya,Ifugao)Kalibugan,TausugKali-ekankanaeyKankana-EyKankanaey/IbaloiKankanaey/Ibaloi/ KalanguyaKankana-Ey/KalangoyaKannanaey/ IgorotLumadMaengMa-gantiMaguindanaoManaboMandayaMangyan BukidManoboManobo/ MatigsalogMansakaManuboMaranaoMasadiitMatigsalogMolbogMuslimMuslim MaguindanaoMuslim MaguindanawanMuslim PalauanMuyadanName Of MamanwaName Of Tribe Or Ethnic Group: AgtaName Of Tribe Or Ethnic Group: Agta And IlongotPalauanPalawanoSamalSubanenSubanen TribeSubaninSubanin, MuslimSubanonSumadelTadyawan Mangyan TribeTagabawaTalaandigTalaandig/ManaboTalaandig/ ManoboTausogTausugTboliTboli/ MuslimTboli/MuslimTidurayTiguianTigwanahonTuwaliTuwali &amp; AyanganUmayamnon- BulonayYatuka' or . = '--Select--Adasen InlaudAetaAetaAlanganAlangan Mangyan TribeApplaiATA manoboATA tribeAtiAyanganBadjaoBadjaoBagoboBago- KankanaeyBanwaonbasaoBilaan, manobo kauloBilaan ,Manobo KauloBlaanBontok TribeBugkalot/Ilongot/Kankana-EyBuhid Mangyan TribeBukkalotDibabawonHanunuo Mangyan TribeHiagaononHigaononHigaonon/ ManoboIbaloiIbaloi/ Kankanaey/ IgorotIbaloy/ Kankamaey/IgorotIlocano-KankanaeyIlongot/BugkalotInlaodiraya, alanganIraya Mangyan TribeIsnagIsnag ( Imalawa)ItnegKalangoya/Bugkalot/IlongotKalangoya/Kankana-EKalanguya(Kalanguya,Ifugao)Kalibugan,TausugKali-ekankanaeyKankana-EyKankanaey/IbaloiKankanaey/Ibaloi/ KalanguyaKankana-Ey/KalangoyaKannanaey/ IgorotLumadMaengMa-gantiMaguindanaoManaboMandayaMangyan BukidManoboManobo/ MatigsalogMansakaManuboMaranaoMasadiitMatigsalogMolbogMuslimMuslim MaguindanaoMuslim MaguindanawanMuslim PalauanMuyadanName Of MamanwaName Of Tribe Or Ethnic Group: AgtaName Of Tribe Or Ethnic Group: Agta And IlongotPalauanPalawanoSamalSubanenSubanen TribeSubaninSubanin, MuslimSubanonSumadelTadyawan Mangyan TribeTagabawaTalaandigTalaandig/ManaboTalaandig/ ManoboTausogTausugTboliTboli/ MuslimTboli/MuslimTidurayTiguianTigwanahonTuwaliTuwali &amp; AyanganUmayamnon- BulonayYatuka')]</value>
      <webElementGuid>0f45a444-23a8-4f47-8d4e-a11f830222ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
