<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - ARMM8 - Il_f2aada</name>
   <tag></tag>
   <elementGuidId>1e4d289f-db43-4cb4-a94c-fe6dc9206004</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboAnswerList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboAnswerList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d5682c71-a4b4-4541-b8f9-9efc5d3465bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>5e160b6d-4b7d-4938-8456-2b896fcf9b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboAnswerList</value>
      <webElementGuid>3e2c5868-c1da-47ab-9f89-0b0bcb34ef22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - ARMM[8] - Ilocos[8] - Cagayan Valley[6] - Central Luzon[9] - Calabarzon[8] - MIMAROPA[5] - Western Mindanao[4] - Bicol[8] - Western Visayas[4] - Central Visayas[2] - Eastern Visayas[0] - Northern Mindanao[6] - Southern Mindanao[2] - Central Mindanao[12] - NCR[7] - CAR[0] - CARAGA</value>
      <webElementGuid>971ac09a-dd59-43fa-bfa0-aae0faf22bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboAnswerList&quot;)</value>
      <webElementGuid>951e5b4f-ac2f-495c-a1b6-a973da1b1c49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboAnswerList']</value>
      <webElementGuid>4fd2d183-d0b8-4267-a048-204c72fbcdf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBody']/tr/td[2]/select</value>
      <webElementGuid>572004ca-9adb-4eda-90f5-c048dbbc5b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puntos'])[2]/following::select[1]</value>
      <webElementGuid>5800f871-abab-4b3a-b3a9-69ab5a6ebe30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mga Indikasyon/Indicators'])[2]/following::select[1]</value>
      <webElementGuid>d472eaf3-6446-4b27-8218-e4de39c924b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Score:'])[1]/preceding::select[11]</value>
      <webElementGuid>5528f490-304c-4e49-af31-e77c0ce9180a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>9e69806f-6b65-4fd3-bca0-e3a4ffb776dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboAnswerList' and (text() = '--      Select      --[0] - ARMM[8] - Ilocos[8] - Cagayan Valley[6] - Central Luzon[9] - Calabarzon[8] - MIMAROPA[5] - Western Mindanao[4] - Bicol[8] - Western Visayas[4] - Central Visayas[2] - Eastern Visayas[0] - Northern Mindanao[6] - Southern Mindanao[2] - Central Mindanao[12] - NCR[7] - CAR[0] - CARAGA' or . = '--      Select      --[0] - ARMM[8] - Ilocos[8] - Cagayan Valley[6] - Central Luzon[9] - Calabarzon[8] - MIMAROPA[5] - Western Mindanao[4] - Bicol[8] - Western Visayas[4] - Central Visayas[2] - Eastern Visayas[0] - Northern Mindanao[6] - Southern Mindanao[2] - Central Mindanao[12] - NCR[7] - CAR[0] - CARAGA')]</value>
      <webElementGuid>00c30ec7-1216-43f7-8836-6dccf7d672b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
