<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_txtBeneficiaryBday1</name>
   <tag></tag>
   <elementGuidId>7d3f1bde-b3bd-4f66-aa82-67265bba0b14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtBeneficiaryBday1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtBeneficiaryBday1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fbbc431-8c16-4985-8e74-53b45e7720f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7a694569-7040-4076-b29d-d056f82bbe34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>86d7429a-8a16-48e0-934c-a464f6633cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>LegalDependentAge(1)</value>
      <webElementGuid>afb3c072-15d0-4d71-a7af-66ba1bcff6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2999-12-12</value>
      <webElementGuid>5740cdca-0cc9-4ee8-b4fd-d56a95115a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required text-uppercase gb-border-fcs font-9</value>
      <webElementGuid>f4b38f8a-9be0-4bf7-86b9-1b4aa1e97000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ad779a95-57ba-4a41-8054-08fee2020dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtBeneficiaryBday1</value>
      <webElementGuid>f64ab833-6610-46f8-9f52-cbbca142de98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtBeneficiaryBday1&quot;)</value>
      <webElementGuid>1a0775cc-fc40-423f-a7b8-885722e78c79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtBeneficiaryBday1']</value>
      <webElementGuid>af79f45a-ee2d-4621-907f-62e26ec12172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row1']/div/div[2]/div/div/input</value>
      <webElementGuid>b6069aed-7911-478c-9bb5-9cc43f781d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>4d555b90-ea6f-4d5e-8740-4c42c3c01067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'txtBeneficiaryBday1']</value>
      <webElementGuid>4e7c623b-7a47-48b0-972e-3485fc4c3ed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
