<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select      0030</name>
   <tag></tag>
   <elementGuidId>b7bfdb7b-db64-4a59-b7eb-ed0edac2afe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbofifthRiskAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbofifthRiskAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>464dd23c-70b3-48cb-b915-f5b17eefbc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center gb-border-fcs Ans5</value>
      <webElementGuid>d1a8cf07-1af7-45a5-8434-810425762c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbofifthRiskAnswer</value>
      <webElementGuid>bf81f154-373a-4865-beba-ee70685357a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Select      0030</value>
      <webElementGuid>95635d97-c432-46f4-b986-9bb1579baab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbofifthRiskAnswer&quot;)</value>
      <webElementGuid>eb07106c-d088-4257-b1e3-bbffd581b867</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbofifthRiskAnswer']</value>
      <webElementGuid>73261383-62ad-46eb-9a0e-16b71f09c15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblRiskclassFifthBody']/tr/td[9]/select</value>
      <webElementGuid>52a1f60e-a1c8-463e-8b93-24980464626a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Listed'])[1]/following::select[1]</value>
      <webElementGuid>26bc0073-344f-473d-98f5-f12db285ab5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Listed'])[2]/following::select[1]</value>
      <webElementGuid>8cb7c176-6cc8-45c8-ba9c-de306f87672c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Activities'])[1]/preceding::select[1]</value>
      <webElementGuid>698ef97b-f607-4f72-9237-f8a067bccdf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self-Employed'])[1]/preceding::select[1]</value>
      <webElementGuid>207d8e4c-1670-40b5-b534-57c4d6018d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[5]/tr/td[9]/select</value>
      <webElementGuid>8ac2c817-a02c-40cb-addb-2763312a1fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbofifthRiskAnswer' and (text() = '     Select      0030' or . = '     Select      0030')]</value>
      <webElementGuid>91c46e3c-4dde-4ed4-b60b-f9066903a4d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
