<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select      01020</name>
   <tag></tag>
   <elementGuidId>cf039a5c-6d22-4d30-b234-37726f887bf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbofourthRiskAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbofourthRiskAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ba3c8068-a651-49f0-a9d8-81d768cca502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center gb-border-fcs Ans4</value>
      <webElementGuid>4f791dce-5263-4cfa-8f19-374f06361a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbofourthRiskAnswer</value>
      <webElementGuid>d517bd4e-2972-40dd-8c88-c4f12edb7280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Select      01020</value>
      <webElementGuid>c58e3be4-09b0-40bd-b41a-aa588c552522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbofourthRiskAnswer&quot;)</value>
      <webElementGuid>b6c70a48-d081-452a-92fa-7b0480a9d32d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbofourthRiskAnswer']</value>
      <webElementGuid>1d9c3be6-89bf-431f-a2fc-1d81a9d57489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblRiskclassFourthBody']/tr/td[9]/select</value>
      <webElementGuid>6ae751d1-582e-4e10-b38f-1ffb26dba383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[5]/following::select[1]</value>
      <webElementGuid>b07690fd-7a62-4f3a-b2c0-3c758eb236d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='With Materially Link Accounts'])[1]/following::select[1]</value>
      <webElementGuid>960a34aa-b89d-4e74-b5f2-7fc2c68c5553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Included in Watchlist, Engaged in illegal activities'])[1]/preceding::select[1]</value>
      <webElementGuid>25adcb3e-3a22-4e29-bb10-bb8497b05a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Listed'])[1]/preceding::select[1]</value>
      <webElementGuid>e64997c9-e7d0-407a-bc3e-fba5092e5d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[4]/tr/td[9]/select</value>
      <webElementGuid>fe427f39-9f88-49d4-98b5-2778739eb601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbofourthRiskAnswer' and (text() = '     Select      01020' or . = '     Select      01020')]</value>
      <webElementGuid>43abc5d8-8190-44dc-8308-934bff6b3eed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
