<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_January 31, 2024 - 092106AM_rounded-circle</name>
   <tag></tag>
   <elementGuidId>d569a9c1-205b-48dc-a6e5-1a2cf8118a49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div/div/div/ul/li[5]/a/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.account-user-avatar > img.rounded-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0e00de08-5a89-4e14-9c78-1e08193bd7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Resources/assets/images/users/avatar-1.jpg</value>
      <webElementGuid>7515c722-06eb-42d3-a27b-b0bd9d436a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>user-image</value>
      <webElementGuid>ae609fce-348d-4a4b-9009-558d354340bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>c0b53d26-38ea-4159-89a0-90ccd7d0e8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle</value>
      <webElementGuid>247e111e-8407-4966-b183-177684c1194d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;wrapper show&quot;]/div[@class=&quot;navbar-custom&quot;]/div[@class=&quot;topbar container-fluid&quot;]/ul[@class=&quot;topbar-menu d-flex align-items-center gap-3&quot;]/li[@class=&quot;dropdown&quot;]/a[@class=&quot;nav-link dropdown-toggle arrow-none nav-user px-2 show&quot;]/span[@class=&quot;account-user-avatar&quot;]/img[@class=&quot;rounded-circle&quot;]</value>
      <webElementGuid>2eea7b3e-416e-4bda-80ea-3510c0695acd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div/div/ul/li[5]/a/span/img</value>
      <webElementGuid>7514746a-a64f-4f87-a98e-8573c164ba8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='user-image']</value>
      <webElementGuid>b905d84d-959f-4329-970a-b837a97713cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span/img</value>
      <webElementGuid>94a3a52e-6189-4e8a-bc0c-8fda221b166f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../Resources/assets/images/users/avatar-1.jpg' and @alt = 'user-image']</value>
      <webElementGuid>3b375306-f9b5-4195-9327-e258bb54851d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
