<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ClientCreation</name>
   <tag></tag>
   <elementGuidId>ab5435d5-2cde-4c83-9c58-b3c699779f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomerPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CustomerPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed4a2709-3c0d-43db-af5f-e3b26905dd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb-hover-side confirmation-link</value>
      <webElementGuid>89fd0331-ccb0-4cef-9b9f-0a6335f93bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>CustomerValidation</value>
      <webElementGuid>702882a2-26a3-4f23-8688-37ac8f54ae16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerPage</value>
      <webElementGuid>04714d76-58a9-4c4a-ab33-207ae46dae36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return loadIframe('ifrm1', this.href);</value>
      <webElementGuid>12ef8d3d-f1be-4d94-ae8f-e931b992628b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Client
									Creation</value>
      <webElementGuid>1d9c2f8d-e948-435e-b28c-652e7b5574f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomerPage&quot;)</value>
      <webElementGuid>d53d3cc6-60da-4f7d-ba39-884966d11593</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CustomerPage']</value>
      <webElementGuid>083206a2-1661-4d2f-ba5c-f3e4a9cd9f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarCustomer']/ul/li[2]/a</value>
      <webElementGuid>b2d4aa27-3b46-4741-9180-600026f63cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Client
									Creation')]</value>
      <webElementGuid>8eaa1231-b50f-43b4-aa34-03e155d777c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/following::a[2]</value>
      <webElementGuid>fdf4c921-2581-4918-b659-8c00f653a02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'CustomerValidation')]</value>
      <webElementGuid>703def0c-b3c7-4349-978e-f1cc14ae34fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li[2]/a</value>
      <webElementGuid>aeea8d29-f097-4af3-bedd-7a0077280774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'CustomerValidation' and @id = 'CustomerPage' and (text() = 'Client
									Creation' or . = 'Client
									Creation')]</value>
      <webElementGuid>d0c0d094-dc3f-43d3-b0db-921d29f5efdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
