<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PAGSANG-AYON ATPAGTALIKOD (CONSENT AN_49f71e</name>
   <tag></tag>
   <elementGuidId>abb410f8-603d-4d54-8f72-d50f574d9851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtiAgree</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtiAgree']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a656457-6b93-47b0-b61d-8928abda52a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e3068bfc-2d0c-4824-a072-4b82358f0f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input </value>
      <webElementGuid>38c49565-0f12-4ba9-9021-cb7d43afd954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5bd84d5b-dd44-4e5a-9f9f-19f6aed543f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtiAgree</value>
      <webElementGuid>2d0dd302-cdb9-4c46-a17d-09dd912cecdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtiAgree&quot;)</value>
      <webElementGuid>d74aaa31-ac26-4c1b-9552-a2bc7b90b49b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtiAgree']</value>
      <webElementGuid>770aaf35-2551-48bb-8c22-aa193f70f0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='9']/div/div/div[4]/div/div[2]/div/div/div/div[3]/div/input</value>
      <webElementGuid>ebbe123b-5313-4bdb-aaf2-eac0739523fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/input</value>
      <webElementGuid>1aa0cf28-39bb-458d-9196-1fc55cc9716f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'txtiAgree']</value>
      <webElementGuid>c7517e7f-c0f6-4a8b-a7ff-d283335f4d04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
