<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YES_CARDScholar</name>
   <tag></tag>
   <elementGuidId>42c556d6-4804-46a1-bccd-e4e33e2f92c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCARDScholarNO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCARDScholarNO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99a2a862-2695-4efa-842f-ad61b1c7d61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c7467a1a-799e-4f27-b041-3d18b4ac9ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs </value>
      <webElementGuid>4a9a024f-2508-4ad3-b247-a99eaca71bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>df6c5ef3-36da-4948-ae76-010c3f6c4e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCARDScholarNO</value>
      <webElementGuid>2da94c0e-36c0-47c5-b29b-1d9e14faf8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CARDScholar</value>
      <webElementGuid>c734dea0-dc90-428c-bbb0-8add993c2549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCARDScholarNO&quot;)</value>
      <webElementGuid>e491c553-7b87-46c9-9f3f-dd806788528c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCARDScholarNO']</value>
      <webElementGuid>54a4caba-726f-43c1-b03b-d66e4a48a7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[21]/div[2]/input</value>
      <webElementGuid>01341860-a1a3-45b8-8e1c-f19b61c76747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div[2]/input</value>
      <webElementGuid>7812a61b-4a4b-4f45-9de0-a635b9779799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'txtCARDScholarNO' and @name = 'CARDScholar']</value>
      <webElementGuid>05e5a42d-4bf6-4bbe-8e16-263cae09e12c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
