<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Area</name>
   <tag></tag>
   <elementGuidId>c8f37629-1e36-4b0c-93cd-f78e9f207bd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCustomerBranch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCustomerBranch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>56f0fde5-9ac9-4386-9a5a-14ff06ed110c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCustomerBranch</value>
      <webElementGuid>4df23856-9daa-47d5-93f5-cf8fed171230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>467425fa-9420-453f-87ea-07158b10556e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>375d99ba-de50-4241-b814-28bf1bf76667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --Batangas 1BukidCandelaria 1Cavite 1Cavite 2Ilocos 1Ilocos 3Laguna 1Laguna 2Laguna 3Ncr 1Ncr 1 TestTarlac AreaTest Area JmmTest Area Jmm</value>
      <webElementGuid>030060c0-3a70-4b63-857e-86b018506069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCustomerBranch&quot;)</value>
      <webElementGuid>3aa2f0a7-78c2-49d4-942e-5755c5790adf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCustomerBranch']</value>
      <webElementGuid>52f1d0b9-fabe-488d-ad3e-e5415a7081f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[18]/div/div/select</value>
      <webElementGuid>1b4b4b61-895a-464a-a18a-96bbaa6de27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/select</value>
      <webElementGuid>13a37775-b2d3-44bb-a66c-499f46ad2737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCustomerBranch' and (text() = '-- Select --Batangas 1BukidCandelaria 1Cavite 1Cavite 2Ilocos 1Ilocos 3Laguna 1Laguna 2Laguna 3Ncr 1Ncr 1 TestTarlac AreaTest Area JmmTest Area Jmm' or . = '-- Select --Batangas 1BukidCandelaria 1Cavite 1Cavite 2Ilocos 1Ilocos 3Laguna 1Laguna 2Laguna 3Ncr 1Ncr 1 TestTarlac AreaTest Area JmmTest Area Jmm')]</value>
      <webElementGuid>39d8038c-5cc7-461e-a4df-9d23a23c8bc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
