<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Unit</name>
   <tag></tag>
   <elementGuidId>5ee816fd-c4fb-4c17-affd-db2b7ea921b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCustomerUnit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCustomerUnit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>81f27372-b9f2-4d2d-95e2-f8ff5eed9e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCustomerUnit</value>
      <webElementGuid>58b9e36e-116f-45c6-a00c-5688d6de901d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>66d16376-0ebb-4c40-acd6-ac1ff85d6259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>c044d368-d752-4101-ad8a-717dd317d4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--PAETE (REGULAR)Sampalok 1PAGSANJAN (REGULAR)TANAYSAN PABLOPILA (REGULAR)MAGDALENA (REGULAR)STA. MARIA (REGULAR)</value>
      <webElementGuid>585c2379-4f1c-4f82-ac39-16d3a1e7c8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCustomerUnit&quot;)</value>
      <webElementGuid>72b97c40-8bc9-46bc-832f-b2be3d14ee4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCustomerUnit']</value>
      <webElementGuid>556f3e7b-4982-43ea-9b2c-f93d2e00a194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[19]/div/div/select</value>
      <webElementGuid>96b9dd6a-9ab3-4280-a826-6195ef29fa72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARD Scholar :'])[1]/preceding::select[2]</value>
      <webElementGuid>557ab3f5-40d6-4764-941f-83da7e891598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/select</value>
      <webElementGuid>b2e5bfd9-b3b0-4f61-a972-74b10cca666f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCustomerUnit' and (text() = '--Select--PAETE (REGULAR)Sampalok 1PAGSANJAN (REGULAR)TANAYSAN PABLOPILA (REGULAR)MAGDALENA (REGULAR)STA. MARIA (REGULAR)' or . = '--Select--PAETE (REGULAR)Sampalok 1PAGSANJAN (REGULAR)TANAYSAN PABLOPILA (REGULAR)MAGDALENA (REGULAR)STA. MARIA (REGULAR)')]</value>
      <webElementGuid>02f25669-e559-42a1-b6b7-12c984d66881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
