<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Province</name>
   <tag></tag>
   <elementGuidId>a285dc24-d808-4480-812a-17006b34af72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBdayProvince']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboBdayProvince</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>564a67f0-db18-4a6a-881d-57e8b114db16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBdayProvince</value>
      <webElementGuid>8f6ca6a7-911b-4e68-905b-beb85cf43a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>cb178ee3-20b1-4da5-8ffc-393c8cb8542c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>b0f45a56-447d-45d4-be52-5dba00048fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)</value>
      <webElementGuid>0da3f82e-4c20-4497-b34c-ce6f40e16ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBdayProvince&quot;)</value>
      <webElementGuid>8025dd32-d97d-4a9e-a064-26d20694fe9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBdayProvince']</value>
      <webElementGuid>22c95875-62f0-43dc-9543-cda93e69c113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[8]/div/div/select</value>
      <webElementGuid>c00e031b-3fce-4915-9e4d-9a7741f4571f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/select</value>
      <webElementGuid>8b306d36-e906-4d0c-a8d7-134233d5efd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBdayProvince' and (text() = '--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)' or . = '--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)')]</value>
      <webElementGuid>a3aba602-fe5a-4460-b5cd-9316ea66b593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
