<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--DSHPRegular Client</name>
   <tag></tag>
   <elementGuidId>0963997b-31b6-47e7-810e-d3ef03778f97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboSubClassification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSubClassification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bbdf2c6c-b292-426c-be23-b0d1f3cb5b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSubClassification</value>
      <webElementGuid>15cb8936-d7bf-42cc-8ed5-824d4c47d14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>membershipClassification();</value>
      <webElementGuid>e5617cdc-094f-43a8-b95c-441eac6d2da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs select2 font-11</value>
      <webElementGuid>57da5221-ffbe-40a9-a140-1487b5aebd1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>033e8bed-62a2-4dbb-b2ed-2369bbd91f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--DSHPRegular Client</value>
      <webElementGuid>0813913e-9308-4812-95d3-b82b257bcd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSubClassification&quot;)</value>
      <webElementGuid>6a98bc89-d2e3-4093-ac81-b67b0c0c9380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSubClassification']</value>
      <webElementGuid>16385de6-ad89-49b5-97d8-8a81b027ac27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8']/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>8b722e6b-2a83-47f5-ab6c-50a80cd123fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puntos'])[2]/following::select[11]</value>
      <webElementGuid>7016bb92-005d-443d-bcd5-744ce3880230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Score:'])[1]/preceding::select[1]</value>
      <webElementGuid>004216ab-6b44-43fa-aac5-790a3e832e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health Declaration'])[1]/preceding::select[3]</value>
      <webElementGuid>fc316cff-ceff-4978-97c7-fd9241ac665b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>25d0f5ad-c526-4e89-ba06-100b49525d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSubClassification' and (text() = '--Select--DSHPRegular Client' or . = '--Select--DSHPRegular Client')]</value>
      <webElementGuid>97e1b58e-40fe-4715-a84b-f925c4815d42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
