<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Wala7 - Oo</name>
   <tag></tag>
   <elementGuidId>e7066295-78c3-407b-aad1-5e95452b3bc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbosixthQAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbosixthQAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2d9d022b-9af2-454f-b8ba-5528d20b97fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>867f2bb1-1586-4abe-bbb0-16b9eaf70cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbosixthQAnswer</value>
      <webElementGuid>f3f311d7-b2e7-4273-b5c0-30daca1fdc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Wala[7] - Oo</value>
      <webElementGuid>397655d8-568f-46c7-b578-933ddb577312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbosixthQAnswer&quot;)</value>
      <webElementGuid>37da11c5-b7d0-4872-afb8-466b8b142fd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbosixthQAnswer']</value>
      <webElementGuid>964d6adf-0051-4d02-9085-cb5d95acee35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodySixth']/tr/td[2]/select</value>
      <webElementGuid>d20c160e-2414-4abf-935f-4a8cfd8b1773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puntos'])[2]/following::select[6]</value>
      <webElementGuid>60a8e993-91fa-4447-873b-087fe2bbc959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mga Indikasyon/Indicators'])[2]/following::select[6]</value>
      <webElementGuid>0f8bda13-5978-40e3-983d-7aa9a796bd81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Score:'])[1]/preceding::select[6]</value>
      <webElementGuid>828f6d93-3acd-43fa-a644-0c0f69c08cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[6]/tr/td[2]/select</value>
      <webElementGuid>0c9a3f0a-7d73-49d1-aec0-ecc73e06c982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbosixthQAnswer' and (text() = '--      Select      --[0] - Wala[7] - Oo' or . = '--      Select      --[0] - Wala[7] - Oo')]</value>
      <webElementGuid>1b4bd355-cf95-46fc-8f87-e23a83818eb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
