<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --0 - Hindi8 - Oo</name>
   <tag></tag>
   <elementGuidId>4dc6c6a6-bcb5-4884-aaac-438f0c25320d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbotenthQAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cbotenthQAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d977ecc9-9d01-4f2a-9212-b208b7493ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validatelenght required gb-border-fcs form-control Ans</value>
      <webElementGuid>7c966b9d-6a5d-42d5-b2a5-dc43f788d2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbotenthQAnswer</value>
      <webElementGuid>52ce1cd1-8214-4557-a9fb-929b58f9bf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Hindi[8] - Oo</value>
      <webElementGuid>c6417fce-d1b5-4226-a98a-30e7241aaa8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbotenthQAnswer&quot;)</value>
      <webElementGuid>c9a68b59-e67d-4fc3-8c70-5fe5d9688c7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cbotenthQAnswer']</value>
      <webElementGuid>9cf8dd52-0f00-4b90-8369-a52b34f73f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodyTenth']/tr/td[2]/select</value>
      <webElementGuid>1fcf6052-1242-43e3-91b2-35fd0abc40ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puntos'])[2]/following::select[10]</value>
      <webElementGuid>64ce8b67-b08a-4362-a3f8-8c521523cdaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mga Indikasyon/Indicators'])[2]/following::select[10]</value>
      <webElementGuid>3876d010-1775-471c-8358-a9a0dfa480ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Score:'])[1]/preceding::select[2]</value>
      <webElementGuid>75042a8a-cad5-4b80-bec8-f0fa9811857a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[10]/tr/td[2]/select</value>
      <webElementGuid>1ef3c5a0-ad6c-46af-8a59-67c8394285c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cbotenthQAnswer' and (text() = '--      Select      --[0] - Hindi[8] - Oo' or . = '--      Select      --[0] - Hindi[8] - Oo')]</value>
      <webElementGuid>dfeadfd9-a9fa-4d8f-848c-8d0c2747e3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
