<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YES_withdisability</name>
   <tag></tag>
   <elementGuidId>f27bac8f-9621-4de1-94b8-e11606494cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nodisability']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nodisability</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>388f0952-eafe-46f5-bb89-1afdecf3190d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c30234da-23ad-4c19-968d-aab38954571a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs</value>
      <webElementGuid>c060a75a-b1c4-4ee3-9ecd-fc1045992366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9140f698-fc11-412d-b7c1-1b062b2b843b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>disability();</value>
      <webElementGuid>cbc6c128-d9fa-49ba-aa0d-4775e71449f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nodisability</value>
      <webElementGuid>2b69f677-5ac5-4b8a-a83a-03968d830641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>withdisability</value>
      <webElementGuid>f5402427-ec5d-46c4-a1bf-5d00ba50d30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nodisability&quot;)</value>
      <webElementGuid>328bdcc9-1380-4697-a44c-81b41b2ff48a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nodisability']</value>
      <webElementGuid>1daa9afb-c433-454a-b3b0-1ce7d8efdc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>fd0a354a-f560-49f9-bca3-b98e4aafffd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>ddaa536f-e04f-4585-a2ec-9da0609130ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'nodisability' and @name = 'withdisability']</value>
      <webElementGuid>d1562649-2674-40e9-9f7d-8d4d1282cef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
