<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YES_drone3</name>
   <tag></tag>
   <elementGuidId>6f56fd5b-c5bd-4421-a9c2-4660f5802b68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSpouseTypeNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSpouseTypeNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0197f99b-4e48-4d22-9c77-72a9a81af292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7af850a1-c2a5-4546-941a-e7ea10c7ebed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs</value>
      <webElementGuid>3122c35c-05b6-43e9-b69c-4b82b2db9705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>111c0766-fc52-4218-80fb-0fc924a43723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>SpouseType();</value>
      <webElementGuid>ca1c5032-0341-4953-bf5c-5d3cd25d552e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>756e7b19-a77e-4c5f-9006-06afa54624e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSpouseTypeNo</value>
      <webElementGuid>3d9cc8d2-b1ec-4efb-bdc2-2503ebdf80e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>drone3</value>
      <webElementGuid>75903a8f-8898-4e30-9f1b-9e4d057d88b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSpouseTypeNo&quot;)</value>
      <webElementGuid>2920d8a9-8f07-4764-a442-c31cc16558b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSpouseTypeNo']</value>
      <webElementGuid>f5178386-ee8c-48b7-8edc-4358aca5e2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5']/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>11fcf01a-a0f7-42e9-8666-11c91549eb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>0ddc3126-c7b4-4015-8916-15bd4a565147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'txtSpouseTypeNo' and @name = 'drone3']</value>
      <webElementGuid>836b1cfb-9a50-4f9c-8683-c213653dba51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
