<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--FemaleMale</name>
   <tag></tag>
   <elementGuidId>d9c243bd-bc34-4f71-8530-f525990c785f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboSpouseGender</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSpouseGender']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f18d52ba-1102-4718-9489-2b9142f643d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSpouseGender</value>
      <webElementGuid>3c13c583-b52c-4dab-8278-7fe755910555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2998749e-daf5-4ef0-84f0-a635f816e3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>d48ee799-6da3-4565-86d2-a5fb386f6a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--FemaleMale</value>
      <webElementGuid>9dd41a7f-7134-4ae0-b073-a2a458402f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSpouseGender&quot;)</value>
      <webElementGuid>69c00ef9-f8d4-44a5-874a-1788a511765b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSpouseGender']</value>
      <webElementGuid>b1c68b3a-3c41-4372-a592-58aa665e681b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5']/div/div/div[2]/div/div/div[7]/div/div/select</value>
      <webElementGuid>160ad5d8-1b0c-42f8-9ce8-e4a996b38a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[7]/div/div/select</value>
      <webElementGuid>6622b83b-54af-4273-afcc-01604ca282a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSpouseGender' and (text() = '--Select--FemaleMale' or . = '--Select--FemaleMale')]</value>
      <webElementGuid>bc407544-ff00-47cf-bce7-c85a5eda337c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
