<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--EmploymentSalariesIncome f_b99596</name>
   <tag></tag>
   <elementGuidId>99ddf504-7f9c-42e1-805a-27806932302f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboSourceOfIncome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSourceOfIncome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>118a767f-ecd2-4f5e-9e2b-cfde4c7176b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSourceOfIncome</value>
      <webElementGuid>7faa0ee0-d84a-47df-bf9c-562cc7d922f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c3c593d5-5db0-4bbd-a66b-6fb59fd0d12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checksourceOfFund();</value>
      <webElementGuid>e047c149-0c7f-423b-8007-c93da48c5f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>fe726fbf-56db-4ec8-80a3-9edc3e1f243a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension</value>
      <webElementGuid>d55d3a14-a52a-49f4-b509-59b302ee72ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSourceOfIncome&quot;)</value>
      <webElementGuid>fe2f8a5f-ab9d-4eec-aeae-eb16eeff9ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSourceOfIncome']</value>
      <webElementGuid>fa8f4936-867b-4480-a598-f7cdb09be3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5']/div/div/div[2]/div[2]/div/div[4]/div/div/select</value>
      <webElementGuid>9afcf9d8-f57e-4832-9a82-0d64dcdd1996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[4]/div/div/select</value>
      <webElementGuid>e131e667-bea1-441f-b5a8-8c9c29d0534c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSourceOfIncome' and (text() = '--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension' or . = '--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension')]</value>
      <webElementGuid>5313a356-aa45-4317-b02b-71f4815d2661</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
