<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BeneficiaryLegal Dependent_a71cea_1_2</name>
   <tag></tag>
   <elementGuidId>78ee8be6-3ba2-444b-adb9-39f5c6b27132</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboRemarks3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboRemarks3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>baa116a5-3a5f-43fd-be3e-90f1e66a3a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboRemarks3</value>
      <webElementGuid>a0e758d3-ba2b-4e50-97c6-4eac77192e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ecc6d859-5a28-43be-be3c-72914a8d7171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>beneficiaryRemarks($('#txtBeneficiaryBday3').val(), $('#cboWithDisability3').val(),$('#cboRemarks3').val(),'#cboRemarks3');</value>
      <webElementGuid>9f03b5a8-6c4a-4b33-a795-d0e0d2bd91d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>76204b4d-1ab6-4b7f-938f-84e6c690b3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary</value>
      <webElementGuid>0d02d4e1-08a8-41b7-84a2-37020294a4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboRemarks3&quot;)</value>
      <webElementGuid>d07be335-57c6-46a2-a3c0-c7db18eef367</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboRemarks3']</value>
      <webElementGuid>8847e9e7-3926-46ba-b5a5-44469c9073c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row3']/div/div[10]/div/div/select</value>
      <webElementGuid>9d3f8744-9455-49f6-9895-d7cb3367463f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[21]</value>
      <webElementGuid>57989a5c-aff2-411d-81bf-01f982dfeb50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[1]</value>
      <webElementGuid>05a65be2-f64a-4e31-a1fc-edcdf601ac4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[1]</value>
      <webElementGuid>e0cf21e3-8eb7-4285-bcac-c82bf360b275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[10]/div/div/select</value>
      <webElementGuid>ca0e6313-917e-441d-b7ca-9c4a8cc72d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboRemarks3' and (text() = '--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary' or . = '--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary')]</value>
      <webElementGuid>4a3c7f5b-c835-40de-8906-72218fc75de2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
