<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BrotherBrother-in-LawCousi_e1fca2_1_2</name>
   <tag></tag>
   <elementGuidId>13324d0f-486a-457b-8c1d-2888931f2074</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboBenRelType3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBenRelType3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cd2b99c1-c71f-42a1-b280-ee1ee323063b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBenRelType3</value>
      <webElementGuid>79e9c547-a0c4-451e-a640-c3deabf4b31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2f1df7f3-da17-4286-87b8-6e28610b50aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>eb6a8cea-f506-4b93-b10e-69c69a564d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse</value>
      <webElementGuid>0225ac7a-b571-4ba4-b18d-4c6b65bb232d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBenRelType3&quot;)</value>
      <webElementGuid>578fa5c5-a2e4-404b-a597-a2e1ee4ef625</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBenRelType3']</value>
      <webElementGuid>56e863d7-4679-429e-af4e-1f572a5c7028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row3']/div/div[3]/div/div/select</value>
      <webElementGuid>f302f17e-5319-48ba-91a8-ae793c422eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[15]</value>
      <webElementGuid>b716b2a1-98b0-47a1-ab15-fb1e0c1d086d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[7]</value>
      <webElementGuid>0e124b03-9c5b-42e0-845d-2095fc0dfe73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[7]</value>
      <webElementGuid>27797967-90f4-4529-b21c-e0cb4c2a6913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[3]/div/div/select</value>
      <webElementGuid>36acc3de-5deb-4d10-9c98-ed4575f12ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBenRelType3' and (text() = '--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse' or . = '--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse')]</value>
      <webElementGuid>4c53b618-9d7d-466d-9f86-779a68e28241</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
