<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--NAPrimarySecondary_1</name>
   <tag></tag>
   <elementGuidId>f04772e5-5a38-4223-a5a9-0cf0bfc8d7a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboBeneficiary3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBeneficiary3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d88f4b97-96a0-4f4c-af95-a78e8cbc381b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBeneficiary3</value>
      <webElementGuid>40a1b956-7ab8-4fe3-805b-731db07a5a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4a7df1a6-0457-49c1-abec-d2c8d88b5523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateBeneficiary(3)</value>
      <webElementGuid>19cc791a-e778-48bf-bc1b-35b906363af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>1faf71f1-697f-430d-87b7-6eaaaf70beae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--N/APrimarySecondary </value>
      <webElementGuid>0ef29064-cb8d-40eb-89fb-e7532f3a1a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBeneficiary3&quot;)</value>
      <webElementGuid>3f78b71b-5660-45b7-9c1e-837df62f01a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBeneficiary3']</value>
      <webElementGuid>22957b01-1154-45ab-a86e-cc1a2b12b008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row3']/div/div[6]/div/div/select</value>
      <webElementGuid>535e95bf-478f-454d-a06e-90cbd85fe67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[18]</value>
      <webElementGuid>e6a176a7-7263-4658-9033-de485a9e547c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[4]</value>
      <webElementGuid>30bfba68-9e5c-4efe-b36b-91b8aebc91f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[4]</value>
      <webElementGuid>87a31a4b-4e68-4abc-9659-09185b1ea059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[6]/div/div/select</value>
      <webElementGuid>a27a5aba-873c-4cbe-b93e-d9ff5f7f0aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBeneficiary3' and (text() = '--Select--N/APrimarySecondary ' or . = '--Select--N/APrimarySecondary ')]</value>
      <webElementGuid>ea21f52e-c9a9-4e15-ae17-c31856913284</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
