<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FirstName_txtfname</name>
   <tag></tag>
   <elementGuidId>f2c83df0-9205-4577-8160-adc257bc1608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtfname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d670f73-4535-4d80-a40a-4a9b420fc387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f1e3a2d9-335f-44a9-8489-c7a7699ded93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>804edf24-b2bf-45ac-8bba-37af3d0c0ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs text-capitalize font-11</value>
      <webElementGuid>56c372ca-166f-4e12-9d38-8506a13e1f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtfname</value>
      <webElementGuid>b9736df7-4626-4e4a-934c-b9c8d8d2c5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checkNames();</value>
      <webElementGuid>776fc50e-cd5b-4640-a1c9-de3c05ff63d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtfname&quot;)</value>
      <webElementGuid>4f8bca6f-b5a3-4730-a66a-1ad48b486b31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtfname']</value>
      <webElementGuid>f02d64a2-d9b1-43f0-8881-661037121505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[6]/div/input</value>
      <webElementGuid>adf44f70-17f3-4883-82f9-9e1def30d4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>baffa746-dc87-4a21-b3b8-61066d59e383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtfname']</value>
      <webElementGuid>8bfc5a15-8e19-431f-b2dd-f9c7037c711f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
