<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YES_FormerEmployee</name>
   <tag></tag>
   <elementGuidId>6756ab6c-f74c-4c50-be82-77d506d6f8b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFormerEmployeeNO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtFormerEmployeeNO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0108af37-1a81-41b0-a60a-7de2704b8560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e476c2ea-d93e-49a8-a0a7-ef2b63137240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs </value>
      <webElementGuid>ffd2386d-a665-4ddf-bc79-e454c09793c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>72eb51fd-8d06-4f87-a919-22d410157ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFormerEmployeeNO</value>
      <webElementGuid>7c20d99a-548c-4028-87e5-7d82ae496ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FormerEmployee</value>
      <webElementGuid>441f9a7c-024d-43ed-a1d6-a2640dc455a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFormerEmployeeNO&quot;)</value>
      <webElementGuid>c5e91c28-c2b8-43f8-8a46-a0ae15a5cbd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFormerEmployeeNO']</value>
      <webElementGuid>71dbf22b-6504-41af-9fcc-f1e1a4ffefb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[22]/div[2]/input</value>
      <webElementGuid>cf50df5b-755d-4c8e-86b1-0562fdbfe3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div[2]/input</value>
      <webElementGuid>adfaeef6-8b98-4ebc-8cef-0d4612c95870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'txtFormerEmployeeNO' and @name = 'FormerEmployee']</value>
      <webElementGuid>a2700db0-c6c4-4c45-a7e7-7865897856fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
