<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BusinessGovernment EmployeeOthersPrivate Emplovee</name>
   <tag></tag>
   <elementGuidId>266bd0b4-731e-4ae0-bbbb-ee503a8f1092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboOccupation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboOccupation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>28611438-4697-4163-9e8b-848610ba6f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboOccupation</value>
      <webElementGuid>743c756e-7636-4859-884d-3fde98ef6407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>f55704d3-dd25-43a5-9322-74215e523b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>4ce6d17c-499e-4233-b617-dc399b2acd97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BusinessGovernment EmployeeOthersPrivate Emplovee</value>
      <webElementGuid>8657275c-313f-45e4-9e01-77e22f568338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboOccupation&quot;)</value>
      <webElementGuid>5f959f0b-4557-4ff4-a900-86f9ac850e31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboOccupation']</value>
      <webElementGuid>c87e1e76-31f3-4ba7-a348-8ffc2de4455d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[2]/div/div/select</value>
      <webElementGuid>390c831e-1e1f-4771-badd-c8d8d9b6cbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>08a1ed56-ce39-4a2c-896f-1ce93c728a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboOccupation' and (text() = '--Select--BusinessGovernment EmployeeOthersPrivate Emplovee' or . = '--Select--BusinessGovernment EmployeeOthersPrivate Emplovee')]</value>
      <webElementGuid>4efce7b7-2b0e-4552-bc4d-aa05d95083a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
