<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_EducationalAttainment</name>
   <tag></tag>
   <elementGuidId>4ea90f6d-7b8e-4a6a-9dca-1342ba1122f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboEducationalLevel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboEducationalLevel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aaac6038-11e2-4682-8ad9-1919dd5a9444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboEducationalLevel</value>
      <webElementGuid>c7c1a304-6ea5-4ad7-ad5e-b57096f220ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>654838a5-7542-464a-a80c-1cd6ee94a9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>1bfe1758-bb5d-4e00-a871-589b327ba501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster's DegreeDoctorate Degree</value>
      <webElementGuid>873027e1-0caa-455c-b12c-3c88387fb76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboEducationalLevel&quot;)</value>
      <webElementGuid>90c32228-aa9e-43d4-94db-ec337325da03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboEducationalLevel']</value>
      <webElementGuid>e88f6260-b795-4ade-bdf8-0f1f03d06b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>9a32c5f1-840b-4c83-ac00-f543bc070a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>fb704be9-3c99-41c2-bb0b-e19a96a7baf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboEducationalLevel' and (text() = concat(&quot;--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster&quot; , &quot;'&quot; , &quot;s DegreeDoctorate Degree&quot;) or . = concat(&quot;--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster&quot; , &quot;'&quot; , &quot;s DegreeDoctorate Degree&quot;))]</value>
      <webElementGuid>a7f7800d-6055-4de6-9255-00eb9938fc69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
