<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Religion</name>
   <tag></tag>
   <elementGuidId>ef9b9f0b-7a29-4c8e-8b55-07a2d3b92304</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboReligion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboReligion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f331b05a-c0af-46cd-8150-f3690ca1b10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboReligion</value>
      <webElementGuid>59468c5d-4d6a-4bee-98e1-26e04d87b25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>6a868e09-9a2c-40c5-acf1-a5c932042fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>7f848ce1-aed7-4549-a227-d679334b9a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AglipayanBorn AgainEvangelicalIglesia ni KristoIslamJehova's WitnessOthersProtestantRoman CatholicSeventh-day Adventist</value>
      <webElementGuid>9def3d60-3281-45d8-b192-9aef0c5f0bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboReligion&quot;)</value>
      <webElementGuid>07c2b364-edef-4790-9be6-3aa7b1110c4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboReligion']</value>
      <webElementGuid>c5b989f6-1226-4d5a-a886-af1e0ba6c90b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[21]/div/div/select</value>
      <webElementGuid>7d0b515b-7bec-4d2e-a8ab-5df1ff79d5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div/select</value>
      <webElementGuid>e48e844d-13bf-45be-b281-b6110ee002fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboReligion' and (text() = concat(&quot;--Select--AglipayanBorn AgainEvangelicalIglesia ni KristoIslamJehova&quot; , &quot;'&quot; , &quot;s WitnessOthersProtestantRoman CatholicSeventh-day Adventist&quot;) or . = concat(&quot;--Select--AglipayanBorn AgainEvangelicalIglesia ni KristoIslamJehova&quot; , &quot;'&quot; , &quot;s WitnessOthersProtestantRoman CatholicSeventh-day Adventist&quot;))]</value>
      <webElementGuid>bcfd3c39-9fcd-49cc-be02-61abfc0bb8fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
