<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YES_drone3</name>
   <tag></tag>
   <elementGuidId>34842576-7714-4902-a1d1-9094e1012253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSpouseTypeNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSpouseTypeNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0bdc769-c431-42c7-b24f-07f7a266b769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>17568aa5-708c-4104-8de4-7717f04dc28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs</value>
      <webElementGuid>fcb6e405-5ac7-4c4e-af2e-27945af25447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f06d0bfd-70ff-4903-bf8c-cdd0df50f990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>SpouseType();</value>
      <webElementGuid>6c24899e-a3fa-4820-9df1-d0e319cb4cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0534023f-3b1d-45af-a1ee-83d72dfe56c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSpouseTypeNo</value>
      <webElementGuid>417bc345-5371-49b7-9df3-17ec91590d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>drone3</value>
      <webElementGuid>919917ea-db9e-4787-85a4-fdb43881a737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSpouseTypeNo&quot;)</value>
      <webElementGuid>e4748675-3a0d-4185-ad8f-5446f1e4a567</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSpouseTypeNo']</value>
      <webElementGuid>5f04082a-8d3f-41e5-946a-884a9b217c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5']/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>1c032223-dccb-4374-8cb1-71604745e648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>4df3fd07-a4e6-42fc-87e9-a1f2c8041a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'txtSpouseTypeNo' and @name = 'drone3']</value>
      <webElementGuid>598711dd-8aa6-4330-812d-be71654c8b6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
