<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--YESNO</name>
   <tag></tag>
   <elementGuidId>f7e94ee6-157f-4dca-a5d7-500f94c653d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboCardMRIScho2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCardMRIScho2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>69ea0faf-6c75-49d9-be3b-b11021dff77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCardMRIScho2</value>
      <webElementGuid>b062e220-4d78-4a57-8c03-5315659e96c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fc266544-f1e0-4647-9585-ea4351e11f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>301fe602-f3b0-4d83-8625-0118ecc56027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					--Select--
					YES
					NO
				</value>
      <webElementGuid>88001004-f793-4044-9759-8a3f108d96e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCardMRIScho2&quot;)</value>
      <webElementGuid>4a68e5a2-c9c5-4095-b7fe-44ff20a27723</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCardMRIScho2']</value>
      <webElementGuid>77ab6710-9455-4f6b-adae-6a3ebd506d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div[9]/div/div/select</value>
      <webElementGuid>7c30a920-8ed2-497d-ae00-ff95cf2f2789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[13]</value>
      <webElementGuid>77f13d53-91a9-443a-8995-ddef78c6394c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[9]</value>
      <webElementGuid>6dbe129b-f14f-4601-b0a3-38d52f3dae8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[9]</value>
      <webElementGuid>9109d960-3a3f-44ec-8974-a36cd8cb3ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[9]/div/div/select</value>
      <webElementGuid>b9a54d7c-8337-4185-bc5e-3b413d381bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCardMRIScho2' and (text() = '
					--Select--
					YES
					NO
				' or . = '
					--Select--
					YES
					NO
				')]</value>
      <webElementGuid>33a0d871-a0a8-4c17-a430-04808fe5b200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
