<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ExpirationDate_icon</name>
   <tag></tag>
   <elementGuidId>262d8d60-92bb-4a44-8cf1-0320b50e8ce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4bfe8940-9774-476a-9db2-236258417d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>933d18ea-f563-4d17-90bd-9b03be8ba541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CheckIDs();</value>
      <webElementGuid>e5cccb75-32ab-4e83-859c-a842af895be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-add-circle-fill</value>
      <webElementGuid>e62ffa63-db97-45ea-afda-518c612e40f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon&quot;)</value>
      <webElementGuid>83e9351e-8fac-418c-952f-1ec7ff5448ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='icon']</value>
      <webElementGuid>927cd16a-f342-4f20-802e-66ccae8ef72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btnicon']/i</value>
      <webElementGuid>12b6d13b-9d29-4f09-8917-3d86b2f7c101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/a/i</value>
      <webElementGuid>176546f7-ba55-4785-9b17-e8df2b1c7603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'icon']</value>
      <webElementGuid>2d6e1feb-4d8f-4989-97d5-26e98f410210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
