<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YES_FormerEmployee</name>
   <tag></tag>
   <elementGuidId>be99ed5f-134a-4b99-a60f-08f6d53e145c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFormerEmployeeNO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtFormerEmployeeNO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74e2eea5-b7ac-4450-a947-f01bc0659eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4a2356a2-7f7d-447b-88c2-2e57767f24d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs </value>
      <webElementGuid>0128c970-8ee2-4527-ab0e-b85ced8aa436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>93d8d297-42f4-43a4-bea5-e5a9df7b5f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFormerEmployeeNO</value>
      <webElementGuid>4b16bfc9-9a42-4180-a59e-3fad970e0635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FormerEmployee</value>
      <webElementGuid>00601a7f-51e6-45ed-b4eb-2fa0eb1c56dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFormerEmployeeNO&quot;)</value>
      <webElementGuid>5b366212-c79c-4ebe-9a49-37ba3fa466e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFormerEmployeeNO']</value>
      <webElementGuid>56556197-06cc-43fb-a897-4cd2fe17d6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[22]/div[2]/input</value>
      <webElementGuid>a45fe2c8-17c8-4e18-9b34-183cd6ce3488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div[2]/input</value>
      <webElementGuid>8b6db1b2-a4d9-4224-8cf1-8b6f17f985f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'txtFormerEmployeeNO' and @name = 'FormerEmployee']</value>
      <webElementGuid>a189180b-dbce-46f8-b9b7-97bdfb3d9336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
