<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BisexualGayLesbianQueerTra_c208c0</name>
   <tag></tag>
   <elementGuidId>64749d24-2575-405b-82d7-3726ec7908f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSexualOrientation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboSexualOrientation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2b90e505-9bfb-4c79-89d4-e78d396febf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSexualOrientation</value>
      <webElementGuid>96719ac4-a680-48b9-bc04-f63b4bd0738e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateTitle();</value>
      <webElementGuid>4a90bb5e-4203-4e56-affb-e0d28e12a0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>79b9631f-432b-438a-b1f1-0a8496d14d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>baad0ac7-9140-40d6-a18c-cfda1a3151d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BisexualGayLesbianQueerTransgender+AgenderAsexual+Bigender+Gender Queer+Gender VirantIntersex+Pangender+PansexualQuestioning</value>
      <webElementGuid>2c75ff55-19c4-4a2e-9681-27ec15eac3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSexualOrientation&quot;)</value>
      <webElementGuid>7a05bdfd-6b5b-4fb4-99dc-e925e0bb302d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSexualOrientation']</value>
      <webElementGuid>a33c3835-7c1e-49b2-928d-a69a6bbbbef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[11]/div/div/select</value>
      <webElementGuid>15ae75e9-7f19-41c2-93f8-ca1a423f19c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/select</value>
      <webElementGuid>5260f281-98d0-404f-93be-ec13eb021211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSexualOrientation' and (text() = '--Select--BisexualGayLesbianQueerTransgender+AgenderAsexual+Bigender+Gender Queer+Gender VirantIntersex+Pangender+PansexualQuestioning' or . = '--Select--BisexualGayLesbianQueerTransgender+AgenderAsexual+Bigender+Gender Queer+Gender VirantIntersex+Pangender+PansexualQuestioning')]</value>
      <webElementGuid>36eba415-381d-41a3-bbe9-88115e096c97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
