<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --BAGONG POOK (S_ac7106</name>
   <tag></tag>
   <elementGuidId>f365cfeb-3d8f-4826-98d5-ce8eb5d1d212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCustomerCenter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCustomerCenter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>982b2417-73e3-4209-add9-af50ac11ff6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCustomerCenter</value>
      <webElementGuid>ae70bbc1-c95f-49c6-9b59-16e7be39ba3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>80a2fa7a-c7ed-4ad2-b1d2-b052979a1962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>c033eb95-e161-49b0-98d8-4eb5ce267d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --BAGONG POOK (SAN PABLO)Report TestDAMA DE NOCHEDEL REMEDIO (SAN PABLO CITY)DOMISONFARCON VILLEGUADALUPEHIILS DAYLYNVILLEPAMELAPATRIAPUROK 2 SAN PABLOSAMPALOCSAN CRISPINSAN FRANCISCOSAN FRANCISCO 2SAN FRANCISCO 3SAN FRANCISCO 4SAN FRANCISCO 5SAN GREGORIOSAN RAFAELSAN RAFAEL 2SAN ROQUESK3-AIMOKSTA. MONICASTA. MONICA 2STO. NINOWAWABINAN REMAININGMangaCenter101</value>
      <webElementGuid>fe88e156-cd2c-4866-bba2-963544553ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCustomerCenter&quot;)</value>
      <webElementGuid>580d52f7-9263-4d56-8e87-a49f3a0f7cc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCustomerCenter']</value>
      <webElementGuid>c862284b-5ed8-4ebd-8b8e-a11bbd3a6a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[20]/div/div/select</value>
      <webElementGuid>826cc3a8-c90b-421e-8fcf-bfd7ed93f91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARD Scholar :'])[1]/preceding::select[1]</value>
      <webElementGuid>ffef1d4d-a8e7-4b96-b51c-5db2f0bc73cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YES'])[2]/preceding::select[1]</value>
      <webElementGuid>8c321ecc-cae8-42b1-a623-ea798d242181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/select</value>
      <webElementGuid>25ea06a1-0a37-45f3-a0fb-d29e403a2600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCustomerCenter' and (text() = '--      Select      --BAGONG POOK (SAN PABLO)Report TestDAMA DE NOCHEDEL REMEDIO (SAN PABLO CITY)DOMISONFARCON VILLEGUADALUPEHIILS DAYLYNVILLEPAMELAPATRIAPUROK 2 SAN PABLOSAMPALOCSAN CRISPINSAN FRANCISCOSAN FRANCISCO 2SAN FRANCISCO 3SAN FRANCISCO 4SAN FRANCISCO 5SAN GREGORIOSAN RAFAELSAN RAFAEL 2SAN ROQUESK3-AIMOKSTA. MONICASTA. MONICA 2STO. NINOWAWABINAN REMAININGMangaCenter101' or . = '--      Select      --BAGONG POOK (SAN PABLO)Report TestDAMA DE NOCHEDEL REMEDIO (SAN PABLO CITY)DOMISONFARCON VILLEGUADALUPEHIILS DAYLYNVILLEPAMELAPATRIAPUROK 2 SAN PABLOSAMPALOCSAN CRISPINSAN FRANCISCOSAN FRANCISCO 2SAN FRANCISCO 3SAN FRANCISCO 4SAN FRANCISCO 5SAN GREGORIOSAN RAFAELSAN RAFAEL 2SAN ROQUESK3-AIMOKSTA. MONICASTA. MONICA 2STO. NINOWAWABINAN REMAININGMangaCenter101')]</value>
      <webElementGuid>7e265cae-3c2d-4215-950a-f34f918bb4ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
