<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--AglipayanBorn AgainEvangel_87720a</name>
   <tag></tag>
   <elementGuidId>93a0516b-b6bf-4403-a1a1-94845f0f3185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboReligion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboReligion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7252a88b-acc8-4873-b382-77c10ad7bf12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboReligion</value>
      <webElementGuid>29afc484-ebce-4934-8157-92a64d816b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>0bbe6781-6c8f-49e4-9398-ab6459e90e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>11907dd6-dd52-4c92-9983-2ce414e0a7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AglipayanBorn AgainEvangelicalIglesia ni KristoIslamJehova's WitnessOthersProtestantRoman CatholicSeventh-day Adventist</value>
      <webElementGuid>543e391d-290c-429e-bdef-d67e38a2207c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboReligion&quot;)</value>
      <webElementGuid>b66c133b-13f0-4c11-a028-55b17ecab8d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboReligion']</value>
      <webElementGuid>3bbd5dcb-ff21-42d5-bce7-82226676b79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[21]/div/div/select</value>
      <webElementGuid>62d373ad-e911-4ebc-a31e-48fedae3b158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div/select</value>
      <webElementGuid>78227cce-a098-4919-9948-06a52d74dabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboReligion' and (text() = concat(&quot;--Select--AglipayanBorn AgainEvangelicalIglesia ni KristoIslamJehova&quot; , &quot;'&quot; , &quot;s WitnessOthersProtestantRoman CatholicSeventh-day Adventist&quot;) or . = concat(&quot;--Select--AglipayanBorn AgainEvangelicalIglesia ni KristoIslamJehova&quot; , &quot;'&quot; , &quot;s WitnessOthersProtestantRoman CatholicSeventh-day Adventist&quot;))]</value>
      <webElementGuid>74bf2c6e-0da6-47cc-b60e-6d862aaaa801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
