<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_--      Select      --0 - Hindi13 - Oo</name>
   <tag></tag>
   <elementGuidId>5c4e1458-f6f7-4b9f-96d4-11fb9b311d1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tblPPIBodyEighth > tr > td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblPPIBodyEighth']/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>78e989e1-4ace-4be1-beec-ee961f163b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --[0] - Hindi[13] - Oo</value>
      <webElementGuid>0e79b9ce-7d25-421c-87d6-dd4b97dd710b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblPPIBodyEighth&quot;)/tr[1]/td[2]</value>
      <webElementGuid>da55da1f-695d-4acc-9a30-230dfbe3a958</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblPPIBodyEighth']/tr/td[2]</value>
      <webElementGuid>d393d843-14f5-4c27-9a81-ec65be2f3ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Puntos'])[2]/following::td[16]</value>
      <webElementGuid>5e345b7b-1a30-49b0-bf5e-3ae9d25f53a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mga Indikasyon/Indicators'])[2]/following::td[16]</value>
      <webElementGuid>75963dec-3258-4c12-afe4-3ba97037eec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Score:'])[1]/preceding::td[5]</value>
      <webElementGuid>97ffbc34-5ee4-43d2-83e6-593c18edde82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[8]/tr/td[2]</value>
      <webElementGuid>2d927018-509d-4067-a54d-7eee1242c557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '--      Select      --[0] - Hindi[13] - Oo' or . = '--      Select      --[0] - Hindi[13] - Oo')]</value>
      <webElementGuid>357a69f0-393c-404b-be09-cd954be0af1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
