<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Dashboard</name>
   <tag></tag>
   <elementGuidId>fa3c1142-2aa0-4243-a714-51c28d9a56a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-header.card-header-success.card-header-icon > h4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div/div[4]/div/div/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>a799cf10-e28d-4ad2-90c1-f965275b8a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>2120aee0-8108-46fc-a43a-9634ebc1c0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;wrapper show&quot;]/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;card shadow mb-4&quot;]/div[@class=&quot;card-header card-header-success card-header-icon&quot;]/h4[1]</value>
      <webElementGuid>b5c7d613-90b1-4f1e-8fea-6388db74d186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div[4]/div/div/div/div/h4</value>
      <webElementGuid>abc7382e-a40a-4150-9f0f-760ee40f7fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Welcome to your dashboard! We', &quot;'&quot;, 're glad to have you here.')])[1]/preceding::h4[1]</value>
      <webElementGuid>36a22e34-76bd-44f2-aa03-ab47436f028e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate Report'])[1]/preceding::h4[1]</value>
      <webElementGuid>7ba1b07c-734b-40fe-af28-4586e0c10965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/h4</value>
      <webElementGuid>9fe7d6fb-035e-43ce-a865-b9bb43ea32db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>2bc4c799-297a-425b-9605-143b7717cc82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
