<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birthday_txtdoBirth</name>
   <tag></tag>
   <elementGuidId>b07ddc97-1cc8-488e-b158-446a6d1c6c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtdoBirth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtdoBirth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a95616ce-a925-4315-a259-edbc216cac1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3ace946d-3da0-4a9b-a474-1907c56b92cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>4a3ce0b4-68a1-42bb-902f-e23536a61098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-upppercase datepicker gb-border-fcs text-uppercase</value>
      <webElementGuid>7cadcaf7-336a-4735-99c0-69ca9d32248a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>computeAge();</value>
      <webElementGuid>650a4b03-c945-4017-8a17-fbe49b7b04e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2999-12-12</value>
      <webElementGuid>405a7770-4817-4949-9bde-1047dc1f894e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtdoBirth</value>
      <webElementGuid>27f50ba7-20f5-4485-aa1b-83d7eb5af528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtdoBirth&quot;)</value>
      <webElementGuid>22287090-c51b-4420-9beb-3dba4a89c4b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtdoBirth']</value>
      <webElementGuid>6454fa6a-5939-4024-b1ca-a782b9a52a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='validationForm']/div/div[2]/div/div/input</value>
      <webElementGuid>4d2b580e-8c44-4c94-9ab3-5485d2911a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/input</value>
      <webElementGuid>c8d2efce-5d2e-4eca-838b-60a66e4b1f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'txtdoBirth']</value>
      <webElementGuid>527b030c-bae6-4c81-b4e8-a7460c85e3d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
