<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FirstName_txtFname</name>
   <tag></tag>
   <elementGuidId>cc89741a-f010-4a9c-9cb8-a4f3a9f76e6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtFname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>177015bc-a312-4cd8-8ae0-db73da532faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>72021343-e6e6-4031-b65e-9ed20a50c60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ff9fe31-882a-4230-a20b-504a50ad92db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-capitalize gb-border-fcs</value>
      <webElementGuid>1f9a1677-0a4c-4216-a758-6473859ce902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checkNames();</value>
      <webElementGuid>e53fb985-1135-47e9-b172-2a99145b51d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFname</value>
      <webElementGuid>75d2d585-90d0-4587-94d7-534895dd222c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFname&quot;)</value>
      <webElementGuid>9e2504b1-1020-489a-aaf3-10ca68e7885f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFname']</value>
      <webElementGuid>ee7c3cfd-2f0b-43e4-865e-941c1b627794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='validationForm']/div/div/div/div/input</value>
      <webElementGuid>da89c21e-b6ef-42ac-910b-ec5272d9b3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/input</value>
      <webElementGuid>bb17e252-d982-43b4-881b-f8e220f5612e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtFname']</value>
      <webElementGuid>d56ddc0f-e572-4f0b-a876-d3b9a3a81a7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
