<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MiddleName_nomiddlename</name>
   <tag></tag>
   <elementGuidId>da5ce789-1d08-4a5e-8dd3-a8d96744ee37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nomiddlename</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nomiddlename']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83ae3a14-9c14-49fa-9384-77caf063df6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1e5aa6cc-d698-4e0f-8b80-ac6ac146d292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input </value>
      <webElementGuid>2309a679-4eba-44b5-9adb-984e56549189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a319fb8e-6ed1-4fbb-b80b-73e53e690df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>noMiddlename();</value>
      <webElementGuid>a0320fc3-2b7a-439c-8390-3f6759c0bf5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomiddlename</value>
      <webElementGuid>056535c2-022b-4ba8-aba9-3d521bb4397a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomiddlename&quot;)</value>
      <webElementGuid>c7d4f6b3-25e1-4f51-9c48-1652e7f587e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomiddlename']</value>
      <webElementGuid>38cf07e4-f715-48a8-b8f6-4683a9b64c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='validationForm']/div/div/div[2]/div/input[2]</value>
      <webElementGuid>e1a5caa7-56a0-48b7-93e2-96ccd6d90da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>a0acb199-baa3-4004-81e4-7a5a68159230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'nomiddlename']</value>
      <webElementGuid>4d5ccc87-bd27-42c6-9449-59221faa525b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
