<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MiddleName_txtMname</name>
   <tag></tag>
   <elementGuidId>1b62288c-8047-4a7e-9e53-8f3f490bd2fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtMname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9bc1815-98f3-461f-9ba7-3b8768d19677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>213f50ef-aefa-4b1b-b9a7-dd6362f949cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d8a8ec26-31f6-47dc-ae4e-8e45ca0e3265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checkPersonalInfoMiddleName();</value>
      <webElementGuid>0ac83bca-c41d-403a-8756-c7bb039f494b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-capitalize gb-border-fcs</value>
      <webElementGuid>833ccee1-cb66-44ed-931d-1f08416ef14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMname</value>
      <webElementGuid>4141d850-36ad-4494-a664-843f36e35253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMname&quot;)</value>
      <webElementGuid>a0f22859-f242-4ca2-8f4b-0ad1bc432c02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMname']</value>
      <webElementGuid>d4534f32-5f38-44a0-b4d2-3c053b66bdbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='validationForm']/div/div/div[2]/div/input</value>
      <webElementGuid>dbafffea-e3da-440e-bc3b-f20f18ae7b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c6aa8c96-00b3-4c28-94c9-519e14704bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtMname']</value>
      <webElementGuid>14add4ef-7868-4bfa-a58c-5a70ee0b595d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
