<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Placeof Issue_txtPlaceOfIssue2</name>
   <tag></tag>
   <elementGuidId>b1bb2630-b6ea-4ff3-bb74-479c5fe62946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPlaceOfIssue2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPlaceOfIssue2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0e23b4b-3ed8-44b7-b3b7-412c8a781776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>474b2f4c-9092-4d1f-a208-48348d0ca8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8eefce1c-c0f1-43e5-a668-2c3e2a6d3cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs text-capitalize font-11</value>
      <webElementGuid>fc610815-bc85-4a9b-8183-161c3022456a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPlaceOfIssue2</value>
      <webElementGuid>ee932a82-fce5-419b-b813-8dd0b41eff40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPlaceOfIssue2&quot;)</value>
      <webElementGuid>bcd86c1c-b92f-426b-a5aa-0ef9551115b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPlaceOfIssue2']</value>
      <webElementGuid>b193d75b-5b82-4539-879e-3316ed083e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OtherIDs']/div[3]/div/input</value>
      <webElementGuid>5158c659-8f4f-4125-9345-d007fb02c9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[3]/div/input</value>
      <webElementGuid>cc23c4bf-aa79-4fd1-8047-10f108ff5a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtPlaceOfIssue2']</value>
      <webElementGuid>fa8c76b7-3a2c-454d-8833-73f25c7a37ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
