<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Barangay CertificateBIR TI_0033e0_1</name>
   <tag></tag>
   <elementGuidId>83d9774e-e490-4528-8b2f-70a5e7e7e92a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboIDType2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboIDType2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ecbd068c-bb73-471f-9032-ede98f58cf9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboIDType2</value>
      <webElementGuid>fc133c1e-901c-41ef-8ee8-cef9dfaea1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checkid()</value>
      <webElementGuid>c652661d-5ca2-4ffa-b0c8-1e2cafafad7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>38205f86-6dbb-45d7-8661-fb8e1675332c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Barangay CertificateBIR TINCompany IDDriver's License IDGSIS IDNBI ClearanceOWWA IDPag-IBIG IDPassportPhilHealth IDPostal IDPRC IDSenior Citizen IDSSS IDUMIDVoter's ID</value>
      <webElementGuid>1d353898-f618-4bd5-a770-7032fe900dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboIDType2&quot;)</value>
      <webElementGuid>1aa7d0c4-87b8-4b9e-a039-6bf8f84ef6ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboIDType2']</value>
      <webElementGuid>1f5bc1db-0ed5-4357-9ab3-5a2c902b64b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OtherIDs']/div/div/div/select</value>
      <webElementGuid>d89dcca2-92c7-4043-95dd-8cf651696083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove Additional ID Presented'])[1]/following::select[1]</value>
      <webElementGuid>31269414-bd67-448d-ac8a-b2e3622468ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/select</value>
      <webElementGuid>eb5db49e-ff2b-4585-92df-1cef75527300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboIDType2' and (text() = concat(&quot;--Select--Barangay CertificateBIR TINCompany IDDriver&quot; , &quot;'&quot; , &quot;s License IDGSIS IDNBI ClearanceOWWA IDPag-IBIG IDPassportPhilHealth IDPostal IDPRC IDSenior Citizen IDSSS IDUMIDVoter&quot; , &quot;'&quot; , &quot;s ID&quot;) or . = concat(&quot;--Select--Barangay CertificateBIR TINCompany IDDriver&quot; , &quot;'&quot; , &quot;s License IDGSIS IDNBI ClearanceOWWA IDPag-IBIG IDPassportPhilHealth IDPostal IDPRC IDSenior Citizen IDSSS IDUMIDVoter&quot; , &quot;'&quot; , &quot;s ID&quot;))]</value>
      <webElementGuid>02570148-018e-4de7-93a7-5dcdaa6bdfa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
