<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --Atty.Dr.Eng.Hon.MrMrsMs</name>
   <tag></tag>
   <elementGuidId>ea032aea-0b51-413d-ab2f-9f4d50e0b2e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bab1b4e3-7d4d-4de8-bf35-5d7bd68866c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboTitle</value>
      <webElementGuid>02a4ef3a-23b7-4d28-b2a3-42e3460b0850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateTitle();</value>
      <webElementGuid>f539c5fa-a124-4f44-9cb8-10c150f16f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>c29f493c-7949-4903-9211-7ca9acc8c90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>40c0004e-c348-4ec0-90f0-f24f242e642f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																		-- Select --Atty.Dr.Eng.Hon.MrMrsMs</value>
      <webElementGuid>b2d5706f-1d43-4a50-92e6-2cac87a9a916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboTitle&quot;)</value>
      <webElementGuid>f618b562-ca80-407d-9441-c09e874f1c76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboTitle']</value>
      <webElementGuid>f4159b80-b354-4b4c-8735-a01d5581c8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[5]/div/select</value>
      <webElementGuid>8633f0f4-46fd-45a4-94d8-4793c6043095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>eeefd412-cfd8-4b91-80c3-543c6a2c6b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboTitle' and (text() = '
																		-- Select --Atty.Dr.Eng.Hon.MrMrsMs' or . = '
																		-- Select --Atty.Dr.Eng.Hon.MrMrsMs')]</value>
      <webElementGuid>2d425a41-0b85-4a9b-aa49-1908377523f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
