<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BusinessGovernment Employe_69ab64</name>
   <tag></tag>
   <elementGuidId>198ca2e9-2f15-482f-9433-ba33abd5dfa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboOccupation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboOccupation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>500ffdc8-da45-4869-ad9f-ddfccb559dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboOccupation</value>
      <webElementGuid>6737b110-60ab-4278-bd55-ec2ab466a496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>048e390a-ee4a-435f-85b5-5bcc717a299c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>ad70c9a6-d504-49ff-980e-8fab039e2368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BusinessGovernment EmployeeOthersPrivate Emplovee</value>
      <webElementGuid>9c5311a6-1574-4f72-a3c8-d5e6e938383a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboOccupation&quot;)</value>
      <webElementGuid>79bececb-3d71-4af9-9acf-2954b639c911</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboOccupation']</value>
      <webElementGuid>7e96194b-73dc-413e-8cce-f0394ef3bc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[2]/div/div/select</value>
      <webElementGuid>53a4555c-8191-42c9-b403-0301212e5f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>3b6a8b87-04f8-47a3-94b1-45d4aa0c8e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboOccupation' and (text() = '--Select--BusinessGovernment EmployeeOthersPrivate Emplovee' or . = '--Select--BusinessGovernment EmployeeOthersPrivate Emplovee')]</value>
      <webElementGuid>70beffd8-1094-45cd-8116-2561cb6996f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
