<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--PAETE (REGULAR)Sampalok 1P_2adbb5</name>
   <tag></tag>
   <elementGuidId>ad4d264e-bff7-48d9-b237-b202dafb1d78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCustomerUnit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCustomerUnit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0aa065f4-3acb-42c0-a8a1-8ee61a3a242a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCustomerUnit</value>
      <webElementGuid>1406041a-0bdb-419b-851e-0477db6bd794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>1204168a-bc99-4063-bcfe-ac0c9e6b5912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>1f7e8cca-e934-4eb7-b44b-f028e02f7a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--PAETE (REGULAR)Sampalok 1PAGSANJAN (REGULAR)TANAYSAN PABLOPILA (REGULAR)MAGDALENA (REGULAR)STA. MARIA (REGULAR)</value>
      <webElementGuid>0345f29c-f483-474a-8e51-43f14dbcce6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCustomerUnit&quot;)</value>
      <webElementGuid>9e402dbb-be87-4bd8-808b-8648c3a98da0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCustomerUnit']</value>
      <webElementGuid>b2d910ca-ef9c-4b9b-a38e-0eb923b8ecf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[19]/div/div/select</value>
      <webElementGuid>79a8bcba-add7-4754-bc51-49593231a0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARD Scholar :'])[1]/preceding::select[2]</value>
      <webElementGuid>acf7cf5e-128c-4c7d-848b-57cb7ca277fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/select</value>
      <webElementGuid>81f5cb6a-c0a7-4839-bc57-d65433a16d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCustomerUnit' and (text() = '--Select--PAETE (REGULAR)Sampalok 1PAGSANJAN (REGULAR)TANAYSAN PABLOPILA (REGULAR)MAGDALENA (REGULAR)STA. MARIA (REGULAR)' or . = '--Select--PAETE (REGULAR)Sampalok 1PAGSANJAN (REGULAR)TANAYSAN PABLOPILA (REGULAR)MAGDALENA (REGULAR)STA. MARIA (REGULAR)')]</value>
      <webElementGuid>3d05bf95-990b-4c97-bd76-e0fb82abd667</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
