<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Numberof Children in School (input nu_5d3c1c</name>
   <tag></tag>
   <elementGuidId>8ad6b405-6cb5-471d-8faa-24a6528f6d93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPreSchool</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPreSchool']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2f1717b-21a4-40f6-b409-9773ddb6129b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>28bac46f-7cce-46b5-b5b5-6c294a175c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31c9f231-dde4-467b-85ce-73c3449cf433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>76782c81-4051-486a-a173-f09a135e1b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return onlyNumberKey(event)</value>
      <webElementGuid>a9185328-71e3-49b1-a4eb-f16111ce40a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPreSchool</value>
      <webElementGuid>fa75ad50-a365-4d7f-99a8-5d55905b79a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPreSchool&quot;)</value>
      <webElementGuid>7edde23b-2013-4bbb-b4d7-9bd659001dae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPreSchool']</value>
      <webElementGuid>dfb01423-634a-4ef3-8d7e-421a753959b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[8]/div/div/div/input</value>
      <webElementGuid>d84909b5-772e-471d-a635-32e23a36248c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/input</value>
      <webElementGuid>dd3a51f3-6b6d-4058-a415-da4b450888ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtPreSchool']</value>
      <webElementGuid>d1702c11-c61c-43fa-8525-8ae9ba926f84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
