<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--EmploymentSalariesIncome f_b99596</name>
   <tag></tag>
   <elementGuidId>6fcf13f4-e32b-44f5-9729-d10c8cc07d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboKYCSourceOfIncome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboKYCSourceOfIncome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5b8c2c6b-c8a7-4d76-bd97-ffb912fc83e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboKYCSourceOfIncome</value>
      <webElementGuid>897f31ff-f63a-4e9d-8582-b3d50c7c101b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checksourceOfFund();</value>
      <webElementGuid>873024bf-5d50-461d-9153-a64a07162322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>9406b912-bf32-49db-96d5-55d138405e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension</value>
      <webElementGuid>f85d269b-149a-42c0-9793-a007cde911ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboKYCSourceOfIncome&quot;)</value>
      <webElementGuid>32a95567-0a74-4a92-b5f9-b8fe4f1d166d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboKYCSourceOfIncome']</value>
      <webElementGuid>45dbd5d7-5aa1-4187-9684-96cc1f3e2823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>01b54ab3-a16f-4f94-afdf-06bc52c604bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>916b5189-3ed7-449e-8fe4-1406c7d65cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboKYCSourceOfIncome' and (text() = '--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension' or . = '--Select--Employment/SalariesIncome from businessInheritanceOthersProceeds from investmentRemittancesRetirement/Pension')]</value>
      <webElementGuid>2aa5d7c4-2540-46e9-9caa-40534fadf40b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
