<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Below 1,000 pesos1001 - 3,_8e7891</name>
   <tag></tag>
   <elementGuidId>4cc62337-03fd-48c8-b8c2-8fac05c6196b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboHouseholdMonthlyInc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboHouseholdMonthlyInc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>97ddbfc7-498b-4891-8b53-ef177c96e88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboHouseholdMonthlyInc</value>
      <webElementGuid>e1314ddd-cd99-444e-a04d-de727528556c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>b3f4089a-e446-4428-96eb-eab8b3e73b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Below 1,000 pesos1001 - 3,000 pesos3001 - 5,000 pesos5001 - 8,000 pesos8001 - 10,000 pesos10001 - 15,000 pesosAbove 15,000 pesos</value>
      <webElementGuid>3af8c706-310f-4b2d-b19a-0587c9b054ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboHouseholdMonthlyInc&quot;)</value>
      <webElementGuid>efa82c3c-7bb4-4639-804c-fdc06c13f064</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboHouseholdMonthlyInc']</value>
      <webElementGuid>cd7cb957-e697-4394-a442-cbd172dde50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[5]/div/div/select</value>
      <webElementGuid>2df9bdae-0f73-4202-a29c-be7b8153cea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMLA watchlist? :'])[1]/preceding::select[1]</value>
      <webElementGuid>e6ac0039-7dbd-4a2d-8ee4-656c4d0d3966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[5]/div/div/select</value>
      <webElementGuid>0c64e923-0d84-4288-b059-72a1ef0f8788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboHouseholdMonthlyInc' and (text() = '--Select--Below 1,000 pesos1001 - 3,000 pesos3001 - 5,000 pesos5001 - 8,000 pesos8001 - 10,000 pesos10001 - 15,000 pesosAbove 15,000 pesos' or . = '--Select--Below 1,000 pesos1001 - 3,000 pesos3001 - 5,000 pesos5001 - 8,000 pesos8001 - 10,000 pesos10001 - 15,000 pesosAbove 15,000 pesos')]</value>
      <webElementGuid>cdf2c396-ad1e-4917-bdf6-a15de910fae5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
