<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FirstName_txtmothersMaidenFName</name>
   <tag></tag>
   <elementGuidId>56732f1b-1aa9-4d86-ade7-7f5a33c5f330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtmothersMaidenFName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtmothersMaidenFName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd5d6567-38cb-4572-874a-d1a3d6722d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>18d384cc-ef25-48d3-a759-3b9c5c3316a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af98adcb-ff46-4715-8420-01d46b1d914f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs text-capitalize font-11</value>
      <webElementGuid>2cd8a2b6-3ed2-4301-9c45-70b3acea8b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtmothersMaidenFName</value>
      <webElementGuid>9de7c302-7b39-4c42-a07e-ba2a716006c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checkNames();</value>
      <webElementGuid>8cadc3f4-d81c-470e-a520-7ecac6e24ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtmothersMaidenFName&quot;)</value>
      <webElementGuid>10be23f2-5125-493b-af24-881a265b053d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtmothersMaidenFName']</value>
      <webElementGuid>1092c170-8eee-45b1-8712-1b3b6c21f3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[18]/div/input</value>
      <webElementGuid>bfd46e2b-ce18-4d46-8c06-335267bf94d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/input</value>
      <webElementGuid>86fe3c86-9bef-4a7a-8413-3939729ff493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtmothersMaidenFName']</value>
      <webElementGuid>a80c27ef-aa19-40b3-b03b-43df9f48fb54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
