<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_with Disability_withdisability</name>
   <tag></tag>
   <elementGuidId>a2c769a0-1de5-462b-b4eb-847c2c2115c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='withdisability']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#withdisability</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8e5f6fc-ac31-4dc6-af4d-b7a0516d780c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>506b96bf-9e8d-4d9f-9316-0e5686a4dcd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs</value>
      <webElementGuid>f7c83850-719b-4a8d-a2dd-0cc117c38078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1c4ba592-dded-4874-b247-3f3c550b1453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>disability();</value>
      <webElementGuid>031160b0-7fd1-4f24-acc3-63ef82f0fccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdisability</value>
      <webElementGuid>2184aa4f-70dc-4363-9d8f-93cce8c7edee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>withdisability</value>
      <webElementGuid>77dbfca0-3603-42ee-aecd-c868b3a5a72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CLient Type</value>
      <webElementGuid>280a4212-b66f-4dae-b848-50bb444fbf66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdisability&quot;)</value>
      <webElementGuid>ce8ae267-f08f-4ffd-b909-47171b606208</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='withdisability']</value>
      <webElementGuid>895d3960-825d-4f07-8ac6-4629781fb143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>bce07fae-1540-4ff4-84d1-bb6105293919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a16d41e8-5f07-4714-9a3f-969fc2c88a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'withdisability' and @name = 'withdisability' and @placeholder = 'CLient Type']</value>
      <webElementGuid>ab997d5e-7351-4ba4-b4d2-b2d9d59ff723</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
