<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ClientCreation</name>
   <tag></tag>
   <elementGuidId>e9eb1b37-fdff-4bd4-a942-996cb6dd871c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CustomerPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CustomerPage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d1459e6-7928-461b-bd6f-1f3b6982f18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb-hover-side confirmation-link active</value>
      <webElementGuid>958de7da-3aaa-4e10-838d-8a932f29a72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>CustomerValidation</value>
      <webElementGuid>faa2ddfe-09f3-42fe-8b9d-6aa063ffa9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerPage</value>
      <webElementGuid>9086ef40-f265-4eda-82d2-03d8424fc829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return loadIframe('ifrm1', this.href);</value>
      <webElementGuid>84d323ae-6ca3-48c3-ab5a-3eaa7c7b27d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Client
									Creation</value>
      <webElementGuid>27f2f80c-41bc-4072-a1be-8ebbac7ddf9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomerPage&quot;)</value>
      <webElementGuid>26d12bb7-38d5-40fd-b1b0-e988640ef65e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CustomerPage']</value>
      <webElementGuid>dcb11e68-9da3-4f09-a4be-b3dabeab1e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarCustomer']/ul/li[2]/a</value>
      <webElementGuid>e5c8a695-1dd2-417c-ab4f-1bd8c83852d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Client
									Creation')]</value>
      <webElementGuid>81c3ac1b-f504-43a2-b61d-43a1078a284a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/following::a[2]</value>
      <webElementGuid>b5321693-f8fc-476e-b4e1-df017f27d423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'CustomerValidation')]</value>
      <webElementGuid>ffb37219-b6d7-4b7b-a295-0e0d21c39bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li[2]/a</value>
      <webElementGuid>eff2112f-ba88-4803-9abc-0733c7d22bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'CustomerValidation' and @id = 'CustomerPage' and (text() = 'Client
									Creation' or . = 'Client
									Creation')]</value>
      <webElementGuid>35ed6718-485e-4d2e-872e-262a870251dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
