<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--NewTransferred</name>
   <tag></tag>
   <elementGuidId>71ec8675-fb15-4c61-a3d9-2ed1a573d660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboMembershiptype']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboMembershiptype</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c08f317d-07fa-4ded-a5a9-7d47eb84f3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboMembershiptype</value>
      <webElementGuid>91074733-62ef-47d1-bd07-353e1e6fe4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>computeAge()</value>
      <webElementGuid>de403c74-3d9d-4ed6-922e-42b631827272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>7575f960-8807-4aa9-900c-30d2f277f91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>4f7451e5-cc4b-410c-afd8-bc4027e6e948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--NewTransferred</value>
      <webElementGuid>b34055cf-5966-46b6-b1cf-9bdd86636c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboMembershiptype&quot;)</value>
      <webElementGuid>0fece773-cab6-457e-b801-1f3710dce5ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboMembershiptype']</value>
      <webElementGuid>2566924e-3eff-428c-a88b-d5d32504bf16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[3]/div/select</value>
      <webElementGuid>9c4a2a6e-4679-47da-afd5-f9efa7acbacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/following::select[1]</value>
      <webElementGuid>82fcf0ad-f504-4fbf-a6cc-d4b642cda35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3996e427-801e-420e-a810-3ec18a6a103f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboMembershiptype' and (text() = '--Select--NewTransferred' or . = '--Select--NewTransferred')]</value>
      <webElementGuid>9b73d7e6-0794-442e-a0f2-5cc299fc1354</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
