<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_txtBeneficiaryName2</name>
   <tag></tag>
   <elementGuidId>dd4e318b-4206-433c-bfb9-b1d478828207</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtBeneficiaryName2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtBeneficiaryName2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7a52f5b-f5b8-442d-8387-adcada4c83fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>66962052-6533-4303-9b41-61e4fcaa775d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>051c5d7b-533d-40c7-a906-c0f9d69f76ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs text-capitalize font-9</value>
      <webElementGuid>3eafae21-f1ab-415a-a13e-c4fb575626d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9134526d-35f2-44f9-88be-59ec60b30edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtBeneficiaryName2</value>
      <webElementGuid>66c05fb4-d5fb-4f8a-a768-993ad094f578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtBeneficiaryName2&quot;)</value>
      <webElementGuid>e4a91bfc-adf8-4c33-9195-257b6a98e2ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtBeneficiaryName2']</value>
      <webElementGuid>29b6325f-209b-4c2b-9ef4-19f12777cbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div/div/div/input</value>
      <webElementGuid>e32608f8-d2a8-4a97-bae3-9eaf5a2bb574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/input</value>
      <webElementGuid>988f2567-225a-4181-91f5-2d61cd55082d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtBeneficiaryName2']</value>
      <webElementGuid>80fee1cb-2cde-454b-b173-1ce0c2d3a1ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
