<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--YESNO</name>
   <tag></tag>
   <elementGuidId>644fa21a-6bbf-4446-b518-b278b6001528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboWithDisability1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboWithDisability1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>34dcbe9a-62ae-4ac0-85ba-f4b377b2404a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboWithDisability1</value>
      <webElementGuid>5842f208-c387-4449-bd4c-5b962440386c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>beneficiaryDisability();</value>
      <webElementGuid>f349bae3-1934-4cdb-b6ff-48d85ac29848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d7ae791b-7214-4413-8276-7499b162a35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>2e9d6c7e-56b3-4dfc-a1f3-488e7b11dc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																			--Select--
																			YES
																			NO
																		</value>
      <webElementGuid>b3de50f3-b059-4f20-89df-ac46154cdda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboWithDisability1&quot;)</value>
      <webElementGuid>4b3aedfe-fefe-4975-af61-90fd134a986d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboWithDisability1']</value>
      <webElementGuid>262f9117-0423-451c-8d3f-f387948c5aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row1']/div/div[7]/div/div/select</value>
      <webElementGuid>e6a5feb3-5771-4fe2-abb4-f28e42fe6392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[5]</value>
      <webElementGuid>81a56f4b-6746-4f64-b3da-af3b8ea9b5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[3]</value>
      <webElementGuid>0852c62f-7e0c-4910-80dc-788497c1f02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[3]</value>
      <webElementGuid>40d362d0-71ac-4e03-94ee-68d319e37558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[7]/div/div/select</value>
      <webElementGuid>f7994164-39b0-4247-a2b7-b768a9ccac55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboWithDisability1' and (text() = '
																			--Select--
																			YES
																			NO
																		' or . = '
																			--Select--
																			YES
																			NO
																		')]</value>
      <webElementGuid>9a6ff8c3-fa10-428b-84be-590fc98952ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
