<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--YESNO_1</name>
   <tag></tag>
   <elementGuidId>7eb30e7a-0898-42bf-87f9-5791ffecfa7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboCardMRIScho1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCardMRIScho1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eff904a3-131b-4a01-baa7-b5676ada59a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCardMRIScho1</value>
      <webElementGuid>7030a72e-e430-4f21-95ba-739ed085a06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>84ee8e72-f946-4d9b-85c1-e9461aef2155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>d3f922fa-e631-4934-96f9-93fe7a7b9cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																			--Select--
																			YES
																			NO
																		</value>
      <webElementGuid>ba3e1557-af8d-4376-847e-029cadf42c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCardMRIScho1&quot;)</value>
      <webElementGuid>d3aab270-0296-4b24-a4ea-53c6c93d6714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCardMRIScho1']</value>
      <webElementGuid>359e4715-98fd-4d8c-89f1-ef1d34eb0ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row1']/div/div[9]/div/div/select</value>
      <webElementGuid>9ceaf908-048a-4a9b-8d12-79c9c3570904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[6]</value>
      <webElementGuid>ae7d7707-b1cd-49ec-ae16-ec4a8fa16566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[2]</value>
      <webElementGuid>dde65b39-1c2c-4668-b11d-0964f5837b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[2]</value>
      <webElementGuid>de011f39-1893-4d2b-869b-4f451d0f2558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[9]/div/div/select</value>
      <webElementGuid>d6e9f704-f949-429c-b9ad-80702b3eccca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCardMRIScho1' and (text() = '
																			--Select--
																			YES
																			NO
																		' or . = '
																			--Select--
																			YES
																			NO
																		')]</value>
      <webElementGuid>9d2328c0-c800-4385-8044-0ebd50a4bb84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
