<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --Abra - CAR (Co_3be376</name>
   <tag></tag>
   <elementGuidId>d24edef9-a92a-4237-9c22-583dcffc8cb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboPhyProvince']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboPhyProvince</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2bb6488c-5a7b-4958-8801-327b9784f007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboPhyProvince</value>
      <webElementGuid>a5eca348-9a5c-487f-9ac5-a818635791c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>e79f4a18-21f8-4ff1-8985-a3bc23139eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)</value>
      <webElementGuid>e0ee7395-0b7a-4b8d-9e0a-97ec13cb6315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboPhyProvince&quot;)</value>
      <webElementGuid>6fb99de7-bdf7-4b58-a2e7-2435de98b3eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboPhyProvince']</value>
      <webElementGuid>026ba915-060e-4228-b6f0-46d05779a930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>60e5de86-e531-4b7c-977d-66368c107335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>b65be0bf-cea7-4d60-a511-25fb46f625cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboPhyProvince' and (text() = '--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)' or . = '--      Select      --Abra - CAR (Cordillera Administrative Region)Agusan Del Norte - Region XIII (CARAGA)Agusan Del Sur - Region XIII (CARAGA)Aklan - Region VI (Western Visayas)Albay - Region V (Bicol Region)Antique - Region VI (Western Visayas)Apayao - CAR (Cordillera Administrative Region)Aurora - Region III (Central Luzon)Basilan - BARMM (Bangsamoro Region)Bataan - Region III (Central Luzon)Batanes - Region II (Cagayan Valley)Batangas - Region IV-A (CALABARZON)Benguet - CAR (Cordillera Administrative Region)Biliran - Region VIII (Eastern Visayas)Bohol - Region VII (Central Visayas)Bukidnon - Region X (NORTHERN MINDANAO)Bulacan - Region III (Central Luzon)Cagayan - Region II (Cagayan Valley)Camarines Norte - Region V (Bicol Region)Camarines Sur - Region V (Bicol Region)Camiguin - Region X (NORTHERN MINDANAO)Capiz - Region VI (Western Visayas)Catanduanes - Region V (Bicol Region)Cavite - Region IV-A (CALABARZON)Cebu - Region VII (Central Visayas)Compostela Valley - Region XI (DAVAO Region)Cotabato - Region XII (SOCCSKSARGEN)COTABATO (NORTH COTABATO) - Region XII (SOCCSKSARGEN)Davao Del Norte - Region XI (DAVAO Region)Davao Del Sur - Region XI (DAVAO Region)Davao Occidental - Region XI (DAVAO Region)Davao Oriental - Region XI (DAVAO Region)Dinagat Islands - Region XIII (CARAGA)Eastern Samar - Region VIII (Eastern Visayas)Guimaras - Region VI (Western Visayas)Ifugao - CAR (Cordillera Administrative Region)Ilocos Norte - Region I (Ilocos Region)Ilocos Sur - Region I (Ilocos Region)Iloilo - Region VI (Western Visayas)Isabela - Region II (Cagayan Valley)Kalinga - CAR (Cordillera Administrative Region)Laguna - Region IV-A (CALABARZON)Lanao Del Norte - Region X (NORTHERN MINDANAO)Lanao Del Sur - BARMM (Bangsamoro Region)La Union - Region I (Ilocos Region)Leyte - Region VIII (Eastern Visayas)Maguindanao - BARMM (Bangsamoro Region)Marinduque - Region IV-B (MiMaRoPa)Masbate - Region V (Bicol Region)Metro Manila 1st District - NCR (National Capital Region)Metro Manila 2nd District - NCR (National Capital Region)Metro Manila 3rd District - NCR (National Capital Region)Metro Manila 4th District - NCR (National Capital Region)Misamis Occidental - Region X (NORTHERN MINDANAO)Misamis Oriental - Region X (NORTHERN MINDANAO)Mountain Province - CAR (Cordillera Administrative Region)Negros Occidental - Region VI (Western Visayas)Negros Oriental - Region VII (Central Visayas)Northern Samar - Region VIII (Eastern Visayas)Nueva Ecija - Region III (Central Luzon)Nueva Vizcaya - Region II (Cagayan Valley)Occidental Mindoro - Region IV-B (MiMaRoPa)Oriental Mindoro - Region IV-B (MiMaRoPa)Palawan - Region IV-B (MiMaRoPa)Pampanga - Region III (Central Luzon)Pangasinan - Region I (Ilocos Region)Quezon - Region IV-A (CALABARZON)Quirino - Region II (Cagayan Valley)Rizal - Region IV-A (CALABARZON)Romblon - Region IV-B (MiMaRoPa)SAMAR (WESTERN SAMAR) - Region VIII (Eastern Visayas)Sarangani - Region XII (SOCCSKSARGEN)Siquijor - Region VII (Central Visayas)Sorsogon - Region V (Bicol Region)South Cotabato - Region XII (SOCCSKSARGEN)Southern Leyte - Region VIII (Eastern Visayas)Sultan Kudarat - Region XII (SOCCSKSARGEN)Sulu - BARMM (Bangsamoro Region)Surigao Del Norte - Region XIII (CARAGA)Surigao Del Sur - Region XIII (CARAGA)Tarlac - Region III (Central Luzon)Tawi-Tawi - BARMM (Bangsamoro Region)Test Aklan - XXX Region VI XXXTest Ilocos Norte - Region I (Ilocos Region)Zambales - Region III (Central Luzon)Zamboanga Del Norte - Region IX (Zamboanga Peninsula)Zamboanga Del Sur - Region IX (Zamboanga Peninsula)Zamboanga Sibugay - Region IX (Zamboanga Peninsula)')]</value>
      <webElementGuid>4d948034-99b3-447f-9025-c3bad2f55dd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
