<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AtisanBagong Bayan Ii-A (Pob.)Bagong_361eda</name>
   <tag></tag>
   <elementGuidId>91a277f7-77c0-4500-9db2-0aaff45d6198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboPhyAddBarangay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboPhyAddBarangay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0913acf6-443c-4519-a8e3-bca57cc0baa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboPhyAddBarangay</value>
      <webElementGuid>8f7a5238-43c1-4418-8c99-a901e35e6c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>f5f4fae0-533b-4d0f-8470-a6e86c032a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AtisanBagong Bayan Ii-A (Pob.)Bagong Pook Vi-C (Pob.)Barangay I-A (Pob.)Barangay I-B (Pob.)Barangay Ii-A (Pob.)Barangay Ii-B (Pob.)Barangay Ii-C (Pob.)Barangay Ii-D (Pob.)Barangay Ii-E (Pob.)Barangay Ii-F (Pob.)Barangay Iii-A (Pob.)Barangay Iii-B (Pob.)Barangay Iii-C (Pob.)Barangay Iii-D (Pob.)Barangay Iii-E (Pob.)Barangay Iii-F (Pob.)Barangay Iv-A (Pob.)Barangay Iv-B (Pob.)Barangay Iv-C (Pob.)Barangay V-A (Pob.)Barangay V-B (Pob.)Barangay V-C (Pob.)Barangay V-D (Pob.)Barangay Vi-A (Pob.)Barangay Vi-B (Pob.)Barangay Vi-D (Pob.)Barangay Vi-E (Pob.)Barangay Vii-A (Pob.)Barangay Vii-B (Pob.)Barangay Vii-C (Pob.)Barangay Vii-D (Pob.)Barangay Vii-E (Pob.)BautistaConcepcionDel RemedioDoloresSan Antonio 1San Antonio 2San BartolomeSan BuenaventuraSan CrispinSan CristobalSan DiegoSan FranciscoSan GabrielSan GregorioSan IgnacioSan IsidroSan JoaquinSan JoseSan JuanSan LorenzoSan Lucas 1San Lucas 2San MarcosSan MateoSan MiguelSan NicolasSan PedroSan RafaelSan RoqueSanta AnaSanta CatalinaSanta CruzSanta ElenaSanta FelominaSanta IsabelSanta MariaSanta Maria MagdalenaSanta MonicaSanta VeronicaSantiago ISantiago IiSantisimo RosarioSanto AngelSanto CristoSanto NiñoSan VicenteSoledad</value>
      <webElementGuid>5cf36bd5-a8fa-4fb4-b32a-493854985645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboPhyAddBarangay&quot;)</value>
      <webElementGuid>9f22aac6-b114-4618-a202-5bb12058cba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboPhyAddBarangay']</value>
      <webElementGuid>8ad1b5d6-f2ef-4de5-9635-4c09571ab7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div/div/div[6]/div/div/select</value>
      <webElementGuid>ef98f6fb-9d9a-402f-931c-b2ebf42c8b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Address'])[1]/preceding::select[1]</value>
      <webElementGuid>84d4febb-3a4b-4232-b8ff-46efbaadeaec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/select</value>
      <webElementGuid>e89f7c6a-3947-4421-9738-f43193662477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboPhyAddBarangay' and (text() = 'AtisanBagong Bayan Ii-A (Pob.)Bagong Pook Vi-C (Pob.)Barangay I-A (Pob.)Barangay I-B (Pob.)Barangay Ii-A (Pob.)Barangay Ii-B (Pob.)Barangay Ii-C (Pob.)Barangay Ii-D (Pob.)Barangay Ii-E (Pob.)Barangay Ii-F (Pob.)Barangay Iii-A (Pob.)Barangay Iii-B (Pob.)Barangay Iii-C (Pob.)Barangay Iii-D (Pob.)Barangay Iii-E (Pob.)Barangay Iii-F (Pob.)Barangay Iv-A (Pob.)Barangay Iv-B (Pob.)Barangay Iv-C (Pob.)Barangay V-A (Pob.)Barangay V-B (Pob.)Barangay V-C (Pob.)Barangay V-D (Pob.)Barangay Vi-A (Pob.)Barangay Vi-B (Pob.)Barangay Vi-D (Pob.)Barangay Vi-E (Pob.)Barangay Vii-A (Pob.)Barangay Vii-B (Pob.)Barangay Vii-C (Pob.)Barangay Vii-D (Pob.)Barangay Vii-E (Pob.)BautistaConcepcionDel RemedioDoloresSan Antonio 1San Antonio 2San BartolomeSan BuenaventuraSan CrispinSan CristobalSan DiegoSan FranciscoSan GabrielSan GregorioSan IgnacioSan IsidroSan JoaquinSan JoseSan JuanSan LorenzoSan Lucas 1San Lucas 2San MarcosSan MateoSan MiguelSan NicolasSan PedroSan RafaelSan RoqueSanta AnaSanta CatalinaSanta CruzSanta ElenaSanta FelominaSanta IsabelSanta MariaSanta Maria MagdalenaSanta MonicaSanta VeronicaSantiago ISantiago IiSantisimo RosarioSanto AngelSanto CristoSanto NiñoSan VicenteSoledad' or . = 'AtisanBagong Bayan Ii-A (Pob.)Bagong Pook Vi-C (Pob.)Barangay I-A (Pob.)Barangay I-B (Pob.)Barangay Ii-A (Pob.)Barangay Ii-B (Pob.)Barangay Ii-C (Pob.)Barangay Ii-D (Pob.)Barangay Ii-E (Pob.)Barangay Ii-F (Pob.)Barangay Iii-A (Pob.)Barangay Iii-B (Pob.)Barangay Iii-C (Pob.)Barangay Iii-D (Pob.)Barangay Iii-E (Pob.)Barangay Iii-F (Pob.)Barangay Iv-A (Pob.)Barangay Iv-B (Pob.)Barangay Iv-C (Pob.)Barangay V-A (Pob.)Barangay V-B (Pob.)Barangay V-C (Pob.)Barangay V-D (Pob.)Barangay Vi-A (Pob.)Barangay Vi-B (Pob.)Barangay Vi-D (Pob.)Barangay Vi-E (Pob.)Barangay Vii-A (Pob.)Barangay Vii-B (Pob.)Barangay Vii-C (Pob.)Barangay Vii-D (Pob.)Barangay Vii-E (Pob.)BautistaConcepcionDel RemedioDoloresSan Antonio 1San Antonio 2San BartolomeSan BuenaventuraSan CrispinSan CristobalSan DiegoSan FranciscoSan GabrielSan GregorioSan IgnacioSan IsidroSan JoaquinSan JoseSan JuanSan LorenzoSan Lucas 1San Lucas 2San MarcosSan MateoSan MiguelSan NicolasSan PedroSan RafaelSan RoqueSanta AnaSanta CatalinaSanta CruzSanta ElenaSanta FelominaSanta IsabelSanta MariaSanta Maria MagdalenaSanta MonicaSanta VeronicaSantiago ISantiago IiSantisimo RosarioSanto AngelSanto CristoSanto NiñoSan VicenteSoledad')]</value>
      <webElementGuid>98b8b532-9d5f-486f-b4ce-a92fb3db6f53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
