<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Dashboard</name>
   <tag></tag>
   <elementGuidId>27dac043-1bbe-4543-8642-2d5c18ca4e69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div/div[4]/div/div/div/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-header.card-header-success.card-header-icon > h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>4b6c6083-4860-4526-a3a0-6f5337b4410b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>b4906f78-7f38-4806-9017-61f661f3b295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;wrapper show&quot;]/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;card shadow mb-4&quot;]/div[@class=&quot;card-header card-header-success card-header-icon&quot;]/h4[1]</value>
      <webElementGuid>805ea836-893a-45bd-9c3d-97d10a102c4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div[4]/div/div/div/div/h4</value>
      <webElementGuid>e088e966-6fa8-4e07-ae5c-7f8dbbf1351f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Welcome to your dashboard! We', &quot;'&quot;, 're glad to have you here.')])[1]/preceding::h4[1]</value>
      <webElementGuid>747d2594-ec96-42ee-8773-2b1dec1d73a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/h4</value>
      <webElementGuid>6cad5207-1b8c-4caa-adc1-81f8bfcf3c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>18c494c6-2ec5-4523-8579-ca92fc59782c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
