<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HouseholdMonthly Expense_txtMonthlyExpense</name>
   <tag></tag>
   <elementGuidId>c7d23832-7e8a-4770-88c6-18261b48efa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtMonthlyExpense</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMonthlyExpense']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cff3731e-e46a-4325-9222-e1183416047b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ffd7b065-e75d-42f8-b28c-e86608e53b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c3b0d51-0b32-4ae7-9b5a-584987f37405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>43ac3c34-a804-45d0-a1c6-080919a6ded1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMonthlyExpense</value>
      <webElementGuid>bc5ed81c-7ad6-4590-8b6d-0dd41c251d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMonthlyExpense&quot;)</value>
      <webElementGuid>46585859-0f0e-4914-bcbe-ffe89a54d969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMonthlyExpense']</value>
      <webElementGuid>f790f5fd-42d7-4ff0-b631-998bfc6fd32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[6]/div/input</value>
      <webElementGuid>6aa6170a-4b9f-4e4f-b52f-6ede9218da69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[6]/div/input</value>
      <webElementGuid>370addc1-64a1-4d91-afd2-d9b49e6d1af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtMonthlyExpense']</value>
      <webElementGuid>c93d748c-641f-4a56-a481-187a424056d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
