<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Numberof Household Member_txtHouseholdMember</name>
   <tag></tag>
   <elementGuidId>05ddc4f5-184d-4f54-85c3-4e640d709e8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtHouseholdMember</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtHouseholdMember']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a5f2641-98b7-4c2c-92e9-1f8a3344a947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cc2a38af-b419-4b47-838b-9a560e771885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3fbbb2c-761b-497f-85d8-2a34de1544cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>78a14176-48f7-49ac-99c1-01e1dd4f022a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return onlyNumberKey(event)</value>
      <webElementGuid>16cbbd93-3d7f-4c43-953b-ef4b6847b8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtHouseholdMember</value>
      <webElementGuid>275aad71-d7e4-4f2b-9858-ba6b650e0bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtHouseholdMember&quot;)</value>
      <webElementGuid>f281eb5e-af34-492f-bb08-02a6c9065932</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtHouseholdMember']</value>
      <webElementGuid>6930053a-a025-4739-b206-aeb1f85e0d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='7']/div/div/div/div[2]/div/input</value>
      <webElementGuid>f32b62f1-e684-4b09-8b22-400038ea0230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[2]/div/input</value>
      <webElementGuid>d75a0291-c945-45ea-87b4-713097201e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtHouseholdMember']</value>
      <webElementGuid>8b76b337-4040-43d1-ad11-c0618100df54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
