<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Placeof Issue_txtPlaceOfIssue</name>
   <tag></tag>
   <elementGuidId>4e29a374-b295-4c8d-a329-1e0f804e493c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPlaceOfIssue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPlaceOfIssue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f1a79ea-4ce7-4e2d-b28e-59f4c0d01c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>500b8fc1-b50f-44ce-8f63-cb36bf958281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e917c7e-15c5-47e2-9329-9ccb9fcdf854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs text-capitalize font-11</value>
      <webElementGuid>56109cb8-b165-4a9d-9ea0-148044fbcad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPlaceOfIssue</value>
      <webElementGuid>165b0ef7-0c5f-4495-90d4-e8fa920b5a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPlaceOfIssue&quot;)</value>
      <webElementGuid>adaab115-84c4-4484-8bdd-5a0350706983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPlaceOfIssue']</value>
      <webElementGuid>d5fb7488-e333-4a98-bb2b-45de608d1195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div/div/div/div[4]/div/input</value>
      <webElementGuid>8a831859-3918-4386-afa5-8deac9d919ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>886b36fe-010b-4f11-8e6c-3437d3ed9c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtPlaceOfIssue']</value>
      <webElementGuid>d51119af-4174-4e50-a833-b3612352bd39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
