<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Barangay CertificateBIR TI_0033e0</name>
   <tag></tag>
   <elementGuidId>2a01ca1a-0df0-4eeb-ad6a-16f22906d07b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboIDType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboIDType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>35c74ed6-4cce-41d9-a111-06972de7fa81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboIDType</value>
      <webElementGuid>e0feb6ee-a116-40d0-9bfe-07f979d52e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>IdPresented();</value>
      <webElementGuid>fa8aa268-9e95-4645-94f1-a9c755649211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>c688c60b-9694-41a6-a023-d309b6bf6517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--Barangay CertificateBIR TINCompany IDDriver's License IDGSIS IDNBI ClearanceOWWA IDPag-IBIG IDPassportPhilHealth IDPostal IDPRC IDSenior Citizen IDSSS IDUMIDVoter's ID</value>
      <webElementGuid>7ca4b40c-229c-445f-9e28-7c33d9bede0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboIDType&quot;)</value>
      <webElementGuid>04c1b618-0605-4526-8178-a1fd67e1a617</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboIDType']</value>
      <webElementGuid>b80cc616-a833-495b-8949-bcd15ab716ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div/div/div/div[2]/div/div/select</value>
      <webElementGuid>93219bc7-d181-4979-a54b-cf6cde3b4e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/select</value>
      <webElementGuid>0f12307e-9d34-4065-8daf-9588285d28db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboIDType' and (text() = concat(&quot;--Select--Barangay CertificateBIR TINCompany IDDriver&quot; , &quot;'&quot; , &quot;s License IDGSIS IDNBI ClearanceOWWA IDPag-IBIG IDPassportPhilHealth IDPostal IDPRC IDSenior Citizen IDSSS IDUMIDVoter&quot; , &quot;'&quot; , &quot;s ID&quot;) or . = concat(&quot;--Select--Barangay CertificateBIR TINCompany IDDriver&quot; , &quot;'&quot; , &quot;s License IDGSIS IDNBI ClearanceOWWA IDPag-IBIG IDPassportPhilHealth IDPostal IDPRC IDSenior Citizen IDSSS IDUMIDVoter&quot; , &quot;'&quot; , &quot;s ID&quot;))]</value>
      <webElementGuid>6625ece7-2bfc-4f2e-8dc6-51063b713039</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
