<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Referredby_relationshipIcon</name>
   <tag></tag>
   <elementGuidId>1af63cbc-26f5-4be7-af0e-07598bf6b607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#relationshipIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='relationshipIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>978dc51e-bb45-4248-a986-41b8d4037ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>relationshipIcon</value>
      <webElementGuid>0ccb2c72-13e7-46b6-9819-a4d37d43c4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-add-circle-fill</value>
      <webElementGuid>96feae34-b385-47c1-9c77-6b4dd264abf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;relationshipIcon&quot;)</value>
      <webElementGuid>bfcc144e-e5e5-4ad1-90af-3f2d5366bad2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='relationshipIcon']</value>
      <webElementGuid>c64dbc80-2a21-4b33-95f5-5adec257da0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btnRelationship']/i</value>
      <webElementGuid>d8c62dd6-da52-4a11-9647-63201eff752d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/a/i</value>
      <webElementGuid>0c314125-73df-4843-a5df-5508e31a8513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'relationshipIcon']</value>
      <webElementGuid>a29c85e8-3baf-4318-9e38-8551b261f402</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
