<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DOSRI_dosri</name>
   <tag></tag>
   <elementGuidId>d6ac8c47-6e5b-4487-9fb2-95f847ac814c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dosriNone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dosriNone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0911edd2-68ae-434f-92d7-eb29c9961506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>05bc0565-edb2-4c97-b679-fe949b832a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs  </value>
      <webElementGuid>a905cbed-e1c1-4fc4-8f7c-d7ae7e69a6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a9c05523-11d2-483d-b17e-5664c3183b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>dosri();</value>
      <webElementGuid>6de904df-0c71-439f-9d9e-f87211a94f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dosriNone</value>
      <webElementGuid>5a0b4279-87b0-484e-9afa-5a5834ff819f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dosri</value>
      <webElementGuid>e2f5c4d3-2fdb-43e2-8503-de45522227d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CLient Type</value>
      <webElementGuid>539e80ed-250c-4879-8262-88d18555ed36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dosriNone&quot;)</value>
      <webElementGuid>d4d1d61d-5157-4365-bd2f-36b670163152</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dosriNone']</value>
      <webElementGuid>895aa76d-6091-4bcd-b3ee-eb7e1025fec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/div/div/div[2]/div/input</value>
      <webElementGuid>d9ba7d18-fde9-499f-b38c-7a1e65cdfd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/input</value>
      <webElementGuid>d23cbcb9-5553-4abc-a727-fcfc45889975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dosriNone' and @name = 'dosri' and @placeholder = 'CLient Type']</value>
      <webElementGuid>ca169f5c-3c65-471b-977f-fca1c2789073</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
