<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nameof Staff_txtNameofStaff</name>
   <tag></tag>
   <elementGuidId>d870b1a6-642e-477b-8925-ce193060b4af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNameofStaff</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNameofStaff']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68dabe44-e9e5-4f81-8f2d-6596ff8df734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>54baf04d-da1a-45b4-8abf-a1a4416c276a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b03875e-10c9-4c86-a0bb-137e49c35d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs text-capitalize font-11</value>
      <webElementGuid>23380ad8-aff0-487a-a054-0a5abd98b2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNameofStaff</value>
      <webElementGuid>bd2c6729-0189-4f8b-a672-f4ca2ebef7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNameofStaff&quot;)</value>
      <webElementGuid>1f29efca-335b-4119-81aa-fe3df1fb4324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNameofStaff']</value>
      <webElementGuid>12c9aaa4-bbfb-4281-bbbe-3c66cf7a1a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/div/div/div[4]/div/input</value>
      <webElementGuid>6a4889f5-9ed7-4f06-bf7b-d10ff4e555c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[4]/div/input</value>
      <webElementGuid>3197d8fc-1c0e-4000-ab73-dc075482e3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtNameofStaff']</value>
      <webElementGuid>69804164-cf83-4947-aa3f-e7036d12e7d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
