<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--CARD Bank, Inc.CARD SME Ba_7bc8fb</name>
   <tag></tag>
   <elementGuidId>026bef3e-04c8-46c7-ada3-005f3dd275f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboDosriInstitution</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboDosriInstitution']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e44684c0-28ce-4b06-8157-e59997651256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboDosriInstitution</value>
      <webElementGuid>787db40a-177c-4752-a05e-d2fdc8512cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>ed1d61a7-5731-4abb-a542-a16bcb8d926a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--CARD Bank, Inc.CARD SME Bank, Inc.CARD MRI Holdings Inc.CARD MRI Rizal Bank, Inc.CARD MBA, Inc.CARD Pioneer, Inc.CaMIA, Inc.Fortress Data Services, Inc.CMIT, Inc.FDSAP, Inc.CBDSFI, Inc.Mga Likha ni Inay, Inc.CARD MRI Hijos Tours Inc.RISE Finance Company.CPMI - CARD MRICLFC, Inc.CARD EMPC, Inc.CMDI, Inc.PUBLISHING HOUSE, Inc.BotiCARD, Inc.CARD Inc.</value>
      <webElementGuid>415c8b1a-0d7c-4990-baf9-7ef7e58bfba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboDosriInstitution&quot;)</value>
      <webElementGuid>72a41880-9dbd-41ba-b00a-5b440ca6d28b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboDosriInstitution']</value>
      <webElementGuid>80631aee-3605-492c-a969-ede982954f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/div/div/div[6]/div/div/select</value>
      <webElementGuid>d1a8ca45-36de-4939-accc-68c555cac1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[6]/div/div/select</value>
      <webElementGuid>1551cbb8-3934-4c8b-b5cb-2c7494ba2649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboDosriInstitution' and (text() = '--Select--CARD Bank, Inc.CARD SME Bank, Inc.CARD MRI Holdings Inc.CARD MRI Rizal Bank, Inc.CARD MBA, Inc.CARD Pioneer, Inc.CaMIA, Inc.Fortress Data Services, Inc.CMIT, Inc.FDSAP, Inc.CBDSFI, Inc.Mga Likha ni Inay, Inc.CARD MRI Hijos Tours Inc.RISE Finance Company.CPMI - CARD MRICLFC, Inc.CARD EMPC, Inc.CMDI, Inc.PUBLISHING HOUSE, Inc.BotiCARD, Inc.CARD Inc.' or . = '--Select--CARD Bank, Inc.CARD SME Bank, Inc.CARD MRI Holdings Inc.CARD MRI Rizal Bank, Inc.CARD MBA, Inc.CARD Pioneer, Inc.CaMIA, Inc.Fortress Data Services, Inc.CMIT, Inc.FDSAP, Inc.CBDSFI, Inc.Mga Likha ni Inay, Inc.CARD MRI Hijos Tours Inc.RISE Finance Company.CPMI - CARD MRICLFC, Inc.CARD EMPC, Inc.CMDI, Inc.PUBLISHING HOUSE, Inc.BotiCARD, Inc.CARD Inc.')]</value>
      <webElementGuid>7df53278-e30d-4bc9-918a-c117dc305867</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
