<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BrotherDaughterFatherMothe_ec9985_1</name>
   <tag></tag>
   <elementGuidId>a271177e-3470-4c40-8aa7-b08eff36c1e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboImmediateFamily2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboImmediateFamily2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e40f127f-de09-4969-b4f7-a03930ba4941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-9</value>
      <webElementGuid>46e42caa-6033-4be6-9cdf-5606f392a660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboImmediateFamily2</value>
      <webElementGuid>6c85246e-85cc-4e49-820c-49e3b8a9c576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BrotherDaughterFatherMotherSisterSonSpouse</value>
      <webElementGuid>ab94de86-30cb-416b-bb98-535eebaddf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboImmediateFamily2&quot;)</value>
      <webElementGuid>bbcad160-64a1-4d61-8c61-20adde2f5b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboImmediateFamily2']</value>
      <webElementGuid>afb5f4be-941a-447e-a998-1266233ca0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div[4]/div/select</value>
      <webElementGuid>ffbb37e0-4f6b-42bb-a49e-bd590b7502f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Immediate Family Member If any'])[1]/preceding::select[1]</value>
      <webElementGuid>0ca9e8b0-9ff4-401a-8f37-b9f695e94a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Information'])[1]/preceding::select[1]</value>
      <webElementGuid>0c8f937e-8dcb-4552-856c-6493090f93d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/select</value>
      <webElementGuid>bede9e6c-78cf-4c1a-8ce4-81d5a83e69d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboImmediateFamily2' and (text() = '--Select--BrotherDaughterFatherMotherSisterSonSpouse' or . = '--Select--BrotherDaughterFatherMotherSisterSonSpouse')]</value>
      <webElementGuid>3b4719d4-89cf-40b6-b61a-f1fc86c23db4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
