<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BrotherBrother-in-LawCousi_e1fca2_1</name>
   <tag></tag>
   <elementGuidId>e31603dd-137f-4a77-b752-35eaedaacf23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboRelationshipType2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboRelationshipType2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>87a88712-7491-4f13-88e8-6b35d944d0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboRelationshipType2</value>
      <webElementGuid>1d2f38dd-7ce7-4861-8190-7c1cdaf2592e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>38c66060-d78e-4c05-bd8e-4f62be062f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse</value>
      <webElementGuid>10e6c7ef-8d06-435e-9d2d-b9ee40235d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboRelationshipType2&quot;)</value>
      <webElementGuid>0bdab95c-da54-4ad7-91a7-e8e63bbf85e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboRelationshipType2']</value>
      <webElementGuid>e99a2a88-a3b7-49cd-9fc2-69d11649b576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OtherRelationship']/div[2]/div/div/select</value>
      <webElementGuid>d217f9b7-0b82-4635-8235-8d38b90c86ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[5]/following::select[1]</value>
      <webElementGuid>c2636162-1300-406a-91b0-2da75246df4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/select</value>
      <webElementGuid>c7fd4254-aad2-4d9a-96df-5db17cb04018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboRelationshipType2' and (text() = '--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse' or . = '--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse')]</value>
      <webElementGuid>f06e125a-e373-40db-97e4-1b5d40dea3ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
