<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BrotherDaughterFatherMothe_ec9985</name>
   <tag></tag>
   <elementGuidId>18480658-c78c-4b30-9ccb-b62a778da2b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboPrimaryImmediateFamily</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboPrimaryImmediateFamily']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eb8fdf2c-73ff-422d-b259-96a2356eecdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboPrimaryImmediateFamily</value>
      <webElementGuid>07e1d899-673a-4c68-be2f-2ef77e4356bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-9</value>
      <webElementGuid>3f815791-376f-48b0-8f6d-dabcf1efa34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BrotherDaughterFatherMotherSisterSonSpouse</value>
      <webElementGuid>bb7374bc-4b54-4559-876a-68904a30495c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboPrimaryImmediateFamily&quot;)</value>
      <webElementGuid>f1415724-3ea8-437a-9c76-6a66f03b9317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboPrimaryImmediateFamily']</value>
      <webElementGuid>d13c9c82-a699-45a8-9776-1d574920374b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='relationshipRow1']/div/div[4]/div/select</value>
      <webElementGuid>b36c39ed-8be8-4165-add2-5b1456d823fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>3d093c97-3804-47ed-af22-09a0b8bc7dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboPrimaryImmediateFamily' and (text() = '--Select--BrotherDaughterFatherMotherSisterSonSpouse' or . = '--Select--BrotherDaughterFatherMotherSisterSonSpouse')]</value>
      <webElementGuid>6b303d6c-47c1-4738-9b34-bbc1ef6238f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
