<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LastName_txtmothersMaidenLName</name>
   <tag></tag>
   <elementGuidId>647907e5-2d81-4b0d-b406-17ce30bbe295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtmothersMaidenLName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtmothersMaidenLName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f731957-3d39-44ce-a2a9-fbaaa5b908d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a032ce47-6675-4c06-80a8-f7fe064dd8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36132229-8aa6-429c-90a4-a05755574306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs text-capitalize font-11</value>
      <webElementGuid>f92bb5d6-47ff-41e5-a91e-3dcd58edc1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtmothersMaidenLName</value>
      <webElementGuid>fb70e780-e01c-4403-9323-da36a8780ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checkNames();</value>
      <webElementGuid>f7cea0d5-584b-4b96-a97e-6b4703a93383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtmothersMaidenLName&quot;)</value>
      <webElementGuid>cac5e4aa-ad31-4c6b-9a9b-e0c337fe2fcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtmothersMaidenLName']</value>
      <webElementGuid>7f253e17-d32f-4795-9f56-9d46095bfdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[20]/div/input</value>
      <webElementGuid>5370b939-1560-426b-a718-d19177a65ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/input</value>
      <webElementGuid>2768c8ca-c210-41f8-bac1-d16c8cc92de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtmothersMaidenLName']</value>
      <webElementGuid>38f6141d-3b29-4c31-88c2-e2b83a9f432b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
