<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YES_CARDScholar</name>
   <tag></tag>
   <elementGuidId>f4957554-ec0c-400c-8bc8-b65e8116c3db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCARDScholarNO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCARDScholarNO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4878077c-26b7-498e-b573-91809ab59d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>14049b33-ef63-4da8-8703-28f155695a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs </value>
      <webElementGuid>f35a5c59-4b1c-4761-9c2c-3ca0035d282a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4342fd47-3cb2-4ac0-90cd-c83765f055de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCARDScholarNO</value>
      <webElementGuid>e813c9c1-449d-41b8-afee-26688aa2b4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CARDScholar</value>
      <webElementGuid>432f09e4-3fc0-4abd-9763-27bf59500742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCARDScholarNO&quot;)</value>
      <webElementGuid>35d674c5-379f-4963-b4ee-3289b97cfb99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCARDScholarNO']</value>
      <webElementGuid>c5dcfac5-3422-423f-ae29-8145e65f29e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[21]/div[2]/input</value>
      <webElementGuid>578b19fb-882a-4f11-84c4-89094244ae9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div[2]/input</value>
      <webElementGuid>0fdc40e9-6747-44b7-a083-7f07d7607068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'txtCARDScholarNO' and @name = 'CARDScholar']</value>
      <webElementGuid>4a1d7d32-33b2-4d8f-a9fe-bd3300674a3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
