<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PhilhealthNo_txtPhilhealth</name>
   <tag></tag>
   <elementGuidId>3b6d6f8e-6d85-43d8-becb-46f4203fb29f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPhilhealth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtPhilhealth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce7bb0c8-dafe-42d8-96c8-12df62b8ff18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aba742a8-3c5e-4118-bd7c-9ce94f77b6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPhilhealth</value>
      <webElementGuid>67fee9e0-3055-43ae-9ac3-9052378555be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>18ca8cc9-13ba-443e-96ce-cab3534d6b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>xx-xxxxxxxxx-x</value>
      <webElementGuid>e477aba6-3969-4837-96b9-9af1c902c254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>f12cb463-2f7a-430c-9c2f-4597fe2aa911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPhilhealth&quot;)</value>
      <webElementGuid>a3a36a5a-6742-4cb1-bd1c-bcf2b1c05577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPhilhealth']</value>
      <webElementGuid>bba45783-b808-4343-95e5-fb82699facd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[16]/div/div/input</value>
      <webElementGuid>4c3bfaff-1767-46e7-b842-61aa0f63d849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/input</value>
      <webElementGuid>01c25f9c-9db3-414e-8c9f-eb7c3b07f16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtPhilhealth' and @placeholder = 'xx-xxxxxxxxx-x']</value>
      <webElementGuid>0556b18f-8add-4934-9575-3a4fe2ff5666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
