<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pag-IBIGNo_txtPagIbig</name>
   <tag></tag>
   <elementGuidId>45355f0d-57d5-4ba0-8967-9497322c8968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPagIbig']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtPagIbig</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39c5b176-e24a-4ec9-9efa-f7694fe14c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>87739f94-290f-4013-8688-1d5c65bee9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPagIbig</value>
      <webElementGuid>5db182b4-b850-4f29-92da-997b07aecc4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>ca33b5c5-6c2a-436c-b747-e889a75dfd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>xxxx-xxxx-xxxx</value>
      <webElementGuid>601c9534-98f4-48f8-9f2c-b85b0fa37995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>8b480fae-7ea6-4ba3-9846-0d580e28e028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPagIbig&quot;)</value>
      <webElementGuid>fd6cd461-7976-46ed-a4c5-a8f2b0fbeea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPagIbig']</value>
      <webElementGuid>45660e8f-2aaa-4ca7-b62c-f6b8d22f2faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[17]/div/div/input</value>
      <webElementGuid>bfac1ea5-8419-4e82-8992-c4aae9abd64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/input</value>
      <webElementGuid>4af0fe55-334d-4ebd-99c5-68dc492e4753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtPagIbig' and @placeholder = 'xxxx-xxxx-xxxx']</value>
      <webElementGuid>29358d65-98a5-4ee8-ab8c-b37cc9e308a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
