<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --AlaminosBayBia_8f7d3f</name>
   <tag></tag>
   <elementGuidId>1872b677-ce86-4a7a-961a-8894fee04036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBdayMunicipalityCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboBdayMunicipalityCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>58822d49-4fbb-426f-8bdf-afb671ccf8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBdayMunicipalityCity</value>
      <webElementGuid>c910ce9d-4d46-418f-936b-d42fa6932e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>f11e82b7-d94e-4597-b539-951b2b89bbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>d75b396b-3a29-4d0c-aed8-cc60c3dd9866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --AlaminosBayBiñan CityCabuyao CityCalamba CityCalauanCavintiFamyKalayaanLiliwLos BañosLuisianaLumbanMabitacMagdalenaMajayjayNagcarlanPaetePagsanjanPakilPangilPilaRizalSan Pablo CitySan Pedro CitySiniloanSta. CruzSta. MariaSta. Rosa CityVictoria</value>
      <webElementGuid>799dce50-1e10-4824-93d7-e4767c9bc8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBdayMunicipalityCity&quot;)</value>
      <webElementGuid>3a9beb8e-13c3-46d5-b839-7eb65be2ac51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBdayMunicipalityCity']</value>
      <webElementGuid>2613a10b-4acf-44f3-94cd-811f135e0feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[9]/div/div/select</value>
      <webElementGuid>52c35140-a0df-4829-b44d-8fb720dc4238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div/div/select</value>
      <webElementGuid>2ebfd300-4448-4829-98a0-90cb9a1e0151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBdayMunicipalityCity' and (text() = '--      Select      --AlaminosBayBiñan CityCabuyao CityCalamba CityCalauanCavintiFamyKalayaanLiliwLos BañosLuisianaLumbanMabitacMagdalenaMajayjayNagcarlanPaetePagsanjanPakilPangilPilaRizalSan Pablo CitySan Pedro CitySiniloanSta. CruzSta. MariaSta. Rosa CityVictoria' or . = '--      Select      --AlaminosBayBiñan CityCabuyao CityCalamba CityCalauanCavintiFamyKalayaanLiliwLos BañosLuisianaLumbanMabitacMagdalenaMajayjayNagcarlanPaetePagsanjanPakilPangilPilaRizalSan Pablo CitySan Pedro CitySiniloanSta. CruzSta. MariaSta. Rosa CityVictoria')]</value>
      <webElementGuid>fbfee52e-893c-4ded-88fc-f31cdee2f0d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
