<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--No Formal EducationElement_aa261c</name>
   <tag></tag>
   <elementGuidId>8fd9e3d4-26ed-4df4-8a20-e12a07933b49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboEducationalLevel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboEducationalLevel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>59cc24c3-1104-44c0-a915-3e7d12fcb679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboEducationalLevel</value>
      <webElementGuid>02dd0f1f-a76e-4465-ba61-cd048d2c60ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>dc5701a4-05c2-44ae-848e-78453650115c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>043170a8-8eec-4da7-b379-3a49a1f71927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster's DegreeDoctorate Degree</value>
      <webElementGuid>59558f6f-619b-4235-a265-799f1953a8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboEducationalLevel&quot;)</value>
      <webElementGuid>723eaee1-d158-4c9c-9879-4240d895bff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboEducationalLevel']</value>
      <webElementGuid>12686a2b-4212-42f7-b1fc-42818a90e2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>8ef63f6d-98ad-4036-ba64-aba7bac30392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>24f298a5-ce81-49b2-bdde-00929ba71611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboEducationalLevel' and (text() = concat(&quot;--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster&quot; , &quot;'&quot; , &quot;s DegreeDoctorate Degree&quot;) or . = concat(&quot;--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster&quot; , &quot;'&quot; , &quot;s DegreeDoctorate Degree&quot;))]</value>
      <webElementGuid>7f855a80-bad6-4142-92cb-ec502d810369</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
