<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --Atty.Dr.Eng.Hon.MrMrsMs</name>
   <tag></tag>
   <elementGuidId>b334a745-5977-4527-82eb-2ae526bd9132</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7172d7e7-1ca6-44f2-9265-33ec8f1bf39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboTitle</value>
      <webElementGuid>11f7bf94-5409-4c13-841c-5f614941cf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateTitle();</value>
      <webElementGuid>b4622b2b-60b4-4e0b-9f49-25d3f8f67bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>a030b49d-cb73-4478-a139-9c8f8d27a996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>7fa6d609-fa72-4a4c-855b-c4c1ed086afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																		-- Select --Atty.Dr.Eng.Hon.MrMrsMs</value>
      <webElementGuid>793a86cc-c508-461c-b09f-20d4ddef8e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboTitle&quot;)</value>
      <webElementGuid>388138b2-90ff-4fec-adf3-063414b766ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboTitle']</value>
      <webElementGuid>e040675a-03de-48e1-99ef-28f93bc94439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[5]/div/select</value>
      <webElementGuid>9b262af9-530e-49cc-979f-a4cc90bd4821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>c3d9b941-525b-4e80-b140-ec1763632f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboTitle' and (text() = '
																		-- Select --Atty.Dr.Eng.Hon.MrMrsMs' or . = '
																		-- Select --Atty.Dr.Eng.Hon.MrMrsMs')]</value>
      <webElementGuid>caeda64b-215f-4af9-bf05-21ed74a12397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
