<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --4Ps BeneficiaryArtistChi_05c006</name>
   <tag></tag>
   <elementGuidId>a26427f5-748c-46f0-80e3-2380e9f37af8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboMemberSegmentation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboMemberSegmentation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>67966cdd-eb9e-41d4-a492-a7dbfc455f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboMemberSegmentation</value>
      <webElementGuid>477d11ae-210d-4b04-b914-bd91f9bc71a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>8d9c252d-a169-4437-80d6-080c8e7e258b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>b530ce53-4a74-4c3f-945c-3d1e46e2ee5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																			-- Select --4Ps BeneficiaryArtistChild of MemberClients Business in Market AreaDSHPK2C AgentMBA CoordinatorMIC AgentOFWPoliticianPWDShareholderSingle Parent</value>
      <webElementGuid>b858f8dc-c235-4553-9cd6-7fdae444c98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboMemberSegmentation&quot;)</value>
      <webElementGuid>0ea41e14-3fa5-43e3-a4d5-3b6f3cedc5ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboMemberSegmentation']</value>
      <webElementGuid>04c6f659-141d-42ee-8836-dcf1833cd07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[4]/div/div/select</value>
      <webElementGuid>a8fabb61-9f13-45f9-9f5b-84736006a2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/select</value>
      <webElementGuid>35763c9b-6479-4ff8-94ce-bd93a62a00b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboMemberSegmentation' and (text() = '
																			-- Select --4Ps BeneficiaryArtistChild of MemberClients Business in Market AreaDSHPK2C AgentMBA CoordinatorMIC AgentOFWPoliticianPWDShareholderSingle Parent' or . = '
																			-- Select --4Ps BeneficiaryArtistChild of MemberClients Business in Market AreaDSHPK2C AgentMBA CoordinatorMIC AgentOFWPoliticianPWDShareholderSingle Parent')]</value>
      <webElementGuid>776b2e3f-42dd-4c04-9b5c-4ffbd685835d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
