<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--GLIP 1GLIP 2IPPaglambo</name>
   <tag></tag>
   <elementGuidId>59a2c665-3cd0-4886-88e4-409e59136267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboIndivClassification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboIndivClassification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>61f56bf9-14e3-4969-96ba-a6b1380f9b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboIndivClassification</value>
      <webElementGuid>1154f8db-0d2c-49fa-86b2-4c8670af72d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>IndivClassification();</value>
      <webElementGuid>04e47cba-3866-41f6-a30f-81a7e912747c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>e51af676-9294-4885-8604-fb7337221dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>ec488497-4447-4de9-96a9-1adf089e3f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--GLIP 1GLIP 2IPPaglambo</value>
      <webElementGuid>10d67069-1785-46d6-ae19-16e4c3dce801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboIndivClassification&quot;)</value>
      <webElementGuid>60bf04ce-58aa-49c6-a11c-d2af85923b0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboIndivClassification']</value>
      <webElementGuid>2e52fbc4-8bd6-4515-a541-de941d44e9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8']/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>387aeb00-da21-4b25-862b-230112417672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Score:'])[1]/following::select[1]</value>
      <webElementGuid>840b5644-b2d2-4b1c-9f71-c25b52868965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health Declaration'])[1]/preceding::select[2]</value>
      <webElementGuid>78768096-0f0a-43d4-b6c8-1bd825e2c5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YES'])[11]/preceding::select[2]</value>
      <webElementGuid>56790f5d-c802-4268-958b-6df35cfaae19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>9df545c2-b872-426e-b434-b017af470f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboIndivClassification' and (text() = '--Select--GLIP 1GLIP 2IPPaglambo' or . = '--Select--GLIP 1GLIP 2IPPaglambo')]</value>
      <webElementGuid>7aafd455-56bd-40e8-84db-624fc4d3f8ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
