<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referredby_txtReferredbyOtherPrimary</name>
   <tag></tag>
   <elementGuidId>4af9c6dd-0689-44a1-848a-f331d16f3413</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtReferredbyOtherPrimary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtReferredbyOtherPrimary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53f132ea-3183-4814-9bf8-821b389779d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c4aa459e-5a51-461e-a186-141bba199228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c789aef-ecbd-4fe6-96f2-a5617e2defe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtReferredbyOtherPrimary</value>
      <webElementGuid>536822c9-6deb-4619-9958-68f75799887f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>Referredby();</value>
      <webElementGuid>6375798b-d881-4592-990e-4af9c010dbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11 text-capitalize</value>
      <webElementGuid>ea48ebeb-7afa-411d-8284-fc3f0a08e46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtReferredbyOtherPrimary&quot;)</value>
      <webElementGuid>3c316b6e-0e71-4d3a-9f53-5c15a171247c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtReferredbyOtherPrimary']</value>
      <webElementGuid>46f0c955-c7fd-4260-b5d4-6ae4b53787d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/div/div/div[7]/div[2]/div/input</value>
      <webElementGuid>2de08de3-6bdf-492d-a72c-d1ce1ed669f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/input</value>
      <webElementGuid>898bdd2a-d570-4365-bc2d-3a3ab0bd0f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtReferredbyOtherPrimary']</value>
      <webElementGuid>df48a03b-a75f-4f0c-ae3b-5f22aa90895a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
