<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Center_txtImmediateFamCID2</name>
   <tag></tag>
   <elementGuidId>aa2730b9-6578-4423-9b4d-6d6146a29358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtImmediateFamCID2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtImmediateFamCID2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5448c439-7c7d-4e73-a6e9-e3c5e91ef1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a49e6bb-f25c-4167-a8a8-7fa41f9f4259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-9</value>
      <webElementGuid>a5157782-8cef-4bc1-898f-72c31a496541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtImmediateFamCID2</value>
      <webElementGuid>f9e66888-1fb2-4f0e-9f26-881e56ece1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtImmediateFamCID2&quot;)</value>
      <webElementGuid>a119a477-ed25-4a80-a45c-b733dc37e0e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtImmediateFamCID2']</value>
      <webElementGuid>067e1fa4-ad27-47bb-af1c-068fb92f1e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div/div/input</value>
      <webElementGuid>9c7d099e-ecf2-45ce-80f3-a5a5587c78a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div/div/div/div/input</value>
      <webElementGuid>ad016c36-7fa1-4532-b359-18c2e36157d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtImmediateFamCID2']</value>
      <webElementGuid>1675e64a-7ea7-494b-abc7-ba5478c7a18f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
