<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nameof Staff_txtNameofStaff2</name>
   <tag></tag>
   <elementGuidId>206f64bd-0a20-411e-9ab0-cafb6847c893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNameofStaff2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNameofStaff2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bdcf468-8b04-42d4-8b5e-745b5e6817ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3d5134d7-03b2-49a6-a50e-4c037961ccd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a018e3d-85c6-4955-a33c-680a4cd834d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs text-capitalize font-11</value>
      <webElementGuid>07dffceb-556e-49e3-b42d-c15db4a48e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNameofStaff2</value>
      <webElementGuid>5b0b6024-f5c1-4033-b3fe-7ceb123ab357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNameofStaff2&quot;)</value>
      <webElementGuid>7a5b0160-9ab1-4c66-b614-d1805c3c82fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNameofStaff2']</value>
      <webElementGuid>0c998b55-5630-42a0-ac60-64c7fca20a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OtherRelationship']/div[3]/div/input</value>
      <webElementGuid>6ebab26b-162e-4efc-acd8-d2ab4f7a3b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/div/input</value>
      <webElementGuid>74919a2e-f41e-4c2c-8afc-1c6b54b706dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtNameofStaff2']</value>
      <webElementGuid>a526461c-7362-4f01-b9cc-eb6bcbb40561</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
