<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_None_drone2</name>
   <tag></tag>
   <elementGuidId>a83a74f4-1391-4464-9db2-cb0864ef8395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dosriYes2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dosriYes2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f74ae41a-c692-4030-b289-d4f58eed24cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>372de05f-d084-49a1-aed1-6ebccdfc184f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs</value>
      <webElementGuid>d11f3a1e-97fa-4572-822f-abc9fcdca15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>08387b4d-d323-4e3b-b5d3-63f0510dd3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>dosri();</value>
      <webElementGuid>0c84096a-ebf1-4933-981c-b62397ca68f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dosriYes2</value>
      <webElementGuid>b5225568-7ce8-4572-8d6f-d40192e2ab3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>drone2</value>
      <webElementGuid>08843035-07bf-4f48-882e-dae9c8875512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CLient Type</value>
      <webElementGuid>8435952c-bbe7-4c78-a040-9d18bc7ae9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dosriYes2&quot;)</value>
      <webElementGuid>4afba93f-f945-4732-9676-5695b1378e55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dosriYes2']</value>
      <webElementGuid>4f14bb17-6519-4f1e-91a7-e8af6c18720b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OtherRelationship']/div/div[2]/input</value>
      <webElementGuid>909f9604-98c5-4ec7-a33b-e2a65678427a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/input</value>
      <webElementGuid>0a7e079a-00b8-4ef9-b84d-733dc1d276fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dosriYes2' and @name = 'drone2' and @placeholder = 'CLient Type']</value>
      <webElementGuid>1f6b476f-3c7b-4c82-9ba7-ed04e596ace3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
