<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CID_txtPrimaryImmediateFamCID</name>
   <tag></tag>
   <elementGuidId>b3f6bbdc-eec9-4c63-a139-eceb3a50a6bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPrimaryImmediateFamCID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPrimaryImmediateFamCID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ed43923-b720-45b8-9de7-aebce72fb8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b2822b7f-9d9a-415d-b4be-269412bc109c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f51da3b5-69f5-42e6-bf61-be3268fc957a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPrimaryImmediateFamCID</value>
      <webElementGuid>3a819e76-c1fd-48c7-b032-4d85e5ab1045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-9</value>
      <webElementGuid>a5634844-7451-4a7d-9640-2ed9e959e702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPrimaryImmediateFamCID&quot;)</value>
      <webElementGuid>a3bbe10e-fdde-4113-9151-dcabb78add3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPrimaryImmediateFamCID']</value>
      <webElementGuid>876512db-c3f3-40bd-8662-5e01eed4369a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='relationshipRow1']/div/div/div/input</value>
      <webElementGuid>b8f40876-fdeb-4df1-90c3-3e39852d0aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/input</value>
      <webElementGuid>2b4bd188-bf9b-446d-b198-5f35b24a6ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtPrimaryImmediateFamCID']</value>
      <webElementGuid>c218883f-70c2-480f-a771-4bae56bdbd7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
