<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BrotherBrother-in-LawCousi_e1fca2</name>
   <tag></tag>
   <elementGuidId>4271bd78-ade7-4510-b7bd-0a0bf889623e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboRelationshipType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboRelationshipType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d7db1a95-00a0-4e4e-a326-591ece74fb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboRelationshipType</value>
      <webElementGuid>afe9b3f6-34b9-45f1-a0e7-30847236abdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>21d548a2-54ad-44dd-8329-cfde5084f191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse</value>
      <webElementGuid>0476088a-2a9c-409a-bf81-bdd34e41fc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboRelationshipType&quot;)</value>
      <webElementGuid>d487b44c-e237-4587-b656-6c65f38f52b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboRelationshipType']</value>
      <webElementGuid>ef17b5fe-a597-4dca-a0ac-2437af98d101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>a1fa105a-3276-4de8-8c67-a5ec7257d4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[4]/following::select[1]</value>
      <webElementGuid>d26737ff-383a-4237-b6d7-d2467d7944fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[3]/div/div/select</value>
      <webElementGuid>030b6688-a65e-4c9e-b0b2-970b0d4c58b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboRelationshipType' and (text() = '--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse' or . = '--Select--BrotherBrother-in-LawCousinDaughterFatherFather-in-LawMotherMother-in-LawOther relativesSisterSister-in-LawSonSpouse')]</value>
      <webElementGuid>47854dc5-b986-4b0d-a120-ae194ea73c20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
