<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDNumber_txtIdNumber</name>
   <tag></tag>
   <elementGuidId>8b42885e-1e2b-4897-b923-67b22ca0e81b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtIdNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtIdNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df80d9d9-45c6-4f13-be4d-0c4b7e1cd369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>36f2ee1f-3167-4999-a65d-81d15993619f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10860412-cfbf-4af1-ae72-cf9dbf7b85d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>c90d822c-98e0-4a5e-beef-9ee6e871033d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtIdNumber</value>
      <webElementGuid>c90a93f5-8cf4-4e12-ab27-19788caad0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtIdNumber&quot;)</value>
      <webElementGuid>8ad5bdb4-6463-485c-8012-fb3c70e1925c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtIdNumber']</value>
      <webElementGuid>dae6615f-b1a4-4d62-9f0a-0ea7a4373fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div/div/div/div[3]/div/input</value>
      <webElementGuid>d7ff8085-71d4-483e-8351-c82e3c84a700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>76e79561-6b5e-4528-9a91-c3502b0b9f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtIdNumber']</value>
      <webElementGuid>04995db8-4968-4b08-ab5d-dbf4f2ce5131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
