<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_toggletxtPassword</name>
   <tag></tag>
   <elementGuidId>096e2d69-8240-45fe-8cb8-e3c4c2d9f1b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='toggletxtPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#toggletxtPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ccd27009-f98c-4aad-9ac4-ae7c64b96452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-eye-off-outline</value>
      <webElementGuid>dc20a16a-b378-421b-9722-3b4b202a66fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggletxtPassword</value>
      <webElementGuid>0e1f4e50-b89b-4379-ab96-7565e2d006aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showPass()</value>
      <webElementGuid>4ff05a28-7b25-4cca-9520-73f04333963e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggletxtPassword&quot;)</value>
      <webElementGuid>0b845332-9ba9-4df8-8503-34fd18d51693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='toggletxtPassword']</value>
      <webElementGuid>4cb3a4af-0db2-4bf4-968c-0d18b3c67587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div/div/div[3]/form/div[2]/div/span/i</value>
      <webElementGuid>45a6796a-2193-43f8-a88f-6abb5b3d50c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>76b61d30-8731-4164-9644-6d1183f0e369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'toggletxtPassword']</value>
      <webElementGuid>69586e31-900d-4a31-8b36-acd268b585fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
