<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--IIIIIIVJrNoneSrVVI</name>
   <tag></tag>
   <elementGuidId>76eee052-80af-4b03-aab0-91e5956b5ee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboSuffix</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSuffix']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a5d2d458-f178-480c-9633-c11d0e4463d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSuffix</value>
      <webElementGuid>fa6d8611-327c-4ac8-bcce-2ad7b4a41f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs</value>
      <webElementGuid>0d1563e9-234c-4f18-b163-299d31b231a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--IIIIIIVJrNoneSrVVI</value>
      <webElementGuid>7caa7081-0880-4927-8d09-2f78984f57c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSuffix&quot;)</value>
      <webElementGuid>5299a4ca-b686-4de9-aeb0-445cf150bfe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSuffix']</value>
      <webElementGuid>05ca563b-5abf-46e4-8618-295c0491b72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='validationForm']/div/div[2]/div[2]/div/div/select</value>
      <webElementGuid>c899ae69-4a9e-4926-a4d8-aae670d04c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEARCH'])[1]/preceding::select[1]</value>
      <webElementGuid>08a5cdc5-de55-4828-af99-f013f51632f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::select[1]</value>
      <webElementGuid>baf74aa9-d271-4c12-a78d-41b9499818ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2b28cf75-a626-42c0-b0f9-cdc1841c5457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSuffix' and (text() = '--Select--IIIIIIVJrNoneSrVVI' or . = '--Select--IIIIIIVJrNoneSrVVI')]</value>
      <webElementGuid>77c68c2c-dea7-4f77-9670-e528fff7cca5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
