<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HouseNo.BldgStreetSubdivision_txthous_59daa2</name>
   <tag></tag>
   <elementGuidId>a8a5bdb8-54f0-447c-ad45-5777f5c08604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txthouseNoStreesAdd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txthouseNoStreesAdd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2ba3475-5119-4568-8e5c-4f726f6c5130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1946c065-0c11-41b4-acdd-8dd53a927652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>931cacde-0248-409b-b602-6ade4c46bc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs text-capitalize font-11</value>
      <webElementGuid>1edcde2a-f4d0-4c5a-8643-2a98204428e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txthouseNoStreesAdd</value>
      <webElementGuid>51aaf63a-cba3-482b-90ef-4a00394831bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txthouseNoStreesAdd&quot;)</value>
      <webElementGuid>9357aa61-ec98-4bcf-9c0f-d66d97aab626</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txthouseNoStreesAdd']</value>
      <webElementGuid>4ed2cac7-dc5c-4bd5-9662-5063f34fafb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div/div/div[7]/div/input</value>
      <webElementGuid>4bce135d-6e9c-46b2-bc81-eea0e078daba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[7]/div/input</value>
      <webElementGuid>4ec49dd6-b4ae-4c78-b5ff-73462e60469f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txthouseNoStreesAdd']</value>
      <webElementGuid>27e3fb91-9a05-4630-936b-d40fec6d5cb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
