<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--      Select      --AlaminosBayBia_8f7d3f</name>
   <tag></tag>
   <elementGuidId>f8c42e3e-dc33-48c9-8d28-f79ca4a03d47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboPhyMunicipalityCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboPhyMunicipalityCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8759bc5d-951f-44b7-992e-e66689153a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboPhyMunicipalityCity</value>
      <webElementGuid>772d33f7-71fa-4b9d-aa74-08c1749d22fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>b6544e12-6a0f-4a69-b7ab-7afb2291766c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --AlaminosBayBiñan CityCabuyao CityCalamba CityCalauanCavintiFamyKalayaanLiliwLos BañosLuisianaLumbanMabitacMagdalenaMajayjayNagcarlanPaetePagsanjanPakilPangilPilaRizalSan Pablo CitySan Pedro CitySiniloanSta. CruzSta. MariaSta. Rosa CityVictoria</value>
      <webElementGuid>820d0d45-c1cb-47cf-8514-9ace08d51736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboPhyMunicipalityCity&quot;)</value>
      <webElementGuid>bb100902-d251-40ae-8710-72937cdcbdbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboPhyMunicipalityCity']</value>
      <webElementGuid>4a4c407c-2ad5-49c6-b138-321206fac1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>863d6cc4-148b-4ba4-a5c9-c42183f3973a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[4]/div/div/select</value>
      <webElementGuid>dd650e82-f982-4671-a06a-0d6267066c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboPhyMunicipalityCity' and (text() = '--      Select      --AlaminosBayBiñan CityCabuyao CityCalamba CityCalauanCavintiFamyKalayaanLiliwLos BañosLuisianaLumbanMabitacMagdalenaMajayjayNagcarlanPaetePagsanjanPakilPangilPilaRizalSan Pablo CitySan Pedro CitySiniloanSta. CruzSta. MariaSta. Rosa CityVictoria' or . = '--      Select      --AlaminosBayBiñan CityCabuyao CityCalamba CityCalauanCavintiFamyKalayaanLiliwLos BañosLuisianaLumbanMabitacMagdalenaMajayjayNagcarlanPaetePagsanjanPakilPangilPilaRizalSan Pablo CitySan Pedro CitySiniloanSta. CruzSta. MariaSta. Rosa CityVictoria')]</value>
      <webElementGuid>01176657-93d0-4d33-920a-4d9b84c300b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
