<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--AnnulledLive-inMarriedSepa_54a068</name>
   <tag></tag>
   <elementGuidId>a70c71d7-9400-416f-a3d4-56a6145f4e0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCivilStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCivilStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bcacac4e-8b59-44fc-a759-0e4040afde67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCivilStatus</value>
      <webElementGuid>a7d0f31c-4422-4ba9-af44-79ba5cfd4e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CivilStatusType();</value>
      <webElementGuid>0057de01-a510-4b2e-aad6-df71b1b3c682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>e8f65f4a-b965-401f-b461-86290f337c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>eac2de4a-5cfe-4de7-90c3-35c040c52260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AnnulledLive-inMarriedSeparatedSingleWidowed</value>
      <webElementGuid>3836aa9b-34de-4cf8-ba8c-1abaf2171ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCivilStatus&quot;)</value>
      <webElementGuid>be0766c7-3cf0-4bac-80f8-a8e6ee8dace3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCivilStatus']</value>
      <webElementGuid>a741654f-c3de-4a06-ae49-674ea6558dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[12]/div/div/select</value>
      <webElementGuid>569e61d3-c91f-4d99-8822-1607f44771a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/select</value>
      <webElementGuid>075af340-f5bc-446e-99d6-cfb4be2ab8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCivilStatus' and (text() = '--Select--AnnulledLive-inMarriedSeparatedSingleWidowed' or . = '--Select--AnnulledLive-inMarriedSeparatedSingleWidowed')]</value>
      <webElementGuid>88ce5465-32d8-44fa-a4bd-8e6726e44d1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
