<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Former Employee_FormerEmployee</name>
   <tag></tag>
   <elementGuidId>b3f20e3a-958d-460e-b2eb-e31e0e238ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtFormerEmployeeYES']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtFormerEmployeeYES</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dff47eb3-c886-4e0b-9959-a6c3b1765575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e5a36252-a7ce-49b3-848c-096a5a58768b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs</value>
      <webElementGuid>98d010b1-0ff5-40a6-8c09-79abe0da2877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ef2ded91-d5fa-4003-90eb-54acd3a8b770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFormerEmployeeYES</value>
      <webElementGuid>250415f9-7fce-473c-8500-c2310a89b636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FormerEmployee</value>
      <webElementGuid>3cff4769-1ac8-4aed-a7f8-b1a5018510b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFormerEmployeeYES&quot;)</value>
      <webElementGuid>4e71457b-8b6b-4ddb-b87f-81d6caa1fb36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtFormerEmployeeYES']</value>
      <webElementGuid>cf1f902e-d98f-48ab-abba-61c13a3d54f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[22]/div/input</value>
      <webElementGuid>248850bc-13ee-4e9b-9117-bdec0a7e4703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/input</value>
      <webElementGuid>2e8b5006-dd76-48c2-abae-7715e185ab4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'txtFormerEmployeeYES' and @name = 'FormerEmployee']</value>
      <webElementGuid>62ec3278-01f3-47c3-9df7-8b70906962a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
