<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_IIIIIIVJrNoneSrVVI</name>
   <tag></tag>
   <elementGuidId>b7feec7d-0d47-4798-a344-2fb01f772357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSuffix']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboSuffix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5c66cb4c-29c1-4b9e-aef3-de435e8ef0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSuffix</value>
      <webElementGuid>0d0d008c-8721-4745-9876-db488de6e96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>38a75273-79f1-49ba-9e80-5d25a32a599a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>e00c050c-220d-42bf-b4c3-022c959678f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IIIIIIVJrNoneSrVVI</value>
      <webElementGuid>3e45899b-7fb2-45a0-ac03-04ee01974e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSuffix&quot;)</value>
      <webElementGuid>702af737-4ef4-43a6-aea5-0d57b812136c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSuffix']</value>
      <webElementGuid>cd8c7734-72a2-44a3-bddb-7902a1b6ef61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[9]/div/div/select</value>
      <webElementGuid>883d647a-abb7-45eb-af9f-5c6ff0683266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/select</value>
      <webElementGuid>54366a57-b6eb-4bbe-8707-66dda12c0166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSuffix' and (text() = 'IIIIIIVJrNoneSrVVI' or . = 'IIIIIIVJrNoneSrVVI')]</value>
      <webElementGuid>7e6f2122-75b0-48fc-92ef-35da76aa99e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
