<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--AnnulledLive-inMarriedSeparatedSingleWidowed</name>
   <tag></tag>
   <elementGuidId>a4bbdb7d-d05f-4fa2-bc34-aa9eb0956f8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCivilStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboCivilStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6632a048-a04f-4354-b0bf-d575b33d2780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCivilStatus</value>
      <webElementGuid>5c7fb1b9-9c99-47c0-9487-3de91d62dcce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CivilStatusType();</value>
      <webElementGuid>6ae76803-89de-4c32-9aea-6d64ed841445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>ebeb3a9f-940d-4eff-8ab6-b263dbc1584e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>35becc83-e543-436c-b746-1d65fbb0b2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AnnulledLive-inMarriedSeparatedSingleWidowed</value>
      <webElementGuid>0dacb561-9d2f-486e-9bfc-91f09ef0417f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCivilStatus&quot;)</value>
      <webElementGuid>9a17eca5-7fe3-4283-91a9-f13b2c5c3457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCivilStatus']</value>
      <webElementGuid>a017baa3-110b-444b-8a26-75397ab0bc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[12]/div/div/select</value>
      <webElementGuid>9db2f9a6-54c1-4352-a861-49a1d72faf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/select</value>
      <webElementGuid>e84b2f6b-0143-4f7e-8261-5c74ddbb684c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCivilStatus' and (text() = '--Select--AnnulledLive-inMarriedSeparatedSingleWidowed' or . = '--Select--AnnulledLive-inMarriedSeparatedSingleWidowed')]</value>
      <webElementGuid>22f68450-f443-4d46-9556-0cb35d6f95b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
