<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --Atty.Dr.Eng.Hon.MrMrsMs</name>
   <tag></tag>
   <elementGuidId>068bdf12-9cd4-4b0a-aab1-7d705893d438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>256ef377-3552-49ce-ad73-830a5adb2027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboTitle</value>
      <webElementGuid>b3a7587f-f9af-428f-9a4d-14782e577006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateTitle();</value>
      <webElementGuid>7752ca48-9cb6-4856-b798-1f944448d814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>89e86a22-030c-4c3d-8d87-5b6d22e2de88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>06ef5325-eb1b-4b93-a52d-2ec627ec7d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																		-- Select --Atty.Dr.Eng.Hon.MrMrsMs</value>
      <webElementGuid>123056f8-414a-4e21-9db9-73a913f09d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboTitle&quot;)</value>
      <webElementGuid>1a6023ec-cd9e-4104-a42f-9f97a8296c52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboTitle']</value>
      <webElementGuid>ea7473c5-f8b4-4679-be3c-01df439021c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[5]/div/select</value>
      <webElementGuid>c4d15c6e-e7e0-4e8e-bef2-1aba282ef7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>2bcc62e8-a92d-481a-8df2-997a088e8079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboTitle' and (text() = '
																		-- Select --Atty.Dr.Eng.Hon.MrMrsMs' or . = '
																		-- Select --Atty.Dr.Eng.Hon.MrMrsMs')]</value>
      <webElementGuid>acd00fff-6fdb-44e0-9e58-b537f978af5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
