<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Municipality</name>
   <tag></tag>
   <elementGuidId>d6b1202d-dda1-42db-8f3c-31c1f5d9cff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBdayMunicipalityCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboBdayMunicipalityCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ce5dc3ac-6388-4abf-8172-5270a4a9f34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBdayMunicipalityCity</value>
      <webElementGuid>7a434fac-5ff5-4fd1-8eff-fa6f202b2d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>618ea5d4-89dc-4098-9507-a060692c9930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>077dce02-eab4-4539-a3f9-5c574afa1c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--      Select      --Brgysample3PhilippinesSamplebrgy2Test1</value>
      <webElementGuid>62a76779-0df5-43ff-bb81-a8d9ff7a0270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBdayMunicipalityCity&quot;)</value>
      <webElementGuid>8d025717-a5de-4643-93dc-eee8c56f68c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBdayMunicipalityCity']</value>
      <webElementGuid>8e3ee0ad-af36-48ec-940a-3c576826e431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[9]/div/div/select</value>
      <webElementGuid>fc0cf18e-8a88-402b-b043-9601164cb5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div/div/select</value>
      <webElementGuid>23cf06cd-3b61-4e9f-97df-7f9d91acf27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBdayMunicipalityCity' and (text() = '--      Select      --Brgysample3PhilippinesSamplebrgy2Test1' or . = '--      Select      --Brgysample3PhilippinesSamplebrgy2Test1')]</value>
      <webElementGuid>ca14c639-b295-40ac-ad66-05d2e0cc1a38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
