<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password_input-group-text</name>
   <tag></tag>
   <elementGuidId>f88fe77c-becf-4869-a5fb-a9863bc3eb12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div/div/div/div[3]/form/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.input-group-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2ed54cd9-6514-4c84-88df-9abedd9c8bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-text</value>
      <webElementGuid>816e015e-0743-42c8-b58e-70c9d6307c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;auth-fluid&quot;]/div[@class=&quot;auth-fluid-form-box&quot;]/div[@class=&quot;card-body d-flex flex-column h-100 gap-3&quot;]/div[3]/form[1]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;input-group form-group mb-2 bmd-form-group is-filled&quot;]/span[@class=&quot;input-group-text&quot;]</value>
      <webElementGuid>1132d284-d746-478b-a77f-1c1856019dea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div/div/div/div[3]/form/div[2]/div/span</value>
      <webElementGuid>9b606d23-8ac0-40ae-b82c-c180c8e92025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/following::span[1]</value>
      <webElementGuid>7f16b00f-d62c-498a-b660-ef3f6c61cda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username:'])[1]/following::span[2]</value>
      <webElementGuid>03f831e5-fab8-4192-81ad-8629c868f144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::span[1]</value>
      <webElementGuid>3b637750-9c85-447f-bc81-d45443acad06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>ac42b52a-c89e-4160-8ed4-57a093015a70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
