<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Health Declaration_healthDeclaration</name>
   <tag></tag>
   <elementGuidId>030e83d1-eeaf-4147-ad47-814d646bb7be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#healthDeclarationYes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='healthDeclarationYes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d4725d9-79a8-412b-a14a-16fd0f8afc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>18af5eae-6398-45f6-962a-5254cbcaada2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs</value>
      <webElementGuid>364f9747-255d-4406-886f-a12f398dba09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>52442df0-18e2-4b78-af5d-825cb6dbf35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>isGoodCondition();</value>
      <webElementGuid>c008b833-5c2b-4b63-a5d9-8e1b8c0732bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>healthDeclarationYes</value>
      <webElementGuid>7beb5529-d79a-44d0-8e35-00c07f136de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>healthDeclaration</value>
      <webElementGuid>faabe585-6ffe-49ee-8afb-8d19d65db5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CLient Type</value>
      <webElementGuid>561a374d-e87a-4f4b-b692-a2f47cd50481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;healthDeclarationYes&quot;)</value>
      <webElementGuid>862eadf1-7609-455b-95ba-2bd1b23f10f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='healthDeclarationYes']</value>
      <webElementGuid>a5fe3e29-cc2e-4f73-be6a-8392eb4fbbd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='9']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>6a8779ef-06f3-4d0b-8def-8358ad2fd4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>c6125a6a-36f1-4213-9814-77c076d0d5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'healthDeclarationYes' and @name = 'healthDeclaration' and @placeholder = 'CLient Type']</value>
      <webElementGuid>895c9056-da8f-42d0-99fe-5f1cbda30034</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
