<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Center_btnrow1</name>
   <tag></tag>
   <elementGuidId>a8ad7719-f8a9-40b9-853c-576533a95c8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnrow1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='btnrow1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2387e36d-06b1-4829-9707-c033d98a526c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnrow1</value>
      <webElementGuid>1bd7c781-eeba-4254-8adb-8939e1fc89ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-add-circle-fill</value>
      <webElementGuid>d104d83e-9fcb-4249-bbc1-3adfa3e635e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-row-button&quot;)/i[@id=&quot;btnrow1&quot;]</value>
      <webElementGuid>5a83aede-1935-493b-b6f8-36e5b1df12f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='btnrow1']</value>
      <webElementGuid>a761412c-bf72-40f9-b68a-ec750a3aa313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='add-row-button']/i</value>
      <webElementGuid>f886094e-dffb-455c-a12c-b3d62d539883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/a/i</value>
      <webElementGuid>9cd6f032-885c-4f5f-8594-c5d9d9abe489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'btnrow1']</value>
      <webElementGuid>9760cca8-cee0-4b4e-89e3-19a92a47610f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
