<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Center_txtImmediateFamCID3</name>
   <tag></tag>
   <elementGuidId>d8931611-49d2-4828-9852-641bdd8bb5f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtImmediateFamCID3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtImmediateFamCID3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a72a248-4751-4806-a8f3-3b67f9f513e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6ea889c-73fb-447c-b576-d87e652d220e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-9</value>
      <webElementGuid>f7080145-5c73-4fa7-bfd3-14ab072f4ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtImmediateFamCID3</value>
      <webElementGuid>62aedfe3-2542-4c71-8e5f-c0f9dc34e18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtImmediateFamCID3&quot;)</value>
      <webElementGuid>990960e5-c975-41bb-8005-a7411b46ae2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtImmediateFamCID3']</value>
      <webElementGuid>0fca8d76-73eb-4696-8566-4340170e33b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row3']/div/div/div/input</value>
      <webElementGuid>1977b587-e54f-44ff-a2fd-fa0e94a7f224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>4c7bb327-e54b-4716-b979-e10d2b907a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtImmediateFamCID3']</value>
      <webElementGuid>44661f8d-59aa-4fef-8298-6820f11c2768</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
