<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NONE_dosri</name>
   <tag></tag>
   <elementGuidId>9643b002-a72a-4dac-8ad9-8e6f24c3bf3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dosriYes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dosriYes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74b6f426-c88f-4683-96bb-f54dba01430f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e84614e2-6c05-45d1-a7f8-64af3d12f5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs  </value>
      <webElementGuid>d80cc9be-4552-4672-9207-7ceb4436fd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4dbb9aac-9425-4989-ae5f-c832e397ff66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>dosri();</value>
      <webElementGuid>d9f74070-ea6e-4d97-a44e-9c2514071c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dosriYes</value>
      <webElementGuid>8542d650-c98a-4ca7-b9e6-1709e1df04ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dosri</value>
      <webElementGuid>a8e96f6d-be23-4751-9654-38ea2884662b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CLient Type</value>
      <webElementGuid>93458423-66e8-4210-9ccc-83ff5dfd2f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dosriYes&quot;)</value>
      <webElementGuid>df91daea-8c92-4783-9105-49e6c2c89d36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dosriYes']</value>
      <webElementGuid>49486b47-e94f-408d-8d0b-9ae6474f643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>25c2fd02-7f91-439f-9c0e-dc4da88eb212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>529186f8-d7f3-4ef4-a2b1-2e2c5018a66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dosriYes' and @name = 'dosri' and @placeholder = 'CLient Type']</value>
      <webElementGuid>ad1f0be4-7646-4eed-afa4-4e7b01b47453</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
