<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YES_dosri</name>
   <tag></tag>
   <elementGuidId>920437a4-f667-4ef9-b2ab-28354c463e6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dosriNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dosriNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60c09546-306a-4be2-beff-5076fbd7747e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7d9cba30-c115-4452-a90e-3def2ec102a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input gb-border-fcs  </value>
      <webElementGuid>f1039df3-3977-4512-8bd7-f3326fc764d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4bc5d358-ac7f-48fe-bf23-6c970db93772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>dosri();</value>
      <webElementGuid>2b976d1d-3a37-4c26-a569-af86b6804b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dosriNo</value>
      <webElementGuid>d4defa32-9a33-4677-89b5-cf5b45f3c655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dosri</value>
      <webElementGuid>25bfe0d7-7344-434a-8eb8-f2c7e9585023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dosriNo&quot;)</value>
      <webElementGuid>3ad8db0a-80a5-4287-8222-a8baabc5c7f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dosriNo']</value>
      <webElementGuid>dd0e154e-5871-4b8d-8e14-826ad7094cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/div/div/div[2]/div[3]/input</value>
      <webElementGuid>372c6a06-085d-405d-a7c6-c8302d2efdb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>3fe427ae-be21-4199-8fae-31ede4422ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'dosriNo' and @name = 'dosri']</value>
      <webElementGuid>a1a74482-23cb-400e-8a57-fbe121a16d08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
