<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Select --CARD MRI MemberCARD MRI _8bd785</name>
   <tag></tag>
   <elementGuidId>02a5105c-7eae-4361-a773-750b2da91e2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboReferredbyPrimary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboReferredbyPrimary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1dd6720b-4eaa-4671-90b5-c85933d9f62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboReferredbyPrimary</value>
      <webElementGuid>5b9093f1-0a2a-4daa-9dcc-9c052b07bb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>Referredby();</value>
      <webElementGuid>631760f0-c720-4449-beab-cac474d5133f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>d78f6433-04c2-4299-9310-ebb7ed5bea8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --CARD MRI MemberCARD MRI StaffOthers</value>
      <webElementGuid>9480bd41-17bc-4939-8cc0-87660efa7c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboReferredbyPrimary&quot;)</value>
      <webElementGuid>8dff7445-4cc1-4672-8611-34165ed7e1ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboReferredbyPrimary']</value>
      <webElementGuid>79ffac5a-82fa-49c5-ba5e-301c508434f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/div/div/div[7]/div/div/select</value>
      <webElementGuid>b169ca29-8681-4001-9fb5-6b3866548813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOSRI :'])[2]/preceding::select[1]</value>
      <webElementGuid>95682a8e-f5c1-4666-a509-86771589e447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[7]/div/div/select</value>
      <webElementGuid>b48b884e-870b-4af7-a274-4fdaedd4cf88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboReferredbyPrimary' and (text() = '-- Select --CARD MRI MemberCARD MRI StaffOthers' or . = '-- Select --CARD MRI MemberCARD MRI StaffOthers')]</value>
      <webElementGuid>bd3e06c2-622c-402a-ba4d-7a766072e819</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
