<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BrotherDaughterFatherMothe_ec9985_1_2</name>
   <tag></tag>
   <elementGuidId>5709c689-cc7d-48df-a907-82ca68b47145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboImmediateFamily3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboImmediateFamily3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5f9e8702-ea86-4822-b80a-7dd5b876edfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-9</value>
      <webElementGuid>7440fe6d-33e6-4f32-86eb-b562b37c44c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboImmediateFamily3</value>
      <webElementGuid>004bfec8-819d-4d3d-886d-af90f58eaa74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BrotherDaughterFatherMotherSisterSonSpouse</value>
      <webElementGuid>f786eedb-963a-4f1b-95e7-102213324d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboImmediateFamily3&quot;)</value>
      <webElementGuid>26d6d70f-1a2d-4514-8f55-9f3f32f18c5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboImmediateFamily3']</value>
      <webElementGuid>c36ac38c-e36b-4d35-95a0-1c9f2974a6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row3']/div/div[4]/div/select</value>
      <webElementGuid>08a42f34-4d5c-4eca-935b-268dd8259834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Immediate Family Member If any'])[1]/preceding::select[1]</value>
      <webElementGuid>a6d1b5df-83f2-4a23-b9e0-3195c332e7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Information'])[1]/preceding::select[1]</value>
      <webElementGuid>a98408ad-7bf4-4ac8-bd53-e8b45dc94622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/select</value>
      <webElementGuid>c8486ef5-8b75-4705-ab89-d775cf2898ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboImmediateFamily3' and (text() = '--Select--BrotherDaughterFatherMotherSisterSonSpouse' or . = '--Select--BrotherDaughterFatherMotherSisterSonSpouse')]</value>
      <webElementGuid>ebeefa72-1b0e-4b83-b9cf-81dd6eb2847e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
