<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Select      51015</name>
   <tag></tag>
   <elementGuidId>4e089a4e-3697-4395-8854-26d12f5867f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tblRiskclassSixBody']/tr/td[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>55210c3e-00ac-418a-851f-99b72b4100d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center </value>
      <webElementGuid>98ab02a2-0189-415b-81e9-445c8a06aca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Select      51015</value>
      <webElementGuid>ac82b8db-1ddf-4f6f-b40d-a93c62f113e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblRiskclassSixBody&quot;)/tr[1]/td[@class=&quot;text-center&quot;]</value>
      <webElementGuid>688f2237-5dfe-4267-abca-3ca991fb6ad3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tblRiskclassSixBody']/tr/td[9]</value>
      <webElementGuid>ed4ba9d4-b023-4cca-9903-16bd081ac003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino, gaming, broker-dealers'])[1]/following::td[1]</value>
      <webElementGuid>7059f3dc-f351-411b-96db-33fcc7710b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All other business other than mentioned in high risk'])[1]/following::td[3]</value>
      <webElementGuid>7442e980-590d-480e-b384-f6bf349e3953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Types of service / products to be availed of'])[1]/preceding::td[2]</value>
      <webElementGuid>453e6f90-a435-4913-a644-30c8e6420600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBU/Micro-savings/ Micro-insurance/Microloans'])[1]/preceding::td[4]</value>
      <webElementGuid>1a09560a-fa13-4eec-bfa2-8e068697c51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[6]/tr/td[9]</value>
      <webElementGuid>412d8b59-2a3f-48cc-b916-e158e5356032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '     Select      51015' or . = '     Select      51015')]</value>
      <webElementGuid>35c64c3f-91b8-4417-8133-feaebd632c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
