<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pag-IBIGNo_txtPagIbig</name>
   <tag></tag>
   <elementGuidId>2ed96627-0a01-4238-b4c5-360081a4989d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPagIbig']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtPagIbig</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a07ea8b2-e2ea-41e1-8ad3-9ff6b1be1f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2ff3a66f-8752-4a32-95a4-25fcea71cea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPagIbig</value>
      <webElementGuid>4e992190-41de-43fe-b450-7d2482a5395d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>987ef5c9-ca33-49cb-bcbc-4f7c9817b720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>xxxx-xxxx-xxxx</value>
      <webElementGuid>2c0b4d11-e6ab-4ab3-aed3-8010362fced5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs font-11</value>
      <webElementGuid>aa29c4b6-7db5-4843-aabe-2383fd7781a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPagIbig&quot;)</value>
      <webElementGuid>6c62e1a8-b7da-4432-a2e0-d0d0a6ce16ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPagIbig']</value>
      <webElementGuid>247e28fd-945b-45fe-ad02-495aa1af7b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[17]/div/div/input</value>
      <webElementGuid>7f10cf0b-693a-4987-b69d-c682e2a362f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/input</value>
      <webElementGuid>2713e318-0388-4cb7-8829-7b31543b601c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtPagIbig' and @placeholder = 'xxxx-xxxx-xxxx']</value>
      <webElementGuid>0145c8b4-31bd-4608-a7ba-1dcb28501f96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
