<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Citizenship</name>
   <tag></tag>
   <elementGuidId>0a211c72-8025-4b13-9447-c8f057b08b04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboNationality']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboNationality</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4d97aae1-7de4-4b60-9269-b21e199fc92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboNationality</value>
      <webElementGuid>ccc3948c-0156-4f68-b3bd-cdb4351376ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>bffca384-f3bf-487b-8a7e-fcfbff5bd0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>24334f62-cc2c-45e0-bec5-0b28662d6637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--AfghanAlbanianAlgerianAndorranAngolanAntiguan or BarbudanArgentineArmenianAustralianAustrianAzerbaijani, AzeriBahamianBahrainiBarbadianBasothoBelarusianBelgianBelizeanBengaliBeninese, BeninoisBhutaneseBissau-GuineanBolivianBosnian or HerzegovinianBrazilianBruneianBulgarianBurkinabéBurmeseBurundianCabo VerdeanCambodianCameroonianCanadianCentral AfricanChadianChileanChineseColombianComoran, ComorianCongoleseCosta RicanCroatianCubanCypriotCzechDanishDjiboutianDominicanDutch, NetherlandicEcuadorianEgyptianEmirati, Emirian, EmiriEquatorial Guinean, EquatoguineanEritreanEstonianEthiopianFijianFilipinoFinnishFrenchGaboneseGambianGeorgianGermanGhanaianGibraltarGreek, HellenicGrenadianGuatemalanGuineanGuyaneseHaitianHonduranHungarian, MagyarIcelandicI-KiribatiIndianIndonesianIranian, PersianIraqiIrishIsraeliItalianIvorianJamaicanJapaneseJordanianKazakhstani, KazakhKenyanKittitian or NevisianKuwaitiKyrgyzstani, Kyrgyz, Kirgiz, KirghizLao, LaotianLatvian, LettishLebaneseLiberianLibyanLiechtensteinerLithuanianLuxembourg, LuxembourgishMacedonianMalagasyMalawianMalaysianMaldivianMalian, MalineseMalteseMarshalleseMartiniquais, MartinicanMauritanianMauritianMexicanMicronesianMoldovanMonégasque, MonacanMongolianMontenegrinMoroccanMotswana, BotswananMozambicanNamibianNauruanNepali, NepaleseNew Zealand, NZ, ZelanianNicaraguanNigerianNigerienNi-Vanuatu, VanuatuanNorthern MariananNorth KoreanNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapua New Guinean, PapuanParaguayanPeruvianPolishPortuguesePuerto RicanQatariRomanianRussianRwandanSaint LucianSaint Vincentian, VincentianSalvadoranSammarineseSamoanSão ToméanSaudi, Saudi ArabianSenegaleseSerbianSeychelloisSierra LeoneanSingapore, SingaporeanSlovakSlovenian, SloveneSolomon IslandSomaliSouth AfricanSouth KoreanSouth SudaneseSpanishSri LankanSudaneseSurinameseSwaziSwedishSwissSyrianTajikistaniTanzanianThaiTimoreseTogoleseTokelauanTonganTrinidadian or TobagonianTunisianTurkishTurkmenTuvaluanUgandanUK, BritishUkrainianUnited States, U.S., AmericanUruguayanUzbekistani, UzbekVaticanVenezuelanVietnameseYemeniZambianZimbabwean</value>
      <webElementGuid>6397b0bd-e161-4f90-a777-d38e42c502ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboNationality&quot;)</value>
      <webElementGuid>b0f5e32b-589e-4063-ba34-160a1b03b727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboNationality']</value>
      <webElementGuid>4de0d8bf-dc88-4da6-9b5e-492a6dfef3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[4]/div/div/select</value>
      <webElementGuid>3d15e09f-36f0-4241-a49c-b2eaa6698be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div/select</value>
      <webElementGuid>6222e54b-b24c-4ab6-a3b5-75c6927cba7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboNationality' and (text() = '--Select--AfghanAlbanianAlgerianAndorranAngolanAntiguan or BarbudanArgentineArmenianAustralianAustrianAzerbaijani, AzeriBahamianBahrainiBarbadianBasothoBelarusianBelgianBelizeanBengaliBeninese, BeninoisBhutaneseBissau-GuineanBolivianBosnian or HerzegovinianBrazilianBruneianBulgarianBurkinabéBurmeseBurundianCabo VerdeanCambodianCameroonianCanadianCentral AfricanChadianChileanChineseColombianComoran, ComorianCongoleseCosta RicanCroatianCubanCypriotCzechDanishDjiboutianDominicanDutch, NetherlandicEcuadorianEgyptianEmirati, Emirian, EmiriEquatorial Guinean, EquatoguineanEritreanEstonianEthiopianFijianFilipinoFinnishFrenchGaboneseGambianGeorgianGermanGhanaianGibraltarGreek, HellenicGrenadianGuatemalanGuineanGuyaneseHaitianHonduranHungarian, MagyarIcelandicI-KiribatiIndianIndonesianIranian, PersianIraqiIrishIsraeliItalianIvorianJamaicanJapaneseJordanianKazakhstani, KazakhKenyanKittitian or NevisianKuwaitiKyrgyzstani, Kyrgyz, Kirgiz, KirghizLao, LaotianLatvian, LettishLebaneseLiberianLibyanLiechtensteinerLithuanianLuxembourg, LuxembourgishMacedonianMalagasyMalawianMalaysianMaldivianMalian, MalineseMalteseMarshalleseMartiniquais, MartinicanMauritanianMauritianMexicanMicronesianMoldovanMonégasque, MonacanMongolianMontenegrinMoroccanMotswana, BotswananMozambicanNamibianNauruanNepali, NepaleseNew Zealand, NZ, ZelanianNicaraguanNigerianNigerienNi-Vanuatu, VanuatuanNorthern MariananNorth KoreanNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapua New Guinean, PapuanParaguayanPeruvianPolishPortuguesePuerto RicanQatariRomanianRussianRwandanSaint LucianSaint Vincentian, VincentianSalvadoranSammarineseSamoanSão ToméanSaudi, Saudi ArabianSenegaleseSerbianSeychelloisSierra LeoneanSingapore, SingaporeanSlovakSlovenian, SloveneSolomon IslandSomaliSouth AfricanSouth KoreanSouth SudaneseSpanishSri LankanSudaneseSurinameseSwaziSwedishSwissSyrianTajikistaniTanzanianThaiTimoreseTogoleseTokelauanTonganTrinidadian or TobagonianTunisianTurkishTurkmenTuvaluanUgandanUK, BritishUkrainianUnited States, U.S., AmericanUruguayanUzbekistani, UzbekVaticanVenezuelanVietnameseYemeniZambianZimbabwean' or . = '--Select--AfghanAlbanianAlgerianAndorranAngolanAntiguan or BarbudanArgentineArmenianAustralianAustrianAzerbaijani, AzeriBahamianBahrainiBarbadianBasothoBelarusianBelgianBelizeanBengaliBeninese, BeninoisBhutaneseBissau-GuineanBolivianBosnian or HerzegovinianBrazilianBruneianBulgarianBurkinabéBurmeseBurundianCabo VerdeanCambodianCameroonianCanadianCentral AfricanChadianChileanChineseColombianComoran, ComorianCongoleseCosta RicanCroatianCubanCypriotCzechDanishDjiboutianDominicanDutch, NetherlandicEcuadorianEgyptianEmirati, Emirian, EmiriEquatorial Guinean, EquatoguineanEritreanEstonianEthiopianFijianFilipinoFinnishFrenchGaboneseGambianGeorgianGermanGhanaianGibraltarGreek, HellenicGrenadianGuatemalanGuineanGuyaneseHaitianHonduranHungarian, MagyarIcelandicI-KiribatiIndianIndonesianIranian, PersianIraqiIrishIsraeliItalianIvorianJamaicanJapaneseJordanianKazakhstani, KazakhKenyanKittitian or NevisianKuwaitiKyrgyzstani, Kyrgyz, Kirgiz, KirghizLao, LaotianLatvian, LettishLebaneseLiberianLibyanLiechtensteinerLithuanianLuxembourg, LuxembourgishMacedonianMalagasyMalawianMalaysianMaldivianMalian, MalineseMalteseMarshalleseMartiniquais, MartinicanMauritanianMauritianMexicanMicronesianMoldovanMonégasque, MonacanMongolianMontenegrinMoroccanMotswana, BotswananMozambicanNamibianNauruanNepali, NepaleseNew Zealand, NZ, ZelanianNicaraguanNigerianNigerienNi-Vanuatu, VanuatuanNorthern MariananNorth KoreanNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapua New Guinean, PapuanParaguayanPeruvianPolishPortuguesePuerto RicanQatariRomanianRussianRwandanSaint LucianSaint Vincentian, VincentianSalvadoranSammarineseSamoanSão ToméanSaudi, Saudi ArabianSenegaleseSerbianSeychelloisSierra LeoneanSingapore, SingaporeanSlovakSlovenian, SloveneSolomon IslandSomaliSouth AfricanSouth KoreanSouth SudaneseSpanishSri LankanSudaneseSurinameseSwaziSwedishSwissSyrianTajikistaniTanzanianThaiTimoreseTogoleseTokelauanTonganTrinidadian or TobagonianTunisianTurkishTurkmenTuvaluanUgandanUK, BritishUkrainianUnited States, U.S., AmericanUruguayanUzbekistani, UzbekVaticanVenezuelanVietnameseYemeniZambianZimbabwean')]</value>
      <webElementGuid>3a75b9b0-c6ac-48a7-bb32-2cde078ca5bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
