<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SexualOrientation</name>
   <tag></tag>
   <elementGuidId>18e8fc01-592d-4e26-b554-15e9ca188c95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboSexualOrientation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboSexualOrientation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7ad33b2e-a94c-4d60-a39c-dfcc1d1b7a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboSexualOrientation</value>
      <webElementGuid>34bc7089-7796-46ec-ac95-14ca6602d830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateTitle();</value>
      <webElementGuid>6faf7c7f-7726-4222-a5eb-3a387c1c4b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>63a30919-9c49-41b2-8fdf-b987f498929e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>ad74ecea-6d3f-478e-8fa6-356c1dda1513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BisexualGayLesbianQueerTransgender+AgenderAsexual+Bigender+Gender Queer+Gender VirantIntersex+Pangender+PansexualQuestioning</value>
      <webElementGuid>df3763dc-6872-47ee-ba50-c8f78115759a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboSexualOrientation&quot;)</value>
      <webElementGuid>f1c2cd09-1b66-4336-8f93-6e2a2ddf9f8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboSexualOrientation']</value>
      <webElementGuid>ce56c792-ae86-4ef9-850a-547087023e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div/div/div[11]/div/div/select</value>
      <webElementGuid>f554ba1c-03e4-44e5-af77-a99851a9cc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/select</value>
      <webElementGuid>3218d9a7-53e1-45dc-b905-83b1875099b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboSexualOrientation' and (text() = '--Select--BisexualGayLesbianQueerTransgender+AgenderAsexual+Bigender+Gender Queer+Gender VirantIntersex+Pangender+PansexualQuestioning' or . = '--Select--BisexualGayLesbianQueerTransgender+AgenderAsexual+Bigender+Gender Queer+Gender VirantIntersex+Pangender+PansexualQuestioning')]</value>
      <webElementGuid>3984cfa9-667f-4ec7-a762-2315ddf92597</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
