<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Country</name>
   <tag></tag>
   <elementGuidId>8da7f105-b701-4a11-9223-ebe388380021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBdayCountry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboBdayCountry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8f074c7a-f135-4522-bd16-9905e20a4949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBdayCountry</value>
      <webElementGuid>9f9b2359-d251-4a67-bc36-64dffbda8ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs select2 font-11</value>
      <webElementGuid>11e5811a-7b80-4606-8a80-f30210c05a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>select2</value>
      <webElementGuid>374c16f1-1812-44e3-8828-b0cb9968ba89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>undefinedBrgysample3PhilippinesSamplebrgy2Test1</value>
      <webElementGuid>9c634239-ebbc-4512-a894-2707000ddef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBdayCountry&quot;)</value>
      <webElementGuid>94d3fd07-d560-4e2a-a3ac-4ae5e5384d19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBdayCountry']</value>
      <webElementGuid>e92d6f53-2d16-460a-bfe7-d779e0e21db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0']/div/div/div[2]/div[2]/div[7]/div/div/select</value>
      <webElementGuid>638928b3-9fd7-4449-a452-b5f6b6abff76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='undefined']/parent::*</value>
      <webElementGuid>7f12d1e8-e697-42a5-a156-04f3fff2796a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>4d4e2c47-4292-4b9f-a2e9-6c675f0770b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBdayCountry' and (text() = 'undefinedBrgysample3PhilippinesSamplebrgy2Test1' or . = 'undefinedBrgysample3PhilippinesSamplebrgy2Test1')]</value>
      <webElementGuid>934fbcc9-1166-4113-9562-98dce23e1a4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
