<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DATEOPENED_txtiAgreeCBU</name>
   <tag></tag>
   <elementGuidId>1a1b8cda-776b-499b-bd8c-f8ddda7a1b98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtiAgreeCBU</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtiAgreeCBU']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eaf26099-59b3-4e1c-b128-ac4f9cc7c408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>642d7968-7f1b-412e-971a-d67bf022f87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input </value>
      <webElementGuid>ae0799bf-b773-4125-b318-42f2fcb30f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7047422b-1561-4724-864f-7b644bcd2184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtiAgreeCBU</value>
      <webElementGuid>165a685d-1d0d-4cc0-806c-d95b66686238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtiAgreeCBU&quot;)</value>
      <webElementGuid>cd8ad93c-9776-4662-9abd-ba53f09c9a40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtiAgreeCBU']</value>
      <webElementGuid>70cbc36a-df32-4e28-9b22-cbdd28caa5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='9']/div/div/div[4]/div/div[2]/div/div/div/div[7]/div/input</value>
      <webElementGuid>4db90300-728c-434d-a546-5bf8c2f20d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/div[7]/div/input</value>
      <webElementGuid>b1b0371b-c138-45bd-9e0e-0422d2303c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'txtiAgreeCBU']</value>
      <webElementGuid>f91a4305-f90e-4e41-b247-4e7437e594b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
