<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SourceOf Income_txtCompanyname</name>
   <tag></tag>
   <elementGuidId>1bb012b4-81a6-4f94-8cad-e399a6472499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCompanyname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCompanyname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2739bb90-df47-4f6c-ae57-e98e77ddf4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4a5ca867-3611-44fd-9e0a-32e34d37446f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>766d2764-cf2d-4c48-bba3-dff21edec6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCompanyname</value>
      <webElementGuid>c9c473ca-7157-48ca-9254-e88f57ad2706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>edda8a97-78ad-4713-9694-c084abea27d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control gb-border-fcs text-capitalize font-11 </value>
      <webElementGuid>3a20c769-9153-441e-97ac-3d039ad82d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Company name</value>
      <webElementGuid>a414b494-f0fa-450e-bc9c-8578246d393d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCompanyname&quot;)</value>
      <webElementGuid>d93c09cb-55a5-4605-bc96-448f8eb480f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCompanyname']</value>
      <webElementGuid>ef751ac9-4c3f-4544-b6fe-5efb5f7d788f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SourceOfFund']/div/div/input</value>
      <webElementGuid>49b43d65-222f-4bd5-a0ed-3815b48fbaf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>45f4e5ee-3d2f-4dbb-be29-1e250b583c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtCompanyname' and @placeholder = 'Enter Company name']</value>
      <webElementGuid>7403ff95-191c-4775-94b1-d6182301591a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
