<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dateof Marriage_txtSpouseDateOfMarraige</name>
   <tag></tag>
   <elementGuidId>4c3d10d8-8eca-4dee-a4ed-b763a30752fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSpouseDateOfMarraige</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSpouseDateOfMarraige']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5eda398-8ba1-4f1a-9399-1429205a11ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2de51a9e-649c-4bc7-bc9b-2dc774b247c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>d0752ab0-21b8-4e1f-9c6f-ae338d81b80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2999-12-12</value>
      <webElementGuid>ba105b65-6a22-4576-922e-bf3b780ba425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-uppercase gb-border-fcs datepicker font-11</value>
      <webElementGuid>6fc25288-a380-4662-b51a-cacf31a8a39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>36ee3826-421d-41bb-b953-3cff66d3831f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSpouseDateOfMarraige</value>
      <webElementGuid>09ff9d96-ecd6-4573-8c88-1dd597427c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSpouseDateOfMarraige&quot;)</value>
      <webElementGuid>be9f8c60-4b3b-4461-9756-743ef27388e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSpouseDateOfMarraige']</value>
      <webElementGuid>a2813cee-9875-4742-95af-9bfaa6c641b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5']/div/div/div[2]/div/div/div[9]/div/input</value>
      <webElementGuid>a016bdf2-5abb-413f-8518-1014f949460e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>73b63c22-9372-49ca-a254-16027d958598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'txtSpouseDateOfMarraige']</value>
      <webElementGuid>17f6ca0a-42b7-42da-b22e-e9a786a0c43e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
