<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--NAPrimarySecondary</name>
   <tag></tag>
   <elementGuidId>83b6b236-58b6-4e88-a632-cb00f6152cf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboBeneficiary2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboBeneficiary2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2b9262d1-dd74-4d0a-ac99-d97596bfbc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboBeneficiary2</value>
      <webElementGuid>9223e041-7482-4040-b3eb-f9833d7d37f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b6dc34f8-fc7c-49bc-9c4e-4ea67a345d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateBeneficiary(2)</value>
      <webElementGuid>3817b53b-3030-465d-b1f0-0901291b4d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>e602eb64-28ce-4fc3-a930-69db50e0f9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--N/APrimarySecondary </value>
      <webElementGuid>b7fd68fe-7002-4489-bc0d-4086ea41b35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboBeneficiary2&quot;)</value>
      <webElementGuid>a644fb10-148f-4f7e-a991-e1005d4ade1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboBeneficiary2']</value>
      <webElementGuid>6895933a-8884-4b95-951a-66d7911bac07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row2']/div/div[6]/div/div/select</value>
      <webElementGuid>148bbab7-1323-499e-8def-5d283348a3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[11]</value>
      <webElementGuid>fa5cd601-3479-4d38-9db5-4c74e1e9fcd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[4]</value>
      <webElementGuid>9cb906f4-0e86-426d-8b62-2b0e5c81a32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[4]</value>
      <webElementGuid>76b5e5a5-26f2-4e64-a742-fcc92dc9b28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[6]/div/div/select</value>
      <webElementGuid>97734723-8eeb-4c75-b137-98c76a20288c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboBeneficiary2' and (text() = '--Select--N/APrimarySecondary ' or . = '--Select--N/APrimarySecondary ')]</value>
      <webElementGuid>537fb506-f182-4d4b-89c8-d0bccc7ee4dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
