<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--No Formal EducationElement_aa261c_1</name>
   <tag></tag>
   <elementGuidId>5a862c06-e45a-4f03-84c9-8ff3987c6a12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboEducationalAttainment1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboEducationalAttainment1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>70a6415c-3a13-48d8-ae22-8baaecc40a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboEducationalAttainment1</value>
      <webElementGuid>b77032c1-194d-45a3-9db5-b71819993b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6840fc09-5ed7-4a96-b213-76bbc11690d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>75ecd55c-ae41-413e-a9c5-5f94cb3e4f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster's DegreeDoctorate Degree</value>
      <webElementGuid>3168fce6-9b51-4142-b5d5-1477a5999abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboEducationalAttainment1&quot;)</value>
      <webElementGuid>4e869b2a-7154-43c0-9f75-d27dd32276ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboEducationalAttainment1']</value>
      <webElementGuid>638cd555-c2cd-4c18-b92c-5fdbef9cc7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row1']/div/div[5]/div/div/select</value>
      <webElementGuid>f99603dc-d4f2-44eb-9e60-57876545fc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[3]</value>
      <webElementGuid>1a04fe9a-3805-4319-9f1d-9d32cfbf82b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[5]</value>
      <webElementGuid>b0b7bbd3-8133-4f21-a7fc-1132eb5e5add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[5]</value>
      <webElementGuid>9b1cf38d-96d9-4d78-97e2-8b8be126eb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[5]/div/div/select</value>
      <webElementGuid>35ed6e32-c78e-480e-bcb7-6dcdc8fb4eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboEducationalAttainment1' and (text() = concat(&quot;--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster&quot; , &quot;'&quot; , &quot;s DegreeDoctorate Degree&quot;) or . = concat(&quot;--Select--No Formal EducationElementary UndergraduateElementary GraduateHigh School UndergraduateHigh School GraduateVocationalAssociate DegreeCollege UndergraduateCollege GraduateMaster&quot; , &quot;'&quot; , &quot;s DegreeDoctorate Degree&quot;))]</value>
      <webElementGuid>888f6f66-82ba-494e-8923-2054a95b9fe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
