<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--FemaleMale_1_2_3</name>
   <tag></tag>
   <elementGuidId>7fe2533b-0b7b-4da6-863d-e10bafa91561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboGender3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboGender3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23836186-5f97-4e96-98db-b2d206599770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboGender3</value>
      <webElementGuid>0c43b78e-2c14-4d1b-be78-7eae0b82ee5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6423a900-06b9-4999-a70e-e6b72f2dbd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>4dc0ba24-7c12-4b73-a0df-edad32097647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--FemaleMale</value>
      <webElementGuid>bb6c873d-efa5-4d39-bdd9-4912b7c8851e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboGender3&quot;)</value>
      <webElementGuid>a393f768-ef86-44a4-bb2c-1c0ffa7115c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboGender3']</value>
      <webElementGuid>997edc42-c42f-4959-8c42-d2c8df31b121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row3']/div/div[4]/div/div/select</value>
      <webElementGuid>5406c3e3-ead8-4391-b0d5-d40ab4217e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[16]</value>
      <webElementGuid>fe2393e5-c890-4e0b-bbb0-bd1b1d135571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[6]</value>
      <webElementGuid>1eaefcf0-a004-47e6-8e2a-7af05b940fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[6]</value>
      <webElementGuid>5e265b8b-b619-4518-9c71-7e9fc46981ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[4]/div/div/select</value>
      <webElementGuid>48820361-1b2c-4e1d-b835-bc9c3ddd5f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboGender3' and (text() = '--Select--FemaleMale' or . = '--Select--FemaleMale')]</value>
      <webElementGuid>97f288aa-6f83-4581-a3f0-49e389192851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
