<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--BeneficiaryLegal Dependent_a71cea</name>
   <tag></tag>
   <elementGuidId>39544835-8745-4b39-8a44-66edede71d40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboRemarks1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboRemarks1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e5a238ae-dc9a-40f0-a427-3280c5161309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboRemarks1</value>
      <webElementGuid>2b4e827a-5019-47d1-8d26-c3189267fc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>89c0fab6-4a04-4a50-932f-e070593b797c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>beneficiaryRemarks($('#txtBeneficiaryBday1').val(), $('#cboWithDisability1').val(),$('#cboRemarks1').val(),'#cboRemarks1');</value>
      <webElementGuid>68668a91-2056-455b-89e6-12804a4eda10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>fba0fdd2-63aa-42f2-907e-21fda396ce5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary</value>
      <webElementGuid>714092ba-6caf-4335-a39f-bf9e7c3c750f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboRemarks1&quot;)</value>
      <webElementGuid>21605fda-bfba-4b75-a806-1337b9ecfc94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboRemarks1']</value>
      <webElementGuid>5341a57b-81f5-4124-a1e0-ed81dfa12bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row1']/div/div[10]/div/div/select</value>
      <webElementGuid>94544c82-36ac-4c87-a98b-596c58bb89b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[7]</value>
      <webElementGuid>abb09af1-1409-427f-865f-513a12649190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[1]</value>
      <webElementGuid>0766ad4f-16a2-4f69-8e27-6e4b67111cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[1]</value>
      <webElementGuid>6cc25a6d-ee22-4dc4-81b7-63b3f2e083bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[10]/div/div/select</value>
      <webElementGuid>4727389d-af7e-41cb-8377-69bac5a921bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboRemarks1' and (text() = '--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary' or . = '--Select--BeneficiaryLegal DependentLegal Dependent and Beneficiary')]</value>
      <webElementGuid>86f70eed-7d19-4b9f-9fcb-3214675077fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
