<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--YESNO_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>21f7091d-a132-49ab-92e0-24f047de5a24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboCardMRIScho3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboCardMRIScho3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>837427bf-716e-4f5c-97dd-da25bb093b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboCardMRIScho3</value>
      <webElementGuid>6c94ee99-739b-46db-a325-745b35fd0caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b66d69f6-4e64-420a-b4fc-dadfc8e6fc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required gb-border-fcs font-9</value>
      <webElementGuid>eb16faa3-e14c-4220-99fb-2185edb6ab96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					--Select--
					YES
					NO
				</value>
      <webElementGuid>9117ecb7-c12f-4e9d-bae8-398235987697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboCardMRIScho3&quot;)</value>
      <webElementGuid>bbd43ae3-804d-47c9-b5ee-89ad75e6205f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboCardMRIScho3']</value>
      <webElementGuid>3fe6333c-8193-4aab-ab0c-c9039af1b90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row3']/div/div[9]/div/div/select</value>
      <webElementGuid>1daca043-0729-4db3-bcaa-baaff1ab3ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks:'])[1]/following::select[20]</value>
      <webElementGuid>b9efef56-5116-4811-9c7f-8d85167e90b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Beneficiary If any'])[1]/preceding::select[2]</value>
      <webElementGuid>399ba152-6bd9-4d85-b923-f3623aa0b54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Risk Assessment'])[2]/preceding::select[2]</value>
      <webElementGuid>72908938-5313-4ffb-a5dd-cdbac5b1d7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[9]/div/div/select</value>
      <webElementGuid>58fca132-4024-42f1-9998-a20ca572efd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboCardMRIScho3' and (text() = '
					--Select--
					YES
					NO
				' or . = '
					--Select--
					YES
					NO
				')]</value>
      <webElementGuid>6146ac35-6e44-48d9-b02b-11694d0a1a51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
